# Generated by Django 5.1.15 on 2026-07-01 18:27

import apps.suporte_claro.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuporteClaroRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(db_index=True, max_length=128)),
                ('irregularidade', models.TextField(blank=True, default='')),
                ('avaliacao', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(db_index=True)),
                ('sent_by', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em atendimento'), ('concluido', 'Concluído')], db_index=True, default='aberto', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suporte_claro_registros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suporte_claro_registro',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuporteClaroAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.suporte_claro.models.anexo_upload_to)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='suporte_claro.suporteclaroregistro')),
            ],
            options={
                'db_table': 'suporte_claro_anexo',
                'ordering': ['id'],
            },
        ),
    ]
