# Generated by Django 5.2.14 on 2026-07-17 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplicacaoD1Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('data_referencia_d1', models.DateField(db_index=True)),
                ('data_execucao', models.DateTimeField(blank=True, null=True)),
                ('parquet_referencia', models.CharField(blank=True, default='', max_length=255)),
                ('auditores_ativos_brflow', models.PositiveIntegerField(blank=True, null=True)),
                ('auditores_ativos_case', models.PositiveIntegerField(blank=True, null=True)),
                ('protocolos_total', models.PositiveIntegerField(default=0)),
                ('workflows_total', models.PositiveIntegerField(default=0)),
                ('workflows_salvo_ok', models.PositiveIntegerField(default=0)),
                ('source_file', models.CharField(blank=True, default='', max_length=1024)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'replicacao_d1_run',
                'ordering': ['-data_referencia_d1', '-run_id'],
            },
        ),
        migrations.CreateModel(
            name='ReplicacaoD1SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('trigger_source', models.CharField(choices=[('user', 'Usuário (portal/manual)'), ('system', 'Sistema (automático)')], db_index=True, default='user', max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('source_file', models.CharField(blank=True, default='', max_length=1024)),
                ('source_mtime', models.FloatField(blank=True, null=True)),
                ('source_size', models.BigIntegerField(blank=True, null=True)),
                ('run_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'replicacao_d1_sync_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplicacaoD1Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia_d1', models.DateField(db_index=True)),
                ('protocolo', models.CharField(db_index=True, max_length=64)),
                ('workflow_config', models.CharField(db_index=True, max_length=255)),
                ('workflow_d1', models.CharField(blank=True, default='', max_length=255)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('hora', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('canal_destino', models.CharField(blank=True, default='', max_length=64)),
                ('status_brflow', models.CharField(blank=True, default='', max_length=64)),
                ('run', models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, related_name='protocolos', to='replicacao_d1.replicacaod1run', to_field='run_id')),
            ],
            options={
                'db_table': 'replicacao_d1_protocolo',
                'ordering': ['run_id', 'workflow_config', 'protocolo'],
                'indexes': [models.Index(fields=['workflow_config', 'data_referencia_d1'], name='replicacao_d1_prot_wf_data')],
                'constraints': [models.UniqueConstraint(fields=('run', 'protocolo'), name='replicacao_d1_prot_run_prot_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ReplicacaoD1WorkflowDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia_d1', models.DateField(db_index=True)),
                ('workflow_config', models.CharField(max_length=255)),
                ('workflow_d1', models.CharField(blank=True, default='', max_length=255)),
                ('workflow_brflow', models.CharField(blank=True, default='', max_length=255)),
                ('canal_destino', models.CharField(blank=True, default='', max_length=64)),
                ('cliente', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('segmento', models.CharField(blank=True, default='', max_length=128)),
                ('categoria', models.CharField(blank=True, default='', max_length=128)),
                ('fila', models.CharField(blank=True, default='', max_length=64)),
                ('amostra_diaria', models.IntegerField(blank=True, null=True)),
                ('amostra_solicitada', models.IntegerField(blank=True, null=True)),
                ('amostra_efetiva', models.IntegerField(blank=True, null=True)),
                ('protocolos_salvos', models.IntegerField(blank=True, null=True)),
                ('pct_atingido', models.FloatField(blank=True, null=True)),
                ('disponivel_d1', models.IntegerField(blank=True, null=True)),
                ('status_amostra', models.CharField(blank=True, default='', max_length=64)),
                ('status_brflow', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('data_hora_upload_brflow', models.CharField(blank=True, default='', max_length=64)),
                ('faixa_horaria', models.CharField(blank=True, default='', max_length=128)),
                ('run', models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='replicacao_d1.replicacaod1run', to_field='run_id')),
            ],
            options={
                'db_table': 'replicacao_d1_workflow_dia',
                'ordering': ['run_id', 'workflow_config'],
                'indexes': [models.Index(fields=['cliente', 'data_referencia_d1'], name='replicacao_d1_wf_cli_data'), models.Index(fields=['data_referencia_d1', 'status_brflow'], name='replicacao_d1_wf_data_st')],
                'constraints': [models.UniqueConstraint(fields=('run', 'workflow_config'), name='replicacao_d1_wf_run_config_uniq')],
            },
        ),
    ]
