# Generated by Django 5.2.14 on 2026-07-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicacao_d1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicacaod1synclog',
            name='kind',
            field=models.CharField(choices=[('plano', 'Plano (Excel)'), ('replicados', 'Replicados BRFlow')], db_index=True, default='plano', max_length=16),
        ),
        migrations.AddField(
            model_name='replicacaod1synclog',
            name='report_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='ReplicacaoD1Replicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('cliente_destino', models.CharField(blank=True, default='', max_length=255)),
                ('data_cadastro_destino', models.DateTimeField(blank=True, null=True)),
                ('protocolo_destino', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('workflow_destino', models.CharField(blank=True, default='', max_length=255)),
                ('protocolo_origem', models.CharField(db_index=True, max_length=64)),
                ('cliente_origem', models.CharField(blank=True, default='', max_length=255)),
                ('workflow_origem', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('nivel_hierarquico_origem', models.CharField(blank=True, default='', max_length=255)),
                ('data_cadastro_origem', models.DateTimeField(blank=True, null=True)),
                ('tipo_conclusao_analise_origem', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'replicacao_d1_replicado',
                'ordering': ['-report_date', 'protocolo_origem'],
                'indexes': [models.Index(fields=['report_date', 'protocolo_origem'], name='replicacao_d1_rep_data_prot'), models.Index(fields=['report_date', 'workflow_origem'], name='replicacao_d1_rep_data_wf')],
            },
        ),
    ]
