# Generated by Django 5.2.14 on 2026-08-10 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_bot_data_ingestion_and_dashboard_fields'),
        ('replicacao_d1', '0006_amostra_mix_manual_automatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicacaod1protocolo',
            name='erro_resumido',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='replicacaod1protocolo',
            name='ingestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos', to='common.botdataingestion'),
        ),
        migrations.AddField(
            model_name='replicacaod1protocolo',
            name='protocolo_normalizado',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='replicacaod1protocolo',
            name='replicado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replicacaod1protocolo',
            name='status_operacional',
            field=models.CharField(choices=[('planejado', 'Planejado'), ('recebido', 'Recebido'), ('replicado', 'Replicado'), ('pendente', 'Pendente'), ('falhou', 'Falhou'), ('divergente', 'Divergente'), ('ignorado', 'Ignorado')], db_index=True, default='planejado', max_length=16),
        ),
        migrations.AddField(
            model_name='replicacaod1replicado',
            name='ingestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replicados', to='common.botdataingestion'),
        ),
        migrations.AddField(
            model_name='replicacaod1replicado',
            name='protocolo_origem_normalizado',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='replicacaod1synclog',
            name='ingestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='common.botdataingestion'),
        ),
        migrations.AddField(
            model_name='replicacaod1synclog',
            name='rows_loaded',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replicacaod1synclog',
            name='rows_read',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replicacaod1synclog',
            name='rows_rejected',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='replicacaod1protocolo',
            index=models.Index(fields=['data_referencia_d1', 'protocolo_normalizado'], name='replicacao_d1_prot_data_norm'),
        ),
        migrations.AddIndex(
            model_name='replicacaod1protocolo',
            index=models.Index(fields=['data_referencia_d1', 'status_operacional'], name='replicacao_d1_prot_data_st'),
        ),
    ]
