# Generated by Django 5.2.14 on 2026-08-10 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicacao_d1', '0008_remove_run_legacy_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='replicacaod1run',
            name='config_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='replicacaod1run',
            name='config_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='replicacao_d1.replicacaod1configsnapshot'),
        ),
        migrations.AddField(
            model_name='replicacaod1run',
            name='config_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replicacaod1run',
            name='status_canonical',
            field=models.CharField(choices=[('planned', 'Planejado'), ('running', 'Em execução'), ('completed', 'Concluído'), ('partial', 'Parcial'), ('failed', 'Falhou'), ('cancelled', 'Cancelado'), ('legacy_unlinked', 'Legado sem vínculo')], db_index=True, default='legacy_unlinked', max_length=32),
        ),
        migrations.CreateModel(
            name='ReplicacaoD1Reconciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('missing', 'Missing'), ('ambiguous', 'Ambiguous'), ('divergent', 'Divergent'), ('ignored', 'Ignored')], db_index=True, max_length=16)),
                ('method', models.CharField(choices=[('run_id', 'Run ID'), ('exact_date', 'Data exata'), ('date_window', 'Janela de datas'), ('manual', 'Manual')], default='date_window', max_length=32)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('regra_version', models.CharField(default='1', max_length=16)),
                ('reconciliado_em', models.DateTimeField(auto_now=True)),
                ('ajuste_manual_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replicacao_d1_reconciliacoes', to=settings.AUTH_USER_MODEL)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliacoes', to='replicacao_d1.replicacaod1protocolo')),
                ('replicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliacoes', to='replicacao_d1.replicacaod1replicado')),
            ],
            options={
                'db_table': 'replicacao_d1_reconciliacao',
                'ordering': ['-reconciliado_em'],
                'indexes': [models.Index(fields=['status', 'reconciliado_em'], name='replicacao_d1_reconc_st_em')],
                'constraints': [models.UniqueConstraint(fields=('protocolo', 'regra_version'), name='replicacao_d1_reconc_prot_regra_uniq')],
            },
        ),
    ]
