# Generated by Django 5.2.14 on 2026-08-10 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_artifact_reconciliacao_run_status'),
        ('replicacao_d1', '0009_artifact_reconciliacao_run_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicacaod1run',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='replicacaod1run',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replicacaod1run',
            name='erro_codigo',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='replicacaod1run',
            name='erro_resumo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='replicacaod1run',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replicacaod1run',
            name='ingestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='common.botdataingestion'),
        ),
        migrations.AddField(
            model_name='replicacaod1run',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replicacaod1workflowdia',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='replicacaod1workflowdia',
            name='erro_codigo',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='replicacaod1workflowdia',
            name='erro_resumo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='replicacaod1workflowdia',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replicacaod1workflowdia',
            name='ingestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_dia', to='common.botdataingestion'),
        ),
        migrations.AddField(
            model_name='replicacaod1workflowdia',
            name='protocolos_aceitos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replicacaod1workflowdia',
            name='protocolos_enviados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replicacaod1workflowdia',
            name='protocolos_planejados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replicacaod1workflowdia',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replicacaod1workflowdia',
            name='status_operacional',
            field=models.CharField(choices=[('planejado', 'Planejado'), ('recebido', 'Recebido'), ('replicado', 'Replicado'), ('pendente', 'Pendente'), ('falhou', 'Falhou'), ('divergente', 'Divergente'), ('ignorado', 'Ignorado')], db_index=True, default='planejado', max_length=16),
        ),
        migrations.AddField(
            model_name='replicacaod1workflowdia',
            name='upload_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
