# Generated by Django 5.2.7 on 2026-08-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replicacao_d1", "0011_database_only_plan_validation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplicacaoD1PlanDeletion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.CharField(db_index=True, max_length=64)),
                ("data_referencia_d1", models.DateField(db_index=True)),
                ("status_canonical", models.CharField(max_length=32)),
                ("validation_status", models.CharField(max_length=16)),
                ("plan_hash", models.CharField(max_length=64)),
                ("plan_revision", models.PositiveIntegerField()),
                ("config_hash", models.CharField(blank=True, default="", max_length=64)),
                ("protocolos_total", models.PositiveIntegerField(default=0)),
                ("workflows_total", models.PositiveIntegerField(default=0)),
                ("deletion_reason", models.CharField(max_length=500)),
                ("audit_snapshot", models.JSONField(blank=True, default=dict)),
                ("deleted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="replicacao_d1_plan_deletions", to=settings.AUTH_USER_MODEL)),
                ("source_batch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="plan_deletions", to="replicacao_d1.replicacaod1fontelote")),
            ],
            options={
                "db_table": "replicacao_d1_plan_deletion",
                "ordering": ["-deleted_at", "-id"],
            },
        ),
    ]
