# Generated by Django 5.2.14 on 2026-08-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replicacao_d1', '0018_revert_retroativo_singleton_pk_db'),
        ('replicacao_d1', '0019_destinos_replicacao_ativos'),
    ]

    operations = [
    ]
