# Generated by Django 5.2.15 on 2026-07-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apirequestmetric',
            new_name='ops_api_req_route_719e41_idx',
            old_name='ops_api_req_route_idx',
        ),
        migrations.RenameIndex(
            model_name='apirequestmetric',
            new_name='ops_api_req_status__716feb_idx',
            old_name='ops_api_req_status_idx',
        ),
    ]
