# Generated by Django 5.2.15 on 2026-07-13 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0002_seed_role_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalRoutePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('path', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('section', models.CharField(blank=True, default='', max_length=64)),
                ('permissions_any', models.JSONField(blank=True, default=list)),
                ('permissions_all', models.JSONField(blank=True, default=list)),
                ('requires_auth', models.BooleanField(default=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_policy_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Política de rota RBAC',
                'verbose_name_plural': 'Políticas de rotas RBAC',
                'ordering': ['section', 'path'],
            },
        ),
    ]
