# Generated by Django 5.2.15 on 2026-07-13 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_portal_route_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalRoleDefinition',
            fields=[
                ('role', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('default_scope', models.CharField(default='global', max_length=16)),
                ('is_editable', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_definition_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Definição de perfil RBAC',
                'verbose_name_plural': 'Definições de perfis RBAC',
                'ordering': ['role'],
            },
        ),
    ]
