# Generated by Django 5.1.15 on 2026-08-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0009_portalroutepolicy_is_active'),
        ('access', '0012_merge_replicacao_d1_quality_menu'),
    ]

    operations = [
    ]
