# Generated by Django 5.2.15 on 2026-08-18 20:59

from django.db import migrations, models


def ensure_is_active_column(apps, schema_editor):
    """Add is_active only if missing (0009/0010 antigos podem já tê-lo)."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM information_schema.columns "
            "WHERE table_schema = 'public' AND table_name = 'access_portalroutepolicy' "
            "AND column_name = 'is_active'"
        )
        if cursor.fetchone():
            return

    PortalRoutePolicy = apps.get_model("access", "PortalRoutePolicy")
    field = models.BooleanField(default=True)
    field.set_attributes_from_name("is_active")
    schema_editor.add_field(PortalRoutePolicy, field)


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0014_quality_failure_change_permission"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_is_active_column, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="portalroutepolicy",
                    name="is_active",
                    field=models.BooleanField(default=True),
                ),
            ],
        ),
    ]
