# Generated by Django 5.2.14 on 2026-06-19 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workforce', '0007_rename_agent_active_idx_agent_active_c8098c_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorEventoSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('trigger_source', models.CharField(choices=[('user', 'Usuário (portal/manual)'), ('system', 'Sistema (automático)')], db_index=True, default='user', max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('source_file', models.CharField(blank=True, default='', max_length=500)),
                ('source_mtime', models.FloatField(blank=True, null=True)),
                ('source_size', models.BigIntegerField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitor_evento_sync_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitorEventoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_usuario', models.CharField(db_index=True, max_length=64)),
                ('data_evento', models.DateTimeField(db_index=True)),
                ('evento', models.CharField(db_index=True, max_length=255)),
                ('id_sessao', models.CharField(blank=True, default='', max_length=255)),
                ('objeto', models.TextField(blank=True, default='')),
                ('data_segundo_evento', models.DateTimeField(blank=True, null=True)),
                ('segundo_evento', models.CharField(blank=True, default='', max_length=255)),
                ('agent_name', models.CharField(blank=True, default='', max_length=255)),
                ('team', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('journey_shift', models.CharField(blank=True, default='', max_length=64)),
                ('leader_name', models.CharField(blank=True, default='', max_length=255)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_evento_records', to='workforce.agent')),
            ],
            options={
                'db_table': 'monitor_evento_record',
                'ordering': ['-data_evento', 'matricula_usuario'],
                'indexes': [models.Index(fields=['evento', '-data_evento'], name='monitor_eve_evento_ce25e6_idx'), models.Index(fields=['team', '-data_evento'], name='monitor_eve_team_8e4a00_idx')],
            },
        ),
    ]
