# Generated by Django 5.2.15 on 2026-06-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_eventos', '0002_align_tratado_schema'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monitoreventorecord',
            new_name='monitor_eve_data_bf03f0_idx',
            old_name='monitor_eve_data_hora_idx',
        ),
    ]
