# Generated by Django 5.1.15 on 2026-08-19 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brb_report', '0002_brbcsdatasource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSupplementImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('rows_na_demanda', models.PositiveIntegerField(default=0)),
                ('rows_na_falha', models.PositiveIntegerField(default=0)),
                ('rows_treinamento', models.PositiveIntegerField(default=0)),
                ('rows_treinamento_horas', models.PositiveIntegerField(default=0)),
                ('upserted', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('completed', 'Concluído'), ('failed', 'Falhou')], default='completed', max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_supplement_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import suplemento report',
                'verbose_name_plural': 'Imports suplemento report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportNaFalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(db_index=True)),
                ('protocolo', models.CharField(blank=True, default='', max_length=100)),
                ('protocolo_norm', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('matricula', models.CharField(blank=True, default='', max_length=64)),
                ('matricula_norm', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('data_cadastro', models.DateField(blank=True, db_index=True, null=True)),
                ('data_notificacao', models.DateField(blank=True, db_index=True, null=True)),
                ('motivo_falha', models.TextField(blank=True, default='')),
                ('resultado_cliente', models.CharField(blank=True, default='', max_length=256)),
                ('resultado_auditoria', models.CharField(blank=True, default='', max_length=256)),
                ('demanda', models.CharField(blank=True, default='', max_length=512)),
                ('cliente_label', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='na_falhas', to='brb_report.reportsupplementimportbatch')),
            ],
            options={
                'db_table': 'report_na_falha',
                'indexes': [models.Index(fields=['id_cliente', 'data_notificacao'], name='report_na_fal_cli_not')],
                'constraints': [models.UniqueConstraint(fields=('id_cliente', 'protocolo_norm', 'matricula_norm'), name='report_na_fal_cli_prot_mat')],
            },
        ),
        migrations.CreateModel(
            name='ReportNaDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(db_index=True)),
                ('demanda', models.CharField(blank=True, default='', max_length=512)),
                ('data_abertura', models.DateField(blank=True, db_index=True, null=True)),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('mes', models.CharField(blank=True, default='', max_length=32)),
                ('quantidade_protocolos', models.IntegerField(default=0)),
                ('falhas_manuais', models.IntegerField(default=0)),
                ('falhas_processuais', models.IntegerField(default=0)),
                ('falhas_automaticas', models.IntegerField(default=0)),
                ('situacao', models.CharField(blank=True, default='', max_length=128)),
                ('cliente_label', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='na_demandas', to='brb_report.reportsupplementimportbatch')),
            ],
            options={
                'db_table': 'report_na_demanda',
                'indexes': [models.Index(fields=['id_cliente', 'data_abertura'], name='report_na_dem_cli_dt')],
                'constraints': [models.UniqueConstraint(fields=('id_cliente', 'demanda', 'data_abertura'), name='report_na_dem_cli_dem_ab')],
            },
        ),
        migrations.CreateModel(
            name='ReportTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(db_index=True)),
                ('event_title', models.CharField(blank=True, default='', max_length=512)),
                ('matricula', models.CharField(blank=True, default='', max_length=64)),
                ('matricula_norm', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('assignment_date', models.DateField(blank=True, null=True)),
                ('signature_date', models.DateField(blank=True, null=True)),
                ('session_start', models.DateField(blank=True, db_index=True, null=True)),
                ('session_final', models.DateField(blank=True, null=True)),
                ('horas', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=128)),
                ('cliente_label', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treinamentos', to='brb_report.reportsupplementimportbatch')),
            ],
            options={
                'db_table': 'report_treinamento',
                'indexes': [models.Index(fields=['id_cliente', 'session_start'], name='report_tr_cli_start')],
                'constraints': [models.UniqueConstraint(fields=('id_cliente', 'matricula_norm', 'event_title', 'session_start'), name='report_tr_cli_mat_evt_dt')],
            },
        ),
    ]
