# Generated by Django 5.2.15 on 2026-08-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brb_report', '0003_report_supplement_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttreinamento',
            name='scope',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
