# Generated by Django 5.1.15 on 2026-06-16 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FalhasAgent',
            fields=[
                ('matricula_norm', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('admissao_date', models.DateField(blank=True, null=True)),
                ('tempo_casa', models.CharField(blank=True, default='', max_length=100)),
                ('tempo_etapa', models.CharField(blank=True, default='', max_length=100)),
                ('atividade_atual', models.CharField(blank=True, default='', max_length=255)),
                ('turno_atual', models.CharField(blank=True, default='', max_length=100)),
                ('localidade', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('leader_nome', models.CharField(blank=True, default='', max_length=255)),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'agente (falhas)',
                'verbose_name_plural': 'agentes (falhas)',
                'db_table': 'falhas_agent',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=500)),
                ('tipo_acao', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_acao_prefixo', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('situacao', models.CharField(blank=True, default='', max_length=100)),
                ('situacao_calculada', models.CharField(blank=True, default='', max_length=100)),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('data_atribuicao', models.DateField(blank=True, null=True)),
                ('data_assinatura', models.DateField(blank=True, null=True)),
                ('data_inicio_sessao', models.DateField(blank=True, null=True)),
                ('data_fim_sessao', models.DateField(blank=True, null=True)),
                ('localidade', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('matricula', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('nome_agente', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'falhas_training',
            },
        ),
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=100)),
                ('data_analise', models.DateField(db_index=True)),
                ('data_auditoria', models.DateField(blank=True, null=True)),
                ('etapa', models.CharField(blank=True, default='', max_length=255)),
                ('categoria', models.CharField(blank=True, default='', max_length=255)),
                ('cenario', models.TextField(blank=True, default='')),
                ('novo_cenario', models.TextField(blank=True, default='')),
                ('localidade', models.CharField(db_index=True, max_length=100)),
                ('cliente', models.CharField(blank=True, default='', max_length=255)),
                ('workflow', models.CharField(blank=True, default='', max_length=255)),
                ('dificuldade', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_documento', models.CharField(blank=True, default='', max_length=255)),
                ('uf_documento', models.CharField(blank=True, default='', max_length=50)),
                ('tipo_falha', models.CharField(default='OUTROS', max_length=50)),
                ('modulo', models.CharField(blank=True, default='', max_length=255)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failures', to='falhas_criticas.falhasagent')),
            ],
            options={
                'db_table': 'falhas_failure',
            },
        ),
        migrations.CreateModel(
            name='Contestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(blank=True, default='', max_length=100)),
                ('data', models.DateField(blank=True, null=True)),
                ('fonte', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('localidade', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestations', to='falhas_criticas.falhasagent')),
            ],
            options={
                'db_table': 'falhas_contestation',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(blank=True, default='', max_length=100)),
                ('data', models.DateField(blank=True, db_index=True, null=True)),
                ('cliente', models.CharField(blank=True, default='', max_length=255)),
                ('workflow', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_solicitacao', models.CharField(blank=True, default='', max_length=255)),
                ('conformidade', models.CharField(blank=True, default='', max_length=100)),
                ('conformidade_regra', models.CharField(blank=True, default='', max_length=100)),
                ('dificuldade', models.CharField(blank=True, default='', max_length=100)),
                ('critico', models.CharField(blank=True, default='', max_length=100)),
                ('uf_emissao', models.CharField(blank=True, default='', max_length=50)),
                ('localidade', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('agente_nome_planilha', models.CharField(blank=True, default='', max_length=255)),
                ('duvida', models.TextField(blank=True, default='')),
                ('conclusao', models.TextField(blank=True, default='')),
                ('lider_solicitante', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_documento', models.CharField(blank=True, default='', max_length=255)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supports', to='falhas_criticas.falhasagent')),
            ],
            options={
                'db_table': 'falhas_support',
            },
        ),
        migrations.CreateModel(
            name='SyncAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('trigger_source', models.CharField(choices=[('user', 'Usuário (portal/manual)'), ('system', 'Sistema (automático)')], db_index=True, default='user', max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'falhas_sync_audit_log',
                'ordering': ['-started_at'],
            },
        ),
    ]
