# Generated by Django 5.2.15 on 2026-06-17 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falhas_criticas', '0002_executivereportarchive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('in_progress', 'Em andamento'), ('resolved', 'Resolvido'), ('closed', 'Fechado')], db_index=True, default='open', max_length=32)),
                ('localidade', models.CharField(blank=True, default='', max_length=100)),
                ('module', models.CharField(blank=True, default='', max_length=64)),
                ('jira_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('jira_status_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='falhas_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'falhas_portal_ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalTicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='falhas_ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='falhas_criticas.portalticket')),
            ],
            options={
                'db_table': 'falhas_portal_ticket_comment',
                'ordering': ['created_at'],
            },
        ),
    ]
