# Generated by Django 5.2.15 on 2026-07-23 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaUtilSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Em execução'), ('ok', 'OK'), ('error', 'Erro')], default='running', max_length=16)),
                ('cutover_at', models.DateTimeField(help_text='Instante de corte para protocolos abertos')),
                ('rows_detalhe', models.PositiveIntegerField(default=0)),
                ('rows_consolidado', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_util_sync_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sla_util_sync_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SlaUtilDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(db_index=True, max_length=64)),
                ('id_cliente', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('id_workflow', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('id_nh', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('cliente_nome', models.CharField(blank=True, default='', max_length=255)),
                ('workflow_nome', models.CharField(blank=True, default='', max_length=255)),
                ('nh_nome', models.CharField(blank=True, default='', max_length=255)),
                ('data_cadastro', models.DateField(db_index=True)),
                ('hora_cadastro', models.TimeField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, db_index=True, null=True)),
                ('hora_conclusao', models.TimeField(blank=True, null=True)),
                ('em_aberto', models.BooleanField(db_index=True, default=False)),
                ('resultado', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_conclusao', models.CharField(blank=True, default='', max_length=255)),
                ('avaliacao', models.CharField(blank=True, default='', max_length=64)),
                ('date_key_cadastro', models.PositiveIntegerField(db_index=True)),
                ('date_key_conclusao', models.PositiveIntegerField(blank=True, null=True)),
                ('key_cwn', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('chave_nh', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('sla_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('data_vencimento_d2u', models.DateField(blank=True, null=True)),
                ('sla_descricao_natural', models.CharField(blank=True, default='', max_length=16)),
                ('sla_descricao_ajustado', models.CharField(blank=True, default='', max_length=16)),
                ('faixa', models.CharField(blank=True, default='', max_length=64)),
                ('problemas', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalhes', to='monitoramento_sla.slautilsyncrun')),
            ],
            options={
                'db_table': 'sla_util_detalhe',
                'ordering': ['-data_cadastro', 'protocolo'],
                'indexes': [models.Index(fields=['data_cadastro', 'id_cliente', 'id_workflow'], name='sla_util_de_data_ca_a1f0e1_idx'), models.Index(fields=['sla_descricao_natural'], name='sla_util_de_sla_des_262977_idx'), models.Index(fields=['sla_descricao_ajustado'], name='sla_util_de_sla_des_0bdf64_idx'), models.Index(fields=['em_aberto', '-data_cadastro'], name='sla_util_de_em_aber_1df385_idx')],
                'constraints': [models.UniqueConstraint(fields=('protocolo', 'id_workflow', 'id_nh'), name='uniq_sla_util_detalhe_prot_wf_nh')],
            },
        ),
        migrations.CreateModel(
            name='SlaUtilConsolidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField(db_index=True)),
                ('hora_cadastro', models.TimeField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('hora_conclusao', models.TimeField(blank=True, null=True)),
                ('id_cliente', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('id_workflow', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('id_nh', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('cliente_nome', models.CharField(blank=True, default='', max_length=255)),
                ('workflow_nome', models.CharField(blank=True, default='', max_length=255)),
                ('nh_nome', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_conclusao', models.CharField(blank=True, default='', max_length=255)),
                ('resultado', models.CharField(blank=True, default='', max_length=255)),
                ('sla_descricao_natural', models.CharField(blank=True, default='', max_length=16)),
                ('sla_descricao_ajustado', models.CharField(blank=True, default='', max_length=16)),
                ('faixa', models.CharField(blank=True, default='', max_length=64)),
                ('avaliacao', models.CharField(blank=True, default='', max_length=64)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('date_key_cadastro', models.PositiveIntegerField(db_index=True)),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidados', to='monitoramento_sla.slautilsyncrun')),
            ],
            options={
                'db_table': 'sla_util_consolidado',
                'ordering': ['-data_cadastro'],
                'indexes': [models.Index(fields=['data_cadastro', 'id_cliente', 'id_workflow'], name='sla_util_co_data_ca_3d9820_idx')],
            },
        ),
    ]
