# Generated by Django 5.2.14 on 2026-07-17 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotDbSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('produtividade', 'Produtividade'), ('monitor_eventos', 'Monitor eventos'), ('rotina_bruto', 'Rotina bruto'), ('falhas_criticas', 'Falhas críticas')], db_index=True, max_length=32)),
                ('report_type', models.CharField(blank=True, default='', max_length=64)),
                ('source_path', models.CharField(blank=True, default='', max_length=1024)),
                ('force', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em execução'), ('done', 'Concluído'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], db_index=True, default='pending', max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'common_bot_db_sync_job',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='bot_db_sync_status_created'), models.Index(fields=['domain', 'report_type', 'source_path', 'status'], name='bot_db_sync_dedupe')],
            },
        ),
    ]
