# Generated by Django 5.2.14 on 2026-07-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_bot_db_sync_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botdbsyncjob',
            name='domain',
            field=models.CharField(choices=[('produtividade', 'Produtividade'), ('monitor_eventos', 'Monitor eventos'), ('rotina_bruto', 'Rotina bruto'), ('falhas_criticas', 'Falhas críticas'), ('replicacao_d1', 'Replicação D-1')], db_index=True, max_length=32),
        ),
    ]
