# Generated by Django 5.2.14 on 2026-08-10 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_botdbsyncjob_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotDataIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('domain', models.CharField(db_index=True, max_length=32)),
                ('kind', models.CharField(db_index=True, max_length=32)),
                ('reference_date', models.DateField(blank=True, db_index=True, null=True)),
                ('run_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source_file', models.CharField(blank=True, default='', max_length=1024)),
                ('source_mtime', models.FloatField(blank=True, null=True)),
                ('source_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Recebido'), ('processing', 'Processando'), ('completed', 'Concluído'), ('partial', 'Parcial'), ('failed', 'Falhou')], db_index=True, default='received', max_length=16)),
                ('rows_read', models.PositiveIntegerField(default=0)),
                ('rows_loaded', models.PositiveIntegerField(default=0)),
                ('rows_rejected', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('sync_log_id', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('sync_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestions', to='common.botdbsyncjob')),
            ],
            options={
                'db_table': 'common_bot_data_ingestion',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['domain', 'kind', 'reference_date'], name='bot_ingest_domain_kind_date')],
            },
        ),
    ]
