# Generated by Django 5.2.14 on 2026-08-10 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_bot_data_ingestion_and_dashboard_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='botdataingestion',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='botdataingestion',
            name='parser_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='BotDataArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=32)),
                ('kind', models.CharField(db_index=True, max_length=32)),
                ('semantic_key', models.CharField(db_index=True, max_length=128)),
                ('safe_name', models.CharField(max_length=255)),
                ('content_sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('content_size', models.BigIntegerField(blank=True, null=True)),
                ('reference_date', models.DateField(blank=True, db_index=True, null=True)),
                ('legacy_unverified', models.BooleanField(default=False)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'common_bot_data_artifact',
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['domain', 'kind', 'semantic_key'], name='bot_artifact_domain_kind_key')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('content_sha256__gt', '')), fields=('domain', 'kind', 'content_sha256'), name='bot_artifact_domain_kind_hash_uniq')],
            },
        ),
        migrations.AddField(
            model_name='botdataingestion',
            name='artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestions', to='common.botdataartifact'),
        ),
    ]
