# Generated by Django 5.2 on 2026-08-10
from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0009_artifact_reconciliacao_run_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botdataingestion",
            name="source_key",
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name="botdataingestion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("artifact__isnull", False)),
                fields=("artifact", "attempt_number"),
                name="bot_ingest_artifact_attempt_uniq",
            ),
        ),
    ]
