# Generated by Django 5.2.15 on 2026-06-17 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workforce', '0007_rename_agent_active_idx_agent_active_c8098c_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductivitySyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('trigger_source', models.CharField(choices=[('user', 'Usuário (portal/manual)'), ('system', 'Sistema (automático)')], db_index=True, default='user', max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('source_file', models.CharField(blank=True, default='', max_length=500)),
                ('source_mtime', models.FloatField(blank=True, null=True)),
                ('source_size', models.BigIntegerField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'produtividade_sync_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_norm', models.CharField(db_index=True, max_length=64)),
                ('etapa', models.CharField(db_index=True, max_length=255)),
                ('analysis_seconds', models.PositiveIntegerField(default=0)),
                ('stage_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('agent_name', models.CharField(blank=True, default='', max_length=255)),
                ('team', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('journey_shift', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('leader_name', models.CharField(blank=True, default='', max_length=255)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productivity_records', to='workforce.agent')),
            ],
            options={
                'db_table': 'produtividade_record',
                'ordering': ['-recorded_at', 'matricula_norm'],
                'indexes': [models.Index(fields=['etapa', '-recorded_at'], name='produtivida_etapa_1878a1_idx'), models.Index(fields=['team', '-recorded_at'], name='produtivida_team_7a2fa1_idx')],
            },
        ),
    ]
