# Generated by Django 5.2.15 on 2026-06-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivityrecord',
            name='analysis_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
