# Generated by Django 5.2.15 on 2026-07-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0002_productivityrecord_analysis_count'),
        ('workforce', '0008_agent_jira_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivityrecord',
            name='source',
            field=models.CharField(choices=[('brflow', 'BRFlow HxH'), ('case', 'Case Manager')], db_index=True, default='brflow', max_length=16),
        ),
        migrations.AddIndex(
            model_name='productivityrecord',
            index=models.Index(fields=['source', 'etapa', '-recorded_at'], name='produtivida_source_045905_idx'),
        ),
    ]
