# Generated by Django 5.1.15 on 2026-08-08 01:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalNotificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=160, unique=True)),
                ('section', models.CharField(db_index=True, max_length=80)),
                ('functionality', models.CharField(max_length=255)),
                ('route', models.CharField(blank=True, default='', max_length=500)),
                ('event_label', models.CharField(max_length=255)),
                ('trigger_description', models.TextField(blank=True, default='')),
                ('primary_recipient_rule', models.TextField(blank=True, default='')),
                ('escalation_recipient_rule', models.TextField(blank=True, default='')),
                ('channel', models.CharField(blank=True, default='Portal', max_length=120)),
                ('priority', models.CharField(choices=[('info', 'Informativa'), ('warning', 'Atenção'), ('critical', 'Crítica')], db_index=True, default='info', max_length=16)),
                ('action_description', models.TextField(blank=True, default='')),
                ('current_coverage', models.TextField(blank=True, default='')),
                ('recommendation', models.CharField(choices=[('required', 'Obrigatória'), ('recommended', 'Recomendada'), ('optional', 'Opcional'), ('policy_required', 'Dependente de regra'), ('keep', 'Manter')], db_index=True, default='recommended', max_length=32)),
                ('frequency_rule', models.TextField(blank=True, default='')),
                ('decision', models.CharField(choices=[('pending', 'A definir'), ('approved', 'Aprovar'), ('adjust', 'Ajustar'), ('discarded', 'Descartar')], db_index=True, default='pending', max_length=16)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('catalog_managed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_notification_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_notification_rule',
                'ordering': ['section', 'functionality', 'event_label'],
                'indexes': [models.Index(fields=['section', 'enabled', 'priority'], name='portal_notif_rule_filter_idx')],
            },
        ),
    ]
