# -*- coding: utf-8 -*-
from django.urls import path

from apps.replicacao_d1.views.api import (
    DashboardAgentesExportView,
    DashboardAgentesView,
    DashboardExportView,
    DashboardProjectionExportView,
    DashboardProjectionPdfExportView,
    DashboardProjectionView,
    DashboardView,
    ProtocoloDetailView,
    ProtocolosListView,
    ReplicadosListView,
    RunDetailView,
    RunsListView,
    SyncView,
    WorkflowsListView,
)
from apps.replicacao_d1.views.config_api import (
    CategoriaDetailView,
    CategoriaListCreateView,
    ClienteDetailView,
    ClienteListCreateView,
    ConfigCalculadoraView,
    ConfigExportCsvView,
    ConfigGeralView,
    ConfigProjecaoMensalView,
    ConfigResumoView,
    ConfigRetroativoView,
    EscalaDetailView,
    EscalaListCreateView,
    FonteAtivarView,
    FonteDesativarView,
    HistoricoListView,
    ImportApplyView,
    ImportPreviewView,
    LedgerAjusteView,
    LedgerListView,
    LedgerPurgeRunsView,
    MetaMensalDetailView,
    MetaMensalListCreateView,
    SegmentoDetailView,
    SegmentoListCreateView,
    SnapshotPreviewView,
    WorkflowBulkStatusView,
    WorkflowColumnFilterOptionsView,
    WorkflowDetailView,
    WorkflowDuplicateView,
    WorkflowListCreateView,
)
from apps.replicacao_d1.views.plan_validation_api import (
    PlanApproveView,
    PlanDeleteView,
    PlanExportCsvView,
    PlanListView,
    PlanProtocolListView,
    PlanRejectView,
    PlanValidationDetailView,
)

urlpatterns = [
    path("dashboard/", DashboardView.as_view(), name="replicacao-d1-dashboard"),
    path("dashboard/export.csv", DashboardExportView.as_view(), name="replicacao-d1-dashboard-export"),
    path("dashboard/projection/", DashboardProjectionView.as_view(), name="replicacao-d1-dashboard-projection"),
    path("dashboard/projection/export.csv", DashboardProjectionExportView.as_view(), name="replicacao-d1-dashboard-projection-export"),
    path("dashboard/projection/export.pdf", DashboardProjectionPdfExportView.as_view(), name="replicacao-d1-dashboard-projection-pdf-export"),
    path("dashboard/agentes/", DashboardAgentesView.as_view(), name="replicacao-d1-dashboard-agentes"),
    path("dashboard/agentes/export.csv", DashboardAgentesExportView.as_view(), name="replicacao-d1-dashboard-agentes-export"),
    path(
        "runs/<str:run_id>/protocolos/<str:protocolo>/",
        ProtocoloDetailView.as_view(),
        name="replicacao-d1-protocolo-detail",
    ),
    path("runs/", RunsListView.as_view(), name="replicacao-d1-runs"),
    path("runs/<str:run_id>/", RunDetailView.as_view(), name="replicacao-d1-run-detail"),
    path("workflows/", WorkflowsListView.as_view(), name="replicacao-d1-workflows"),
    path("protocolos/", ProtocolosListView.as_view(), name="replicacao-d1-protocolos"),
    path("replicados/", ReplicadosListView.as_view(), name="replicacao-d1-replicados"),
    path("sync/", SyncView.as_view(), name="replicacao-d1-sync"),
    # Config D-1 (PostgreSQL)
    path("config/geral/", ConfigGeralView.as_view(), name="replicacao-d1-config-geral"),
    path("config/calculadora/", ConfigCalculadoraView.as_view(), name="replicacao-d1-config-calculadora"),
    path("config/retroativo/", ConfigRetroativoView.as_view(), name="replicacao-d1-config-retroativo"),
    path("config/resumo/", ConfigResumoView.as_view(), name="replicacao-d1-config-resumo"),
    path("config/projecao/", ConfigProjecaoMensalView.as_view(), name="replicacao-d1-config-projecao"),
    path("config/export/<str:resource>/", ConfigExportCsvView.as_view(), name="replicacao-d1-config-export"),
    path("config/segmentos/", SegmentoListCreateView.as_view(), name="replicacao-d1-config-segmentos"),
    path("config/segmentos/<int:pk>/", SegmentoDetailView.as_view(), name="replicacao-d1-config-segmento-detail"),
    path("config/categorias/", CategoriaListCreateView.as_view(), name="replicacao-d1-config-categorias"),
    path("config/categorias/<int:pk>/", CategoriaDetailView.as_view(), name="replicacao-d1-config-categoria-detail"),
    path("config/clientes/", ClienteListCreateView.as_view(), name="replicacao-d1-config-clientes"),
    path("config/clientes/<int:pk>/", ClienteDetailView.as_view(), name="replicacao-d1-config-cliente-detail"),
    path("config/workflows/column-filter-options/", WorkflowColumnFilterOptionsView.as_view(), name="replicacao-d1-config-workflows-column-filter-options"),
    path("config/workflows/", WorkflowListCreateView.as_view(), name="replicacao-d1-config-workflows"),
    path("config/workflows/bulk-status/", WorkflowBulkStatusView.as_view(), name="replicacao-d1-config-workflows-bulk-status"),
    path("config/workflows/<int:pk>/duplicate/", WorkflowDuplicateView.as_view(), name="replicacao-d1-config-workflow-duplicate"),
    path("config/workflows/<int:pk>/", WorkflowDetailView.as_view(), name="replicacao-d1-config-workflow-detail"),
    path("config/escala/", EscalaListCreateView.as_view(), name="replicacao-d1-config-escala"),
    path("config/escala/<int:pk>/", EscalaDetailView.as_view(), name="replicacao-d1-config-escala-detail"),
    path("config/metas/", MetaMensalListCreateView.as_view(), name="replicacao-d1-config-metas"),
    path("config/metas/<int:pk>/", MetaMensalDetailView.as_view(), name="replicacao-d1-config-meta-detail"),
    path("config/ledger/", LedgerListView.as_view(), name="replicacao-d1-config-ledger"),
    path("config/ledger/ajuste/", LedgerAjusteView.as_view(), name="replicacao-d1-config-ledger-ajuste"),
    path("config/ledger/purge-runs/", LedgerPurgeRunsView.as_view(), name="replicacao-d1-config-ledger-purge-runs"),
    path("config/historico/", HistoricoListView.as_view(), name="replicacao-d1-config-historico"),
    path("config/import/preview/", ImportPreviewView.as_view(), name="replicacao-d1-config-import-preview"),
    path("config/import/apply/", ImportApplyView.as_view(), name="replicacao-d1-config-import-apply"),
    path("config/fonte/ativar/", FonteAtivarView.as_view(), name="replicacao-d1-config-fonte-ativar"),
    path("config/fonte/desativar/", FonteDesativarView.as_view(), name="replicacao-d1-config-fonte-desativar"),
    path("config/snapshot/preview/", SnapshotPreviewView.as_view(), name="replicacao-d1-config-snapshot-preview"),
    path("config/plans/", PlanListView.as_view(), name="replicacao-d1-plan-list"),
    path("config/plans/<str:run_id>/validation/", PlanValidationDetailView.as_view(), name="replicacao-d1-plan-validation"),
    path("config/plans/<str:run_id>/protocolos/", PlanProtocolListView.as_view(), name="replicacao-d1-plan-protocols"),
    path("config/plans/<str:run_id>/approve/", PlanApproveView.as_view(), name="replicacao-d1-plan-approve"),
    path("config/plans/<str:run_id>/reject/", PlanRejectView.as_view(), name="replicacao-d1-plan-reject"),
    path("config/plans/<str:run_id>/delete/", PlanDeleteView.as_view(), name="replicacao-d1-plan-delete"),
    path("config/plans/<str:run_id>/export.csv", PlanExportCsvView.as_view(), name="replicacao-d1-plan-export"),
]
