"""Catálogo canônico de rotas do frontend (espelho do Vue Router)."""

from __future__ import annotations

from dataclasses import dataclass

from apps.access import registry as R

# Grupos OR usados no router (espelho do frontend)
_PORTAL_OPS = (R.ADM_CONSOLE_OPS, R.PLANEJAMENTO_CONSOLE_OPS_VIEW)
_CONFIG_HUB = (
    R.ADM_CONFIG_HUB,
    R.ADM_CATALOGOS,
    R.ADM_QUALIDADE_REGISTROS_VIEW,
    R.ADM_QUALIDADE_REGISTROS_MANAGE,
)
_CONTROLE_JORNADA_LAYOUT = (
    R.OPERACAO_JORNADA_PAINEL_VIEW,
    R.OPERACAO_JORNADA_ESCALA_VIEW,
    R.OPERACAO_HISTORICO_VIEW,
    R.OPERACAO_STATUS_VIEW,
)

SYSTEM_ROUTE_NAMES: frozenset[str] = frozenset(
    {
        "login",
        "home",
        "change-password",
        "access-denied",
    }
)


@dataclass(frozen=True)
class PortalRouteDefinition:
    route_name: str
    path: str
    label: str
    section: str
    permissions_any: tuple[str, ...] = ()
    permissions_all: tuple[str, ...] = ()
    requires_auth: bool = True
    is_editable: bool = True


PORTAL_ROUTE_DEFINITIONS: tuple[PortalRouteDefinition, ...] = (
    PortalRouteDefinition(
        route_name="login",
        path="/",
        label="Login",
        section="auth",
        requires_auth=False,
        is_editable=False,
    ),
    PortalRouteDefinition(
        route_name="change-password",
        path="/alterar-senha",
        label="Alterar senha",
        section="auth",
        is_editable=False,
    ),
    PortalRouteDefinition(
        route_name="home",
        path="/home",
        label="Home",
        section="home",
        is_editable=False,
    ),
    PortalRouteDefinition(
        route_name="access-denied",
        path="/acesso-negado",
        label="Acesso negado",
        section="auth",
        is_editable=False,
    ),
    PortalRouteDefinition(
        route_name="all-news",
        path="/noticias",
        label="Todas as notícias",
        section="home",
        permissions_any=(R.COMUNICACAO_NOTICIAS_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="falhas-criticas",
        path="/secao/indicadores/falhas/:module?",
        label="Falhas críticas",
        section="qualidade",
        permissions_any=(R.QUAL_FALHAS_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="indicadores-qualidade",
        path="/secao/indicadores/qualidade/:module?",
        label="Qualidade",
        section="indicadores",
        permissions_any=(R.QUAL_OPERACIONAL_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-auditoria-dashboard",
        path="/secao/qualidade/auditoria/fraud/dashboard",
        label="Auditoria Fraud — dashboard",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-auditoria-cadastro",
        path="/secao/qualidade/auditoria/fraud/cadastro",
        label="Auditoria Fraud — cadastro",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_CREATE,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-auditoria-consulta",
        path="/secao/qualidade/auditoria/fraud/consulta",
        label="Auditoria Fraud — consulta",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-auditoria-atividade-detalhe",
        path="/secao/qualidade/auditoria/fraud/atividades/:atividadeId",
        label="Auditoria Fraud — detalhe da atividade",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-auditoria-protocolo-analise",
        path="/secao/qualidade/auditoria/fraud/atividades/:atividadeId/protocolos/:protocoloId",
        label="Auditoria Fraud — análise do protocolo",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_CREATE,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-fraud-contestacao-interna",
        path="/secao/qualidade/contestacao/fraud/interna",
        label="Contestação Fraud — interna",
        section="qualidade",
        permissions_any=(R.QUAL_CONTESTACAO_INTERNA_FRAUD_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-contestacao-dashboard",
        path="/secao/qualidade/contestacao/fraud/externa/dashboard",
        label="Contestação Fraud — dashboard",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-contestacao-cadastro",
        path="/secao/qualidade/contestacao/fraud/externa/cadastro",
        label="Contestação — cadastro",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_CREATE,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-contestacao-consulta",
        path="/secao/qualidade/contestacao/fraud/externa/consulta",
        label="Contestação — consulta",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-contestacao-atividade-detalhe",
        path="/secao/qualidade/contestacao/fraud/externa/atividades/:atividadeId",
        label="Contestação — detalhe da atividade",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-contestacao-protocolo-analise",
        path="/secao/qualidade/contestacao/fraud/externa/atividades/:atividadeId/protocolos/:protocoloId",
        label="Contestação — análise de protocolo",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_CREATE,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-contestacao-remocao-base-negativa",
        path="/secao/qualidade/contestacao/fraud/externa/remocao-base-negativa",
        label="Contestação — remoção base negativa",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-contestacao-remocao-base-positiva",
        path="/secao/qualidade/contestacao/fraud/externa/remocao-base-positiva",
        label="Contestação — remoção base positiva",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-contestacao-solicitacoes-idas-bio",
        path="/secao/qualidade/contestacao/fraud/externa/solicitacoes-idas-bio",
        label="Contestação — solicitações IDAS e BIO",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-compliance-auditoria",
        path="/secao/qualidade/auditoria/compliance",
        label="Auditoria Compliance",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_COMPLIANCE_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-compliance-auditoria-cadastro",
        path="/secao/qualidade/auditoria/compliance/cadastro",
        label="Compliance — Auditoria Cadastro",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_COMPLIANCE_CREATE,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-compliance-auditoria-fila",
        path="/secao/qualidade/auditoria/compliance/fila",
        label="Compliance — Auditoria Minha Fila",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_COMPLIANCE_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-compliance-auditoria-controle",
        path="/secao/qualidade/auditoria/compliance/controle",
        label="Compliance — Auditoria Centro de operações",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_COMPLIANCE_ASSIGN,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-compliance-auditoria-consulta",
        path="/secao/qualidade/auditoria/compliance/consulta",
        label="Compliance — Auditoria Consulta",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_COMPLIANCE_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-compliance-contestacao-interna",
        path="/secao/qualidade/contestacao/compliance/interna",
        label="Contestação Compliance — interna",
        section="qualidade",
        permissions_any=(R.QUAL_CONTESTACAO_INTERNA_COMPLIANCE_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-compliance-contestacao-reinspecao-cadastro",
        path="/secao/qualidade/contestacao/compliance/reinspecao/cadastro",
        label="Compliance — Reinspeção Cadastro",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_CREATE,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-compliance-contestacao-reinspecao-fila",
        path="/secao/qualidade/contestacao/compliance/reinspecao/fila",
        label="Compliance — Reinspeção Minha Fila",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-compliance-contestacao-reinspecao-controle",
        path="/secao/qualidade/contestacao/compliance/reinspecao/controle",
        label="Compliance — Reinspeção Centro de operações",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_ASSIGN,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-compliance-contestacao-reinspecao-consulta",
        path="/secao/qualidade/contestacao/compliance/reinspecao/consulta",
        label="Compliance — Reinspeção Consulta",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-capacitacao-suporte",
        path="/secao/qualidade/capacitacao/suporte",
        label="Capacitação — Suporte",
        section="qualidade",
        permissions_any=(R.QUAL_CAPACITACAO_SUPORTE_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-capacitacao-suporte-offline",
        path="/secao/qualidade/capacitacao/suporte/offline",
        label="Capacitação — Suporte offline",
        section="qualidade",
        permissions_any=(R.QUAL_CAPACITACAO_SUPORTE_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-capacitacao-suporte-presencial",
        path="/secao/qualidade/capacitacao/suporte/presencial",
        label="Capacitação — Suporte presencial",
        section="qualidade",
        permissions_any=(R.QUAL_CAPACITACAO_SUPORTE_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-capacitacao-suporte-fila",
        path="/secao/qualidade/capacitacao/suporte/fila",
        label="Capacitação — Suporte online (fila)",
        section="qualidade",
        permissions_any=(R.QUAL_CAPACITACAO_SUPORTE_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-capacitacao-suporte-controle",
        path="/secao/qualidade/capacitacao/suporte/controle",
        label="Capacitação — Suporte online (controle)",
        section="qualidade",
        permissions_any=(R.QUAL_CAPACITACAO_SUPORTE_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-capacitacao-suporte-recados",
        path="/secao/qualidade/capacitacao/suporte/recados",
        label="Capacitação — Mural de recados",
        section="qualidade",
        permissions_any=(R.QUAL_CAPACITACAO_SUPORTE_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-capacitacao-treinamento",
        path="/secao/qualidade/capacitacao/treinamento",
        label="Capacitação — Treinamento",
        section="qualidade",
        permissions_any=(R.QUAL_AUDITORIA_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-capacitacao-revisao-falhas",
        path="/secao/qualidade/capacitacao/revisao-falhas",
        label="Capacitação — Revisão de falhas",
        section="qualidade",
        permissions_any=(R.QUAL_CAPACITACAO_REVISAO_FALHAS_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="produtividade",
        path="/secao/indicadores/produtividade/:module?",
        label="Produtividade",
        section="indicadores",
        permissions_any=(R.INDICADORES_PRODUTIVIDADE_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="case-manager",
        path="/secao/indicadores/case-manager/:module?",
        label="Case Manager",
        section="indicadores",
        permissions_any=(R.INDICADORES_CASE_MANAGER_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="monitoramento-sla",
        path="/secao/indicadores/monitoramento-sla/:module?",
        label="Monitoramento SLA",
        section="indicadores",
        permissions_any=(R.INDICADORES_MONITORAMENTO_SLA_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="relatorio-brb",
        path="/secao/indicadores/relatorio-brb",
        label="Relatório Quality Pulse",
        section="indicadores",
        permissions_any=(R.INDICADORES_RELATORIO_BRB_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="ciencia-leitura",
        path="/operacao/ciencia-leitura",
        label="Ciência de leitura",
        section="operacao",
        permissions_any=(R.OPERACAO_CIENCIA_LEITURA_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="operacao-contestacao",
        path="/operacao/contestacao/nova",
        label="Operação — Nova contestação",
        section="operacao",
        permissions_any=(R.OPERACAO_CONTESTACAO_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="operacao-contestacao-minhas",
        path="/operacao/contestacao/minhas",
        label="Contestação de falhas — Minhas",
        section="operacao",
        permissions_any=(R.OPERACAO_CONTESTACAO_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="section",
        path="/secao/:slug",
        label="Seção genérica",
        section="home",
        permissions_any=(R.PORTAL_SECAO_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-megazord-headcount",
        path="/planejamento/megazord/headcount",
        label="Megazord — Headcount",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_HEADCOUNT_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-megazord-capacity",
        path="/planejamento/megazord/projecao-equipes",
        label="Megazord — Projeção de equipes",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_MEGAZORD_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-megazord-derivacao-etapa",
        path="/planejamento/megazord/derivacao-etapa",
        label="Megazord — Derivação etapa",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_MEGAZORD_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-megazord-capacity",
        path="/planejamento/megazord/projecao-equipes",
        label="Megazord - Projecao de equipes",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_MEGAZORD_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="dashboard",
        path="/dashboard",
        label="Dashboard de Headcount",
        section="indicadores",
        permissions_any=(R.INDICADORES_DASHBOARD_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="brand-icon-preview",
        path="/dev/brand-icons",
        label="Dev — Brand icons",
        section="dev",
        permissions_any=(R.ADM_CONSOLE_OPS,),
    ),
    PortalRouteDefinition(
        route_name="controle-jornada-icon-preview",
        path="/dev/controle-jornada-icons",
        label="Dev — Controle jornada icons",
        section="dev",
        permissions_any=(R.ADM_CONSOLE_OPS,),
    ),
    PortalRouteDefinition(
        route_name="absence-timeline-mockups",
        path="/dev/absence-timeline-mockups",
        label="Dev — Absence timeline mockups",
        section="dev",
        permissions_any=(R.ADM_CONSOLE_OPS,),
    ),
    PortalRouteDefinition(
        route_name="home-layout-mockups",
        path="/dev/home-layout-mockups",
        label="Dev — Home layout mockups",
        section="dev",
        permissions_any=(R.ADM_CONSOLE_OPS,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-escalas-consulta",
        path="/planejamento/escalas/consulta",
        label="Escalas — consulta",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_ESCALAS_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-escalas-anexar",
        path="/planejamento/escalas/anexar",
        label="Escalas — importação",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_ESCALAS_IMPORT,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-escalas-criar",
        path="/planejamento/escalas/criar",
        label="Escalas — criação automática",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_ESCALAS_GENERATE,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-falhas-import",
        path="/planejamento/falhas-import",
        label="Importar falhas",
        section="planejamento",
        permissions_any=(R.ADM_FALHAS_IMPORT,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-demandas-jira",
        path="/planejamento/demandas-jira",
        label="Demandas Jira",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_DEMANDAS_JIRA_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-portal-ops",
        path="/planejamento/portal-ops",
        label="Portal Ops",
        section="planejamento",
        permissions_any=_PORTAL_OPS,
    ),
    PortalRouteDefinition(
        route_name="portal-ops-doc",
        path="/planejamento/portal-ops/doc",
        label="Portal Ops — documentação",
        section="planejamento",
        permissions_any=_PORTAL_OPS,
    ),
    PortalRouteDefinition(
        route_name="planejamento-psa-cyber",
        path="/planejamento/psa-cyber",
        label="Cyber PSA",
        section="planejamento",
        permissions_any=(R.ADM_PSA_CYBER,),
    ),
    PortalRouteDefinition(
        route_name="psa-cyber-doc",
        path="/planejamento/psa-cyber/doc",
        label="Cyber PSA — documentação",
        section="planejamento",
        permissions_any=(R.ADM_PSA_CYBER,),
    ),
    PortalRouteDefinition(
        route_name="indicadores-replicacao-d1",
        path="/secao/indicadores/replicacao-d1",
        label="Replicação D-1",
        section="indicadores",
        permissions_any=(R.PLANEJAMENTO_AUTOMACAO_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-automacao",
        path="/planejamento/automacao",
        label="Automação",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_AUTOMACAO_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-automacao-replicacao-d1-config",
        path="/planejamento/automacao/replicacao-d1/configuracao",
        label="Replicação D-1 — configuração",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_AUTOMACAO_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="processos-suporte-claro",
        path="/processos/suporte-claro/:module?",
        label="Suporte Claro",
        section="processos",
        permissions_any=(R.PROCESSOS_SUPORTE_CLARO_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-ocorrencias",
        path="/planejamento/ocorrencias",
        label="Ocorrências — aprovação",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_OCORRENCIAS_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-trocas",
        path="/planejamento/trocas",
        label="Trocas — aprovação",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_TROCAS_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="operacao-ocorrencias",
        path="/operacao/ocorrencias",
        label="Ocorrências (operação)",
        section="operacao",
        permissions_any=(R.OPERACAO_OCORRENCIAS_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="operacao-trocas",
        path="/operacao/trocas",
        label="Trocas (operação)",
        section="operacao",
        permissions_any=(R.OPERACAO_TROCAS_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="operacao-suporte-operacional",
        path="/operacao/suporte-operacional",
        label="Suporte operacional",
        section="operacao",
        permissions_any=(R.OPERACAO_SUPORTE_OPERACIONAL_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="configuracoes",
        path="/configuracoes",
        label="Configurações — hub",
        section="configuracoes",
        permissions_any=_CONFIG_HUB,
    ),
    PortalRouteDefinition(
        route_name="configuracoes-status",
        path="/configuracoes/status",
        label="Status operacionais",
        section="configuracoes",
        permissions_any=(R.ADM_CATALOGOS,),
    ),
    PortalRouteDefinition(
        route_name="configuracoes-ocorrencias",
        path="/configuracoes/ocorrencias",
        label="Tipos de ocorrência",
        section="configuracoes",
        permissions_any=(R.ADM_CATALOGOS,),
    ),
    PortalRouteDefinition(
        route_name="configuracoes-ausencias",
        path="/configuracoes/ausencias",
        label="Tipos de ausência",
        section="configuracoes",
        permissions_any=(R.ADM_CATALOGOS,),
    ),
    PortalRouteDefinition(
        route_name="configuracoes-qualidade",
        path="/configuracoes/qualidade",
        label="Catálogos de Qualidade",
        section="configuracoes",
        permissions_any=(R.ADM_CATALOGOS,),
    ),
    PortalRouteDefinition(
        route_name="configuracoes-qualidade-cenarios",
        path="/configuracoes/qualidade/cenarios",
        label="Qualidade — cenários",
        section="configuracoes",
        permissions_any=(R.ADM_CATALOGOS,),
    ),
    PortalRouteDefinition(
        route_name="configuracoes-qualidade-suporte-registros",
        path="/configuracoes/qualidade/suporte-registros",
        label="Qualidade - suporte de registros",
        section="configuracoes",
        permissions_any=(
            R.ADM_QUALIDADE_REGISTROS_VIEW,
            R.ADM_QUALIDADE_REGISTROS_MANAGE,
        ),
    ),
    PortalRouteDefinition(
        route_name="configuracoes-qualidade-catalog",
        path="/configuracoes/qualidade/:catalogSlug",
        label="Qualidade — catálogo",
        section="configuracoes",
        permissions_any=(R.ADM_CATALOGOS,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-configuracao",
        path="/secao/qualidade/configuracao",
        label="Qualidade — configuração",
        section="qualidade",
        permissions_any=(R.ADM_CATALOGOS,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-configuracao-cenarios",
        path="/secao/qualidade/configuracao/cenarios",
        label="Qualidade — configuração de cenários",
        section="qualidade",
        permissions_any=(R.ADM_CATALOGOS,),
    ),
    PortalRouteDefinition(
        route_name="qualidade-configuracao-catalog",
        path="/secao/qualidade/configuracao/:catalogSlug",
        label="Qualidade — configuração de catálogo",
        section="qualidade",
        permissions_any=(R.ADM_CATALOGOS,),
    ),
    PortalRouteDefinition(
        route_name="configuracoes-headcount-catalogos",
        path="/configuracoes/headcount-catalogos",
        label="Catálogos de Headcount",
        section="configuracoes",
        permissions_any=(R.ADM_CATALOGOS,),
    ),
    PortalRouteDefinition(
        route_name="configuracoes-headcount-catalog",
        path="/configuracoes/headcount-catalogos/:catalogSlug",
        label="Headcount — catálogo",
        section="configuracoes",
        permissions_any=(R.ADM_CATALOGOS,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-megazord",
        path="/planejamento/megazord",
        label="Megazord",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_MEGAZORD_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-megazord-import-identificacao",
        path="/planejamento/megazord/import-identificacao",
        label="Megazord — importar catálogo",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_MEGAZORD_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-megazord-catalog",
        path="/planejamento/megazord/:slug",
        label="Megazord — catálogo",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_MEGAZORD_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="configuracoes-impersonacao",
        path="/configuracoes/impersonacao",
        label="Impersonação",
        section="configuracoes",
        permissions_any=(R.ADM_ESCALA_IMPERSONATE,),
    ),
    PortalRouteDefinition(
        route_name="configuracoes-notificacoes",
        path="/configuracoes/notificacoes",
        label="Configurações — notificações",
        section="configuracoes",
        permissions_any=(R.ADM_CONFIG_HUB,),
    ),
    PortalRouteDefinition(
        route_name="configuracoes-usuarios",
        path="/configuracoes/usuarios",
        label="Gestão de usuários",
        section="configuracoes",
        permissions_any=(R.ADM_USERS_MANAGE,),
    ),
    PortalRouteDefinition(
        route_name="configuracoes-rbac-perfis",
        path="/configuracoes/rbac-perfis",
        label="RBAC — perfis do portal",
        section="configuracoes",
        permissions_any=(R.ADM_CONFIG_HUB,),
    ),
    PortalRouteDefinition(
        route_name="configuracoes-feedbacks-onboarding",
        path="/configuracoes/feedbacks-onboarding",
        label="Feedbacks do Onboarding Protection",
        section="configuracoes",
        permissions_any=(R.ADM_CONFIG_HUB,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-monitoramento-painel",
        path="/planejamento/monitoramento/painel",
        label="Monitoramento — painel",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_MONITORAMENTO_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-monitoramento-escala",
        path="/planejamento/monitoramento/escala",
        label="Monitoramento — escala",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_MONITORAMENTO_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-monitoramento-nh",
        path="/planejamento/monitoramento/nh",
        label="Monitoramento — NH",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_MONITORAMENTO_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-monitoramento-intervalo",
        path="/planejamento/monitoramento/intervalo",
        label="Monitoramento — intervalo",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_MONITORAMENTO_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-monitoramento-dashboards",
        path="/planejamento/monitoramento/dashboards",
        label="Monitoramento — dashboards",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_MONITORAMENTO_DASHBOARDS_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-monitoramento-controle-sla",
        path="/planejamento/monitoramento/controle-sla",
        label="Monitoramento — controle de SLA",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_MONITORAMENTO_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="planejamento-monitoramento-controle-sla-historico",
        path="/planejamento/monitoramento/controle-sla/historico",
        label="Monitoramento — histórico de SLA estourados",
        section="planejamento",
        permissions_any=(R.PLANEJAMENTO_MONITORAMENTO_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="operacao-controle-jornada-painel",
        path="/operacao/controle-de-jornada/painel",
        label="Controle de jornada — painel",
        section="operacao",
        permissions_any=(R.OPERACAO_JORNADA_PAINEL_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="operacao-controle-jornada-escala",
        path="/operacao/controle-de-jornada/escala",
        label="Controle de jornada — escala",
        section="operacao",
        permissions_any=(R.OPERACAO_JORNADA_ESCALA_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="operacao-controle-jornada-historico",
        path="/operacao/controle-de-jornada/historico",
        label="Controle de jornada — histórico",
        section="operacao",
        permissions_any=(R.OPERACAO_HISTORICO_VIEW,),
    ),
    PortalRouteDefinition(
        route_name="operacao-controle-jornada-agente",
        path="/operacao/controle-de-jornada/agente",
        label="Controle de jornada — meu status",
        section="operacao",
        permissions_any=(R.OPERACAO_STATUS_VIEW,),
    ),
)

PORTAL_ROUTE_BY_NAME = {item.route_name: item for item in PORTAL_ROUTE_DEFINITIONS}
