# Generated by Django 5.1.15 on 2026-06-17 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workforce', '0007_rename_agent_active_idx_agent_active_c8098c_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_lan_id', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('sharepoint_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'ef_app_user',
            },
        ),
        migrations.CreateModel(
            name='HierarchicalLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='nível hierárquico')),
                ('active', models.BooleanField(default=True)),
                ('sharepoint_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'ef_hierarchical_level',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='atividade')),
                ('active', models.BooleanField(default=True)),
                ('sharepoint_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'ef_job_activity',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='jornada')),
                ('entry_time', models.TimeField(blank=True, null=True)),
                ('exit_time', models.TimeField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=64, verbose_name='turno')),
                ('active', models.BooleanField(default=True)),
                ('sharepoint_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'ef_journey',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=128, verbose_name='cidade')),
                ('state_name', models.CharField(blank=True, max_length=64, verbose_name='estado')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='nome exibição')),
                ('active', models.BooleanField(default=True)),
                ('sharepoint_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'ef_location',
                'ordering': ['city_name'],
            },
        ),
        migrations.CreateModel(
            name='NotifyEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, max_length=128, verbose_name='ação')),
                ('status', models.CharField(blank=True, max_length=64)),
                ('time', models.TimeField(blank=True, null=True)),
                ('sharepoint_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'ef_notify',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_lan_id', models.CharField(db_index=True, max_length=64)),
                ('leader_lan_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('hourly_data', models.JSONField(blank=True, default=dict)),
                ('total', models.CharField(blank=True, max_length=32)),
                ('sharepoint_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ef_production_record',
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='tipo')),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('sharepoint_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'ef_request_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('color', models.CharField(blank=True, max_length=32, verbose_name='cor hex')),
                ('icon', models.CharField(blank=True, max_length=64, verbose_name='ícone')),
                ('active', models.BooleanField(default=True)),
                ('logged_in', models.BooleanField(default=False)),
                ('sharepoint_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'tipo de status',
                'verbose_name_plural': 'tipos de status',
                'db_table': 'ef_status_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BreakTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_lan_id', models.CharField(db_index=True, max_length=64, verbose_name='UserLanID')),
                ('week', models.CharField(blank=True, max_length=32, verbose_name='intervalo semanal')),
                ('weekend', models.CharField(blank=True, max_length=32, verbose_name='intervalo extra')),
                ('active', models.BooleanField(default=True)),
                ('sharepoint_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'ef_break_time',
                'indexes': [models.Index(fields=['agent_lan_id', 'active'], name='ef_break_ti_agent_l_cf3221_idx')],
            },
        ),
        migrations.CreateModel(
            name='CurrentActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_activity', models.CharField(blank=True, max_length=255)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('sharepoint_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_activity_record', to='workforce.agent')),
            ],
            options={
                'db_table': 'ef_current_activity',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('holiday_type', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('sharepoint_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'ef_holiday',
                'indexes': [models.Index(fields=['date', 'location'], name='ef_holiday_date_a67f04_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_activity', models.CharField(blank=True, max_length=255)),
                ('start_of_work', models.DateTimeField(blank=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('sharepoint_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operational_status', to='workforce.agent')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escala_flex.statustype')),
            ],
            options={
                'db_table': 'ef_agent_status',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='data')),
                ('work_schedule', models.CharField(blank=True, max_length=32, verbose_name='escala')),
                ('working_hour', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='horas')),
                ('overtime', models.BooleanField(default=False, verbose_name='hora extra')),
                ('work_day', models.BooleanField(default=True, verbose_name='dia útil')),
                ('sharepoint_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='workforce.agent')),
            ],
            options={
                'db_table': 'ef_schedule',
                'indexes': [models.Index(fields=['date', 'agent'], name='ef_schedule_date_fe6e83_idx'), models.Index(fields=['date', 'work_day'], name='ef_schedule_date_aee49c_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent', 'date'), name='ef_unique_schedule_agent_date')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_lan_id', models.CharField(blank=True, max_length=64)),
                ('agent_lan_id_2', models.CharField(blank=True, max_length=64)),
                ('applicant_lan_id', models.CharField(blank=True, max_length=64)),
                ('date_swap', models.DateField(blank=True, null=True)),
                ('date_request', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('new_journey', models.CharField(blank=True, max_length=128)),
                ('balance_time', models.CharField(blank=True, max_length=64)),
                ('positive', models.BooleanField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('approved_leader', models.BooleanField(blank=True, null=True)),
                ('date_approve_leader', models.DateTimeField(blank=True, null=True)),
                ('approver_leader_lan_id', models.CharField(blank=True, max_length=64)),
                ('date_approve_plan', models.DateTimeField(blank=True, null=True)),
                ('approver_plan_lan_id', models.CharField(blank=True, max_length=64)),
                ('validation_days', models.CharField(blank=True, max_length=64)),
                ('validation_hour', models.CharField(blank=True, max_length=64)),
                ('validation_activity', models.CharField(blank=True, max_length=255)),
                ('sharepoint_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escala_flex.requesttype')),
            ],
            options={
                'db_table': 'ef_schedule_request',
                'indexes': [models.Index(fields=['date_swap'], name='ef_schedule_date_sw_c33761_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leader_lan_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('start_date', models.DateTimeField()),
                ('final_date', models.DateTimeField(blank=True, null=True)),
                ('active_event', models.BooleanField(default=True)),
                ('display', models.BooleanField(default=True)),
                ('sharepoint_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='workforce.agent')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_status_events', to='workforce.agent')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escala_flex.statustype')),
            ],
            options={
                'db_table': 'ef_status_event',
                'indexes': [models.Index(fields=['agent', 'start_date'], name='ef_status_e_agent_i_5e1d0d_idx'), models.Index(fields=['leader_lan_id', 'display'], name='ef_status_e_leader__0a4dc8_idx'), models.Index(fields=['agent', 'active_event'], name='ef_status_e_agent_i_6d3699_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleToday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='data')),
                ('work_schedule', models.CharField(blank=True, max_length=32, verbose_name='escala do dia')),
                ('working_hour', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('overtime', models.BooleanField(default=False)),
                ('current_activity', models.CharField(blank=True, max_length=255)),
                ('start_of_work', models.DateTimeField(blank=True, null=True)),
                ('week_break', models.CharField(blank=True, max_length=32)),
                ('weekend_break', models.CharField(blank=True, max_length=32)),
                ('is_previous_night_shift', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('job_activity', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('journey', models.CharField(blank=True, max_length=128)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('leader_lan_id', models.CharField(blank=True, max_length=64)),
                ('blocked', models.BooleanField(default=False)),
                ('blocked_by', models.CharField(blank=True, max_length=255)),
                ('blocked_description', models.TextField(blank=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('last_change', models.DateTimeField(blank=True, null=True)),
                ('sharepoint_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_today_entries', to='workforce.agent')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_schedule_today', to='workforce.agent')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_today_entries', to='escala_flex.statustype')),
            ],
            options={
                'db_table': 'ef_schedule_today',
                'indexes': [models.Index(fields=['date', 'agent'], name='ef_schedule_date_923ec6_idx'), models.Index(fields=['date', 'leader_lan_id'], name='ef_schedule_date_f69a2c_idx'), models.Index(fields=['date', 'status'], name='ef_schedule_date_e582f7_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent', 'date'), name='ef_unique_schedule_today_agent_date')],
            },
        ),
    ]
