# Generated by Django 5.1.15 on 2026-06-17 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala_flex', '0001_initial'),
        ('workforce', '0007_rename_agent_active_idx_agent_active_c8098c_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, verbose_name='arquivo')),
                ('sheets_processed', models.JSONField(blank=True, default=list)),
                ('rows_upserted', models.PositiveIntegerField(default=0)),
                ('schedules_synced', models.PositiveIntegerField(default=0)),
                ('dates_rebuilt', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escala_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'escala_import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bloco', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('equipe', models.CharField(blank=True, max_length=255)),
                ('horario', models.CharField(blank=True, max_length=32, verbose_name='horário padrão')),
                ('data', models.DateField(verbose_name='data')),
                ('dia_escala', models.CharField(blank=True, max_length=32, verbose_name='valor do dia')),
                ('sheet_name', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escala_entries', to='workforce.agent')),
                ('job_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escala_entries', to='escala_flex.jobactivity')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_escala_entries', to='workforce.agent')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escala_entries', to='escala_flex.location')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='escala_flex.escalaimportbatch')),
            ],
            options={
                'db_table': 'escala',
                'indexes': [models.Index(fields=['data', 'agent'], name='escala_data_fac4e4_idx'), models.Index(fields=['sheet_name'], name='escala_sheet_n_d7dd89_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent', 'data'), name='escala_unique_agent_date')],
            },
        ),
    ]
