# Generated by Django 5.2.15 on 2026-06-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala_flex', '0009_remove_escala_sheet_name'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='statusevent',
            new_name='ef_status_e_leader__c5c0e7_idx',
            old_name='ef_status_e_leader_id_idx',
        ),
        migrations.AlterField(
            model_name='statusevent',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Comentário do líder na aprovação/rejeição.'),
        ),
    ]
