# Generated by Django 5.2.15 on 2026-06-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escala_flex', '0012_merge_operational_occurrence_and_index_rename'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='operationaloccurrence',
            new_name='ef_operatio_date_c0e58f_idx',
            old_name='ef_operatio_date_0a8f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='operationaloccurrence',
            new_name='ef_operatio_approve_bb109e_idx',
            old_name='ef_operatio_approve_6d2f1a_idx',
        ),
        migrations.RenameIndex(
            model_name='operationaloccurrence',
            new_name='ef_operatio_leader__5b5102_idx',
            old_name='ef_operatio_leader__f4a2b1_idx',
        ),
    ]
