# Generated by Django 5.2.15 on 2026-07-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escala_flex', '0018_operational_occurrence_extension'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='operationaloccurrenceextension',
            new_name='ef_operatio_occurre_48421c_idx',
            old_name='ef_occ_ext_occ_appr_idx',
        ),
    ]
