# Generated by Django 5.2.14 on 2026-08-05 12:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala_flex', '0022_delete_productionrecord'),
        ('workforce', '0011_rename_cycle_change_audit_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaGenerationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_month', models.DateField(verbose_name='mês de referência')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('processing', 'Processando'), ('ready', 'Pronta para revisão'), ('published', 'Publicada'), ('failed', 'Falhou'), ('cancelled', 'Cancelada')], default='draft', max_length=20)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('agents_considered', models.PositiveIntegerField(default=0)),
                ('entries_generated', models.PositiveIntegerField(default=0)),
                ('conflicts_count', models.PositiveIntegerField(default=0)),
                ('failure_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escala_generation_runs_created', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escala_generation_runs_published', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'escala_generation_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscalaGenerationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('team', models.CharField(blank=True, max_length=255)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('schedule', models.CharField(blank=True, max_length=32, verbose_name='horário padrão')),
                ('day_value', models.CharField(blank=True, max_length=32, verbose_name='valor do dia')),
                ('source', models.CharField(default='generated', max_length=32)),
                ('has_conflict', models.BooleanField(default=False)),
                ('adjusted_manually', models.BooleanField(default=False)),
                ('observation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escala_generation_entries_adjusted', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escala_generation_entries', to='workforce.agent')),
                ('job_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_entries', to='escala_flex.jobactivity')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_escala_generation_entries', to='workforce.agent')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_entries', to='escala_flex.location')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='escala_flex.escalagenerationrun')),
            ],
            options={
                'db_table': 'escala_generation_entry',
                'ordering': ['date', 'agent__full_name'],
            },
        ),
        migrations.CreateModel(
            name='EscalaGenerationConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=255)),
                ('conflict_type', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('blocking', 'Impeditivo'), ('warning', 'Aviso')], max_length=16)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escala_generation_conflicts', to='workforce.agent')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escala_generation_conflicts_resolved', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='escala_flex.escalagenerationentry')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='escala_flex.escalagenerationrun')),
            ],
            options={
                'db_table': 'escala_generation_conflict',
                'ordering': ['severity', 'date', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='escalagenerationentry',
            index=models.Index(fields=['run', 'date'], name='escala_gene_run_id_09ef55_idx'),
        ),
        migrations.AddIndex(
            model_name='escalagenerationentry',
            index=models.Index(fields=['run', 'has_conflict'], name='escala_gene_run_id_9013ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='escalagenerationentry',
            constraint=models.UniqueConstraint(fields=('run', 'agent', 'date'), name='escala_generation_unique_run_agent_date'),
        ),
        migrations.AddIndex(
            model_name='escalagenerationconflict',
            index=models.Index(fields=['run', 'severity', 'resolved'], name='escala_gene_run_id_f2aa81_idx'),
        ),
    ]
