# Generated by Django 5.1.15 on 2026-08-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escala_flex', '0023_escala_generation_models'),
        ('escala_flex', '0023_operational_alert_event'),
    ]

    operations = [
    ]
