# Generated by Django 5.1.15 on 2026-08-14 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_key', models.CharField(db_index=True, max_length=32, unique=True)),
                ('project_key', models.CharField(db_index=True, max_length=32)),
                ('project_name', models.CharField(blank=True, default='', max_length=128)),
                ('summary', models.CharField(max_length=512)),
                ('description_excerpt', models.TextField(blank=True, default='')),
                ('status_name', models.CharField(db_index=True, max_length=128)),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('assignee_display', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('assignee_username', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('reporter_display', models.CharField(blank=True, default='', max_length=255)),
                ('priority_name', models.CharField(blank=True, default='', max_length=64)),
                ('issue_type', models.CharField(blank=True, default='', max_length=128)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('components', models.JSONField(blank=True, default=list)),
                ('categoria', models.CharField(choices=[('headcount', 'Headcount'), ('ocorrencias', 'Ocorrências'), ('escala_trocas', 'Escala / trocas / volumetria'), ('regras_workflow', 'Regras de workflow'), ('replicacao', 'Replicação / migração'), ('megazord', 'Megazord / metas / SLA'), ('intranet_bi', 'Intranet / BI'), ('confer', 'Confer'), ('brflow', 'BrFlow / NH'), ('suporte_claro', 'Suporte Claro'), ('outro', 'Outros')], db_index=True, default='outro', max_length=32)),
                ('portal_path', models.CharField(blank=True, default='', max_length=255)),
                ('jira_url', models.URLField(blank=True, default='', max_length=512)),
                ('created_at_jira', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at_jira', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'planejamento_jira_demanda',
                'ordering': ['-updated_at_jira', '-issue_key'],
                'indexes': [models.Index(fields=['project_key', 'is_open', '-updated_at_jira'], name='planejament_project_906932_idx'), models.Index(fields=['categoria', 'is_open'], name='planejament_categor_85d991_idx')],
            },
        ),
        migrations.CreateModel(
            name='JiraDemandaSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Em execução'), ('success', 'Sucesso'), ('failed', 'Falha')], default='running', max_length=16)),
                ('projects', models.CharField(blank=True, default='', max_length=255)),
                ('jql', models.TextField(blank=True, default='')),
                ('total_fetched', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planejamento_jira_demanda_sync_run',
                'ordering': ['-started_at'],
            },
        ),
    ]
