# Generated by Django 5.1.15 on 2026-08-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento_demandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jirademanda',
            name='in_team_queue',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='jirademanda',
            name='reporter_username',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddIndex(
            model_name='jirademanda',
            index=models.Index(fields=['in_team_queue', 'is_open'], name='planejament_in_team_05f0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='jirademanda',
            index=models.Index(fields=['assignee_username', 'is_open'], name='planejament_assigne_076d1b_idx'),
        ),
    ]
