# Generated by Django 5.1.15 on 2026-06-01 13:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='news/%Y/%m/', verbose_name='imagem')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'imagem da notícia',
                'verbose_name_plural': 'imagens da notícia',
                'db_table': 'news_image',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='news',
            new_name='news_publish_efe204_idx',
            old_name='news_publish_idx',
        ),
        migrations.RenameIndex(
            model_name='news',
            new_name='news_categor_afc81a_idx',
            old_name='news_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='news',
            new_name='news_active_fff6fd_idx',
            old_name='news_active_idx',
        ),
        migrations.AddField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='communication.news'),
        ),
    ]
