# Generated by Django 5.1.15 on 2026-06-01 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_newsimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_key', models.CharField(max_length=64, verbose_name='chave anônima do cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='communication.news')),
            ],
            options={
                'verbose_name': 'curtida',
                'verbose_name_plural': 'curtidas',
                'db_table': 'news_like',
                'indexes': [models.Index(fields=['news'], name='news_like_news_id_d2f765_idx')],
                'constraints': [models.UniqueConstraint(fields=('news', 'client_key'), name='news_like_unique_client')],
            },
        ),
    ]
