# Generated by Django 5.2.15 on 2026-06-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_news_source_critical_and_acknowledgment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='newsacknowledgment',
            new_name='news_acknow_news_id_5e38a5_idx',
            old_name='news_ack_news_idx',
        ),
        migrations.RenameIndex(
            model_name='newsacknowledgment',
            new_name='news_acknow_user_id_7dcd49_idx',
            old_name='news_ack_user_idx',
        ),
        migrations.RenameIndex(
            model_name='newslike',
            new_name='news_like_user_id_fd726d_idx',
            old_name='news_like_user_id_idx',
        ),
    ]
