# Generated by Django 5.2.15 on 2026-08-06 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0009_news_published_at_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protocol', models.CharField(editable=False, max_length=32, unique=True)),
                ('kind', models.CharField(choices=[('sugestao', 'Sugestão'), ('problema', 'Problema'), ('elogio', 'Elogio'), ('duvida', 'Dúvida')], max_length=16)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_analise', 'Em análise'), ('respondido', 'Respondido'), ('concluido', 'Concluído')], default='novo', max_length=16)),
                ('subject', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=2000)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='portal_feedback/%Y/%m/')),
                ('allow_contact', models.BooleanField(default=True)),
                ('page_path', models.CharField(blank=True, default='', max_length=255)),
                ('module_id', models.CharField(blank=True, default='', max_length=120)),
                ('admin_note', models.TextField(blank=True, default='', max_length=2000)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_feedbacks_created', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_feedbacks_handled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'feedback do Onboarding Protection',
                'verbose_name_plural': 'feedbacks do Onboarding Protection',
                'db_table': 'portal_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='portal_feed_status_fad9af_idx'), models.Index(fields=['kind', '-created_at'], name='portal_feed_kind_f47545_idx')],
            },
        ),
    ]
