# Generated by Django 5.2.15 on 2026-07-27 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualidadeAuditado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, db_index=True, null=True)),
                ('data_analise', models.DateField(blank=True, null=True)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('id_workflow', models.IntegerField(blank=True, null=True)),
                ('tipo_analise', models.CharField(blank=True, default='', max_length=128)),
                ('matricula', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('matricula_auditor', models.CharField(blank=True, default='', max_length=64)),
                ('protocolo', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('cenario', models.CharField(blank=True, default='', max_length=512)),
                ('etapa', models.CharField(blank=True, default='', max_length=256)),
                ('status', models.CharField(blank=True, default='', max_length=128)),
                ('irregularidades_apontadas', models.TextField(blank=True, default='')),
                ('cadastrado_anteriormente', models.CharField(blank=True, default='', max_length=128)),
                ('id_operations', models.IntegerField(blank=True, null=True)),
                ('resultado_origem', models.CharField(blank=True, default='', max_length=128)),
                ('resultado_destino', models.CharField(blank=True, default='', max_length=128)),
                ('protocolo_destino', models.CharField(blank=True, default='', max_length=64)),
                ('source_file', models.CharField(blank=True, default='', max_length=255)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'qualidade_auditado',
                'indexes': [models.Index(fields=['id_cliente', 'id_workflow'], name='qo_aud_cli_wf_idx'), models.Index(fields=['tipo_analise'], name='qo_aud_tipo_idx'), models.Index(fields=['data', 'protocolo'], name='qo_aud_data_prot_idx')],
            },
        ),
        migrations.CreateModel(
            name='QualidadeFalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_origem', models.CharField(blank=True, default='', max_length=128)),
                ('frk_colaborador', models.CharField(blank=True, default='', max_length=64)),
                ('protocolo', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('id_workflow', models.IntegerField(blank=True, null=True)),
                ('id_operations', models.IntegerField(blank=True, null=True)),
                ('tipo_analise', models.CharField(blank=True, default='', max_length=128)),
                ('frk_gerenciamento_fluxo', models.CharField(blank=True, default='', max_length=64)),
                ('modulo', models.CharField(blank=True, default='', max_length=128)),
                ('cenario', models.TextField(blank=True, default='')),
                ('data', models.DateField(blank=True, null=True)),
                ('usuario_auditor', models.CharField(blank=True, default='', max_length=64)),
                ('matricula', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('data_analise', models.DateField(blank=True, db_index=True, null=True)),
                ('etapa', models.CharField(blank=True, default='', max_length=256)),
                ('tipo_falha', models.CharField(blank=True, default='', max_length=128)),
                ('uf', models.CharField(blank=True, default='', max_length=8)),
                ('tipo_documento', models.CharField(blank=True, default='', max_length=128)),
                ('nivel_dificuldade', models.CharField(blank=True, default='', max_length=128)),
                ('des_problemas', models.TextField(blank=True, default='')),
                ('tendencia', models.CharField(blank=True, default='', max_length=128)),
                ('novo_resultado', models.CharField(blank=True, default='', max_length=128)),
                ('tipo_solicitacao', models.CharField(blank=True, default='', max_length=128)),
                ('tipo_modulo', models.CharField(blank=True, default='', max_length=128)),
                ('prk_colaborador', models.CharField(blank=True, default='', max_length=64)),
                ('resultado_analise', models.CharField(blank=True, default='', max_length=128)),
                ('numero_solicitacao', models.CharField(blank=True, default='', max_length=64)),
                ('qualidade_imagem', models.CharField(blank=True, default='', max_length=128)),
                ('origem_analise', models.CharField(blank=True, default='', max_length=128)),
                ('data_diferenca', models.CharField(blank=True, default='', max_length=64)),
                ('tipo_modulo_2', models.CharField(blank=True, default='', max_length=128)),
                ('categoria_falha', models.CharField(blank=True, default='', max_length=128)),
                ('localidade', models.CharField(blank=True, default='', max_length=128)),
                ('agente_ativo', models.CharField(blank=True, default='', max_length=64)),
                ('lider', models.CharField(blank=True, default='', max_length=256)),
                ('tipo_falha_oficial', models.CharField(blank=True, default='', max_length=128)),
                ('nivel_dificuldade_confer', models.CharField(blank=True, default='', max_length=128)),
                ('sub_segmento', models.CharField(blank=True, default='', max_length=128)),
                ('segmento', models.CharField(blank=True, default='', max_length=128)),
                ('condicao_metrica', models.CharField(blank=True, default='', max_length=128)),
                ('source_file', models.CharField(blank=True, default='', max_length=255)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'qualidade_falha',
                'indexes': [models.Index(fields=['id_cliente', 'id_workflow'], name='qo_fal_cli_wf_idx'), models.Index(fields=['tipo_falha'], name='qo_fal_tipo_idx'), models.Index(fields=['tipo_falha_oficial'], name='qo_fal_tipo_of_idx'), models.Index(fields=['localidade'], name='qo_fal_loc_idx')],
            },
        ),
    ]
