# Generated by Django 5.2.15 on 2026-07-28 14:54

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('qualidade_operacional', '0002_qualidadeauditado_tipo_conclusao'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualidadeFiltroOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensao', models.CharField(max_length=32)),
                ('valor', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'qualidade_filtro_opcao',
                'ordering': ['dimensao', 'valor'],
            },
        ),
        AddIndexConcurrently(
            model_name='qualidadeauditado',
            index=models.Index(fields=['data_analise'], name='qo_aud_analise_idx'),
        ),
        AddIndexConcurrently(
            model_name='qualidadeauditado',
            index=models.Index(fields=['matricula', 'data'], name='qo_aud_mat_data_idx'),
        ),
        AddIndexConcurrently(
            model_name='qualidadeauditado',
            index=models.Index(fields=['matricula', 'data_analise'], name='qo_aud_mat_ana_idx'),
        ),
        AddIndexConcurrently(
            model_name='qualidadefalha',
            index=models.Index(fields=['data'], name='qo_fal_auditoria_idx'),
        ),
        AddIndexConcurrently(
            model_name='qualidadefalha',
            index=models.Index(fields=['matricula', 'data'], name='qo_fal_mat_data_idx'),
        ),
        AddIndexConcurrently(
            model_name='qualidadefalha',
            index=models.Index(fields=['matricula', 'data_analise'], name='qo_fal_mat_ana_idx'),
        ),
        migrations.AddIndex(
            model_name='qualidadefiltroopcao',
            index=models.Index(fields=['dimensao', 'valor'], name='qo_filtro_dim_val_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualidadefiltroopcao',
            constraint=models.UniqueConstraint(fields=('dimensao', 'valor'), name='qo_filtro_dim_val_uniq'),
        ),
    ]
