# Generated by Django 5.2.15 on 2026-07-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade_operacional', '0004_populate_filter_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualidadeAgenteAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(db_index=True, max_length=64)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(choices=[('reciclagem', 'Reciclagem de procedimento'), ('checklist', 'Reforço de checklist'), ('monitoria', 'Monitoria dirigida'), ('calibracao', 'Calibração com qualidade'), ('acompanhamento', 'Acompanhamento periódico'), ('amostragem', 'Nova amostragem de auditorias'), ('feedback', 'Feedback individual'), ('outro', 'Outro')], db_index=True, default='outro', max_length=32)),
                ('responsavel', models.CharField(blank=True, default='', max_length=255)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=16)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], db_index=True, default='aberta', max_length=16)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('categoria_falha', models.CharField(blank=True, default='', max_length=255)),
                ('auditorias_vinculadas', models.JSONField(blank=True, default=list)),
                ('criterio_sucesso', models.TextField(blank=True, default='')),
                ('frequencia', models.CharField(choices=[('unica', 'Única'), ('diaria', 'Diária'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal')], default='unica', max_length=16)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concluida_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qualidade_agente_acao',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['matricula', 'status'], name='qo_acao_mat_status_idx'), models.Index(fields=['matricula', '-created_at'], name='qo_acao_mat_created_idx')],
            },
        ),
    ]
