# Generated by Django 5.2.15 on 2026-07-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade_operacional', '0007_retroactive_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualidadeimportchunk',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
