# Generated by Django 5.2.15 on 2026-08-07 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0047_qualidade_sync_indexes"),
        ("qualidade_operacional", "0011_import_cancel_rollback"),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualidadeauditado',
            name='protocolo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='qualidadeauditado',
            name='protocolo_destino',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='qualidadefalha',
            name='protocolo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='QualidadeIntranetProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_version', models.PositiveSmallIntegerField(default=1)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('source_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sync_status', models.CharField(choices=[('ok', 'OK'), ('skipped', 'Ignorado'), ('error', 'Erro')], db_index=True, default='ok', max_length=16)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('auditado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intranet_projection', to='qualidade_operacional.qualidadeauditado')),
                ('falha', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intranet_projection', to='qualidade_operacional.qualidadefalha')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualidade_projection', to='auditoria.auditoriafalhacadastro')),
            ],
            options={
                'db_table': 'qualidade_intranet_projection',
                'indexes': [models.Index(fields=['sync_status', 'synced_at'], name='qo_intra_sync_idx'), models.Index(fields=['mapping_version'], name='qo_intra_mapver_idx')],
            },
        ),
    ]
