# Generated by Django 5.2.15 on 2026-07-20 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCliente',
            fields=[
                ('id_cliente', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=512)),
                ('operations', models.BooleanField(default=True)),
                ('id_classificacao', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'dim_cliente',
                'ordering': ['id_cliente'],
            },
        ),
        migrations.CreateModel(
            name='DimEtapa',
            fields=[
                ('id_etapa', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'dim_etapa',
                'ordering': ['id_etapa'],
            },
        ),
        migrations.CreateModel(
            name='DimGrupoServico',
            fields=[
                ('id_grupo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Grupo de serviço',
                'verbose_name_plural': 'Grupos de serviço',
                'db_table': 'dim_grupo_servico',
                'ordering': ['id_grupo'],
            },
        ),
        migrations.CreateModel(
            name='DimNivelHierarquico',
            fields=[
                ('id_nh', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=512)),
                ('ind_considerar', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nível hierárquico',
                'verbose_name_plural': 'Níveis hierárquicos',
                'db_table': 'dim_nivel_hierarquico',
                'ordering': ['id_nh'],
            },
        ),
        migrations.CreateModel(
            name='DimProduto',
            fields=[
                ('id_produto', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('tipo_produto', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'dim_produto',
                'ordering': ['id_produto'],
            },
        ),
        migrations.CreateModel(
            name='DimServico',
            fields=[
                ('id_servico', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('meta_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('grupo', models.ForeignKey(blank=True, db_column='id_grupo_servico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos', to='dimensoes_processos.dimgruposervico')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'db_table': 'dim_servico',
                'ordering': ['id_servico'],
            },
        ),
        migrations.CreateModel(
            name='DimWorkflow',
            fields=[
                ('id_workflow', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=512)),
                ('ind_considerar', models.BooleanField(default=True)),
                ('tipo_atendimento', models.CharField(blank=True, default='', max_length=64)),
                ('produto', models.ForeignKey(blank=True, db_column='id_produto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='dimensoes_processos.dimproduto')),
            ],
            options={
                'db_table': 'dim_workflow',
                'ordering': ['id_workflow'],
            },
        ),
        migrations.CreateModel(
            name='ProjecaoEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField(blank=True, null=True)),
                ('matricula_agente', models.CharField(db_index=True, max_length=32)),
                ('nome_agente', models.CharField(blank=True, default='', max_length=255)),
                ('email_agente', models.CharField(blank=True, default='', max_length=255)),
                ('atividade', models.CharField(blank=True, default='', max_length=255)),
                ('matricula_lider', models.CharField(blank=True, default='', max_length=32)),
                ('nome_lider', models.CharField(blank=True, default='', max_length=255)),
                ('email_lider', models.CharField(blank=True, default='', max_length=255)),
                ('equipe', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('matricula_facilitador', models.CharField(blank=True, default='', max_length=32)),
                ('id_operations', models.PositiveIntegerField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, default='', max_length=64)),
                ('turno', models.CharField(blank=True, default='', max_length=64)),
                ('localidade', models.CharField(blank=True, default='', max_length=64)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('funcao', models.CharField(blank=True, default='', max_length=128)),
                ('setor', models.CharField(blank=True, default='', max_length=255)),
                ('pcd', models.CharField(blank=True, default='', max_length=16)),
                ('desconto_meta', models.CharField(blank=True, default='', max_length=64)),
                ('matricula_oracle', models.CharField(blank=True, default='', max_length=64)),
                ('matricula_ponto', models.CharField(blank=True, default='', max_length=64)),
                ('observacao', models.CharField(blank=True, default='', max_length=512)),
                ('matricula_supervisor', models.CharField(blank=True, default='', max_length=32)),
                ('supervisor', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('banda', models.CharField(blank=True, default='', max_length=16)),
                ('powerapps_id', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Projeção equipe',
                'verbose_name_plural': 'Projeções equipe',
                'db_table': 'projecao_equipe',
                'ordering': ['-data_inicial', 'matricula_agente'],
                'indexes': [models.Index(fields=['matricula_agente', 'data_inicial'], name='projecao_eq_matricu_b17618_idx'), models.Index(fields=['status', 'equipe'], name='projecao_eq_status_027883_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetaEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('meta_dia', models.DecimalField(decimal_places=2, max_digits=14)),
                ('etapa', models.ForeignKey(db_column='id_etapa', on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='dimensoes_processos.dimetapa')),
                ('servico', models.ForeignKey(blank=True, db_column='id_servico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metas_etapa', to='dimensoes_processos.dimservico')),
            ],
            options={
                'db_table': 'meta_etapa',
                'ordering': ['-data_inicio', 'etapa_id'],
                'indexes': [models.Index(fields=['data_inicio', 'data_fim'], name='meta_etapa_data_in_bc16c1_idx'), models.Index(fields=['etapa'], name='meta_etapa_id_etap_5549fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjecaoSla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('dias_semana', models.CharField(help_text='Ex.: {0..4}, {5}, {10}', max_length=32)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('duracao_atendimento', models.FloatField(blank=True, null=True)),
                ('sla_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('flag_ajuste_sla', models.FloatField(blank=True, null=True)),
                ('sla_ajuste', models.PositiveIntegerField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='projecoes_sla', to='dimensoes_processos.dimcliente')),
                ('nivel_hierarquico', models.ForeignKey(db_column='id_nivel_hierarquico', on_delete=django.db.models.deletion.CASCADE, related_name='projecoes_sla', to='dimensoes_processos.dimnivelhierarquico')),
                ('workflow', models.ForeignKey(db_column='id_workflow', on_delete=django.db.models.deletion.CASCADE, related_name='projecoes_sla', to='dimensoes_processos.dimworkflow')),
            ],
            options={
                'verbose_name': 'Projeção SLA',
                'verbose_name_plural': 'Projeções SLA',
                'db_table': 'projecao_sla',
                'ordering': ['-data_inicio', 'cliente_id', 'workflow_id'],
                'indexes': [models.Index(fields=['data_inicio', 'data_fim'], name='projecao_sl_data_in_19968d_idx'), models.Index(fields=['cliente', 'workflow'], name='projecao_sl_id_clie_951abf_idx'), models.Index(fields=['nivel_hierarquico'], name='projecao_sl_id_nive_c65ac1_idx')],
            },
        ),
    ]
