# Generated by Django 5.2.15 on 2026-08-25 03:32

import apps.dimensoes_processos.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensoes_processos', '0009_capacity_daily_snapshot_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='derivacaoetapadiaria',
            name='manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='derivacaoetapadiaria',
            name='override_notas',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='derivacaoetapadiaria',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivacao_etapa_diaria_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DerivacaoEtapaUploadBatch',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('consumed', 'Consumido'), ('expired', 'Expirado')], default='active', max_length=16)),
                ('file_manifest', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivacao_etapa_upload_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'derivacao_etapa_upload_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DerivacaoEtapaUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.dimensoes_processos.models.derivacao_etapa_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dimensoes_processos.derivacaoetapauploadbatch')),
            ],
            options={
                'db_table': 'derivacao_etapa_upload_file',
                'ordering': ['original_name'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'original_name'), name='uniq_deriv_upload_batch_name')],
            },
        ),
    ]
