# Generated by Django 5.2.15 on 2026-08-27 15:43

import apps.dimensoes_processos.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensoes_processos', '0010_derivacao_upload_and_manual_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivacaoetapaimportrun',
            name='run_kind',
            field=models.CharField(choices=[('scan', 'Scan comparativo'), ('import', 'Importação'), ('purge', 'Apagar base')], default='import', max_length=16),
        ),
        migrations.CreateModel(
            name='IdentificacaoProcessosUpload',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('consumed', 'Consumido'), ('expired', 'Expirado')], default='active', max_length=16)),
                ('original_name', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(upload_to=apps.dimensoes_processos.models.identificacao_processos_upload_to)),
                ('preflight_summary', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identificacao_processos_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identificacao_processos_upload',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdentificacaoProcessosImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('sync', 'Sincronizar'), ('replace', 'Substituir')], default='sync', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Em execução'), ('ok', 'OK'), ('error', 'Erro')], default='running', max_length=16)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identificacao_processos_import_runs', to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_runs', to='dimensoes_processos.identificacaoprocessosupload')),
            ],
            options={
                'db_table': 'identificacao_processos_import_run',
                'ordering': ['-started_at'],
            },
        ),
    ]
