# Generated by Django 5.1.15 on 2026-08-06 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workforce', '0012_agenthistory_sharepoint_item_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalSupportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requester_type', models.CharField(choices=[('agent', 'Agente'), ('leader', 'Líder')], max_length=16)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pending_leader', 'Aguardando líder'), ('pending_support', 'Aguardando suporte'), ('in_analysis', 'Em análise'), ('answered', 'Respondida'), ('rejected_leader', 'Recusada pelo líder'), ('cancelled', 'Cancelada')], db_index=True, max_length=32)),
                ('leader_decision', models.CharField(blank=True, choices=[('approved', 'Aprovada'), ('rejected', 'Recusada')], default='', max_length=16)),
                ('leader_justification', models.TextField(blank=True, default='')),
                ('leader_decided_at', models.DateTimeField(blank=True, null=True)),
                ('auto_approved', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, default='')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_support_requests', to='workforce.agent')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_support_answers', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_support_assigned', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_support_cancellations', to=settings.AUTH_USER_MODEL)),
                ('leader_decider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_support_leader_decisions', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_support_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operational_support_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationalSupportEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Criação'), ('auto_approved', 'Aprovação automática'), ('approved', 'Aprovação'), ('rejected', 'Recusa'), ('cancelled', 'Cancelamento'), ('assigned', 'Atribuição'), ('answered', 'Resposta')], max_length=32)),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(blank=True, default='', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_support_events', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='suporte_operacional.operationalsupportrequest')),
            ],
            options={
                'db_table': 'operational_support_event',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='operationalsupportrequest',
            index=models.Index(fields=['status', 'created_at'], name='operational_status_8e678c_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalsupportrequest',
            index=models.Index(fields=['agent', 'status'], name='operational_agent_i_b5021d_idx'),
        ),
    ]
