# Generated by Django 5.1.15 on 2026-08-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte_operacional', '0002_support_answer_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalsupportrequest',
            name='client',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='operationalsupportrequest',
            name='protocol',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='operationalsupportrequest',
            name='workflow',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
