# Generated by Django 5.1.15 on 2026-08-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte_operacional', '0006_online_queue_and_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalsupportevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Criação'), ('auto_approved', 'Aprovação automática'), ('approved', 'Aprovação'), ('rejected', 'Recusa'), ('cancelled', 'Cancelamento'), ('assigned', 'Atribuição'), ('queue_assigned', 'Fila automática'), ('queue_directed', 'Direcionamento'), ('queue_timeout', 'Timeout da fila'), ('queue_released', 'Liberação da fila'), ('presence_changed', 'Status de presença'), ('answered', 'Resposta')], max_length=32),
        ),
    ]
