# Generated by Django 5.2.14 on 2026-09-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suporte_operacional', '0015_request_type_presencial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='operationalsupportrequest',
            name='ops_req_prot_origin_st_idx',
        ),
    ]
