# Generated by Django 5.2.14 on 2026-06-18 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RotinaBrutoSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('detalhado', 'Detalhado bruto'), ('prod', 'Produtividade D-1 bruto'), ('monitor', 'Monitor bruto')], db_index=True, max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('trigger_source', models.CharField(choices=[('user', 'Usuário (portal/manual)'), ('system', 'Sistema (automático)')], db_index=True, default='user', max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('source_file', models.CharField(blank=True, default='', max_length=500)),
                ('source_mtime', models.FloatField(blank=True, null=True)),
                ('source_size', models.BigIntegerField(blank=True, null=True)),
                ('report_date', models.DateField(blank=True, db_index=True, null=True)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rotina_bruto_sync_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RotinaDetalhadoBrutoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('protocolo', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('cliente', models.CharField(blank=True, default='', max_length=255)),
                ('workflow', models.CharField(blank=True, default='', max_length=255)),
                ('cpf', models.CharField(blank=True, default='', max_length=32)),
                ('data_cadastro', models.CharField(blank=True, default='', max_length=64)),
                ('data_conclusao', models.CharField(blank=True, default='', max_length=64)),
                ('status_registro', models.CharField(blank=True, default='', max_length=255)),
                ('resultado', models.CharField(blank=True, default='', max_length=255)),
                ('nivel_hierarquico', models.CharField(blank=True, default='', max_length=255)),
                ('matricula', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('data_primeira_conclusao', models.CharField(blank=True, default='', max_length=64)),
                ('data_analise', models.CharField(blank=True, default='', max_length=64)),
                ('alertas', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'rotina_detalhado_bruto_record',
                'ordering': ['-report_date', 'protocolo'],
                'indexes': [models.Index(fields=['report_date', 'protocolo'], name='rotina_deta_report__a2da11_idx')],
            },
        ),
        migrations.CreateModel(
            name='RotinaMonitorBrutoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('usuario', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('data_evento', models.CharField(blank=True, default='', max_length=64)),
                ('evento', models.CharField(blank=True, default='', max_length=255)),
                ('id_sessao', models.CharField(blank=True, default='', max_length=255)),
                ('objeto', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'rotina_monitor_bruto_record',
                'ordering': ['-report_date', 'usuario'],
                'indexes': [models.Index(fields=['report_date', 'usuario'], name='rotina_moni_report__c4aff6_idx')],
            },
        ),
        migrations.CreateModel(
            name='RotinaProdBrutoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('des_matricula', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('dat_analise', models.CharField(blank=True, default='', max_length=64)),
                ('num_tempo_analise', models.CharField(blank=True, default='', max_length=64)),
                ('nom_cliente', models.CharField(blank=True, default='', max_length=255)),
                ('nom_workflow', models.CharField(blank=True, default='', max_length=255)),
                ('nom_etapa', models.CharField(blank=True, default='', max_length=255)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'rotina_prod_bruto_record',
                'ordering': ['-report_date', 'des_matricula'],
                'indexes': [models.Index(fields=['report_date', 'des_matricula'], name='rotina_prod_report__4e782d_idx')],
            },
        ),
    ]
