# Generated by Django 5.2.14 on 2026-06-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotina_bruto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotinadetalhadobrutorecord',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
