# Generated by Django 5.2.14 on 2026-06-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotina_bruto', '0003_truncate_fact_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotinadetalhadobrutorecord',
            name='data_analise',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rotinadetalhadobrutorecord',
            name='data_cadastro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rotinadetalhadobrutorecord',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rotinadetalhadobrutorecord',
            name='data_primeira_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rotinadetalhadobrutorecord',
            name='protocolo',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='rotinamonitorbrutorecord',
            name='data_evento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rotinaprodbrutorecord',
            name='dat_analise',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rotinaprodbrutorecord',
            name='num_tempo_analise',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
