# Generated by Django 5.2.15 on 2026-06-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotina_bruto', '0005_rotina_monitor_tratado'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rotinamonitortratadorecord',
            new_name='rotina_moni_report__498e53_idx',
            old_name='rotina_mon_report__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='rotinamonitortratadorecord',
            new_name='rotina_moni_report__80ddbf_idx',
            old_name='rotina_mon_report__d4e5f6_idx',
        ),
        migrations.AlterField(
            model_name='rotinabrutosynclog',
            name='report_type',
            field=models.CharField(choices=[('detalhado', 'Detalhado bruto'), ('prod', 'Produtividade D-1 bruto'), ('monitor', 'Monitor tratado')], db_index=True, max_length=20),
        ),
    ]
