# Generated by Django 5.2.15 on 2026-07-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotina_bruto', '0007_tratados_rotina_ged'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rotinaconferbuscarecord',
            new_name='rotina_conf_report__ea35e6_idx',
            old_name='rotina_conf_report__a8f1d2_idx',
        ),
        migrations.RenameIndex(
            model_name='rotinaconferbuscarecord',
            new_name='rotina_conf_report__b0a796_idx',
            old_name='rotina_conf_report__b3e4c1_idx',
        ),
        migrations.RenameIndex(
            model_name='rotinageddetalhadotratadorecord',
            new_name='rotina_ged__report__02fed0_idx',
            old_name='rotina_ged__report__c2d5e8_idx',
        ),
        migrations.RenameIndex(
            model_name='rotinageddetalhadotratadorecord',
            new_name='rotina_ged__report__beeff1_idx',
            old_name='rotina_ged__report__f7a9b3_idx',
        ),
        migrations.RenameIndex(
            model_name='rotinagedirregularidadetratadorecord',
            new_name='rotina_ged__report__b26672_idx',
            old_name='rotina_ged__report__d4e6f1_idx',
        ),
        migrations.RenameIndex(
            model_name='rotinagedirregularidadetratadorecord',
            new_name='rotina_ged__report__308283_idx',
            old_name='rotina_ged__report__e8b2c7_idx',
        ),
    ]
