# Generated by Django 5.2.14 on 2026-07-08 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChangeHistorico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Criação'), ('edit', 'Edição'), ('activate', 'Ativação'), ('deactivate', 'Desativação'), ('bulk', 'Ação em massa'), ('password_reset', 'Reset de senha'), ('roles', 'Perfis RBAC')], max_length=32)),
                ('field_name', models.CharField(blank=True, default='', max_length=64)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_changes_made', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'histórico de usuário',
                'verbose_name_plural': 'históricos de usuário',
                'db_table': 'accounts_user_change_historico',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_user', '-created_at'], name='accounts_us_target__65923c_idx')],
            },
        ),
    ]
