# Generated by Django 5.2.14 on 2026-05-27 18:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='nome completo')),
                ('user_lan_id', models.CharField(max_length=64, unique=True, verbose_name='ID de rede')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='data de admissão')),
                ('time_tracking_id', models.CharField(blank=True, max_length=64, verbose_name='ID ponto')),
                ('oracle_id', models.CharField(blank=True, max_length=64, verbose_name='ID Oracle')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('ON_LEAVE', 'Afastado'), ('TERMINATED', 'Desligado')], default='ACTIVE', max_length=32, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'colaborador',
                'verbose_name_plural': 'colaboradores',
                'db_table': 'agent',
            },
        ),
        migrations.CreateModel(
            name='AgentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='localização')),
                ('team', models.CharField(blank=True, max_length=255, verbose_name='time')),
                ('job_title', models.CharField(blank=True, max_length=255, verbose_name='cargo')),
                ('journey', models.CharField(blank=True, max_length=128, verbose_name='jornada')),
                ('band', models.CharField(blank=True, max_length=64, verbose_name='faixa')),
                ('inss_type', models.CharField(blank=True, max_length=64, verbose_name='tipo INSS')),
                ('external_movement_type', models.CharField(blank=True, max_length=128, verbose_name='tipo movimentação externa')),
                ('start_date', models.DateField(verbose_name='data início')),
                ('final_date', models.DateField(blank=True, null=True, verbose_name='data fim')),
                ('productivity_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='desconto produtividade')),
                ('pcd', models.BooleanField(default=False, verbose_name='PCD')),
                ('jira', models.BooleanField(default=False, verbose_name='Jira')),
                ('formalization', models.BooleanField(default=False, verbose_name='formalização')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workforce.agent')),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_histories', to='workforce.agent')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_histories', to='workforce.agent')),
            ],
            options={
                'verbose_name': 'histórico do colaborador',
                'verbose_name_plural': 'históricos dos colaboradores',
                'db_table': 'agent_history',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='workforce.agent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de usuário',
                'verbose_name_plural': 'perfis de usuário',
                'db_table': 'user_profile',
            },
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['active', 'status'], name='agent_active_2265d0_idx'),
        ),
        migrations.AddIndex(
            model_name='agenthistory',
            index=models.Index(fields=['agent', '-start_date'], name='agent_histo_agent_i_b9e62b_idx'),
        ),
        migrations.AddIndex(
            model_name='agenthistory',
            index=models.Index(fields=['agent', 'active'], name='agent_histo_agent_i_4a8a27_idx'),
        ),
        migrations.AddConstraint(
            model_name='agenthistory',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('final_date__isnull', True)), fields=('agent',), name='unique_active_open_history_per_agent'),
        ),
    ]
