# Generated by Django 5.2.15 on 2026-06-17 17:59
# Generated by Django 5.1.15 on 2026-06-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0006_remove_agent_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agent',
            new_name='agent_active_c8098c_idx',
            old_name='agent_active_idx',
        ),
    ]
