# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workforce", "0007_rename_agent_active_idx_agent_active_c8098c_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="jira_api_token",
            field=models.CharField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="token API Jira",
            ),
        ),
    ]
