# Generated by Django 5.2.15 on 2026-07-21 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0010_cyclechangeaudit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cyclechangeaudit',
            new_name='cycle_chang_agent_i_b2e649_idx',
            old_name='cycle_chang_agent_i_7d2a1c_idx',
        ),
    ]
