# Generated by Django 5.2.15 on 2026-07-30 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_sla', '0006_etapagap_etapa_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='etapagap',
            new_name='controle_sl_cod_cli_e8da12_idx',
            old_name='controle_sl_cod_cli_7a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='etapagap',
            new_name='controle_sl_last_se_581fbd_idx',
            old_name='controle_sl_last_se_8d3e4f_idx',
        ),
        migrations.RenameIndex(
            model_name='etapagap',
            new_name='controle_sl_situaca_351625_idx',
            old_name='controle_sl_situaca_7c3d4e_idx',
        ),
        migrations.RenameIndex(
            model_name='slabreach',
            new_name='controle_sl_cod_cli_574bbc_idx',
            old_name='controle_sl_cod_cli_wf_idx',
        ),
        migrations.RenameIndex(
            model_name='slabreach',
            new_name='controle_sl_last_se_c8390e_idx',
            old_name='controle_sl_last_se_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='slabreach',
            new_name='controle_sl_critici_11954d_idx',
            old_name='controle_sl_crit_pct_idx',
        ),
        migrations.RenameIndex(
            model_name='slabreach',
            new_name='controle_sl_dat_reg_25aa83_idx',
            old_name='controle_sl_dat_reg_9a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='slabreachhistorico',
            new_name='controle_sl_cod_cli_e69424_idx',
            old_name='controle_sl_cod_cli_hist1_idx',
        ),
        migrations.RenameIndex(
            model_name='slabreachhistorico',
            new_name='controle_sl_dat_reg_a386a0_idx',
            old_name='controle_sl_dat_reg_hist2_idx',
        ),
        migrations.RenameIndex(
            model_name='slabreachhistorico',
            new_name='controle_sl_first_d_e5181b_idx',
            old_name='controle_sl_first_d_hist3_idx',
        ),
        migrations.RenameIndex(
            model_name='slabreachhistorico',
            new_name='controle_sl_last_se_0ee370_idx',
            old_name='controle_sl_last_se_hist4_idx',
        ),
    ]
