# Generated by Django 5.2.15 on 2026-07-17 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutividadeCaseConsolidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_mes', models.CharField(db_index=True, max_length=16)),
                ('protocolo_destino', models.CharField(db_index=True, max_length=128)),
                ('cliente_origem', models.CharField(blank=True, default='', max_length=255)),
                ('workflow_origem', models.CharField(blank=True, default='', max_length=255)),
                ('nh_origem', models.CharField(blank=True, default='', max_length=64)),
                ('usuario_origem', models.CharField(blank=True, default='', max_length=128)),
                ('protocolo_origem', models.CharField(blank=True, default='', max_length=128)),
                ('cpf', models.CharField(blank=True, default='', max_length=32)),
                ('contrato', models.CharField(blank=True, default='', max_length=128)),
                ('cadastro_origem_at', models.DateTimeField(blank=True, null=True)),
                ('conclusao_origem_at', models.DateTimeField(blank=True, null=True)),
                ('resultado_origem', models.CharField(blank=True, default='', max_length=128)),
                ('status_origem', models.CharField(blank=True, default='', max_length=64)),
                ('tipo_conclusao_origem', models.CharField(blank=True, default='', max_length=32)),
                ('matricula_origem', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('alertas_origem', models.TextField(blank=True, default='')),
                ('cliente_destino', models.CharField(blank=True, default='', max_length=128)),
                ('workflow_destino', models.CharField(blank=True, default='', max_length=128)),
                ('cadastro_destino_at', models.DateTimeField(blank=True, null=True)),
                ('inspecao_at', models.DateTimeField(blank=True, null=True)),
                ('conclusao_destino_at', models.DateTimeField(blank=True, null=True)),
                ('tempo_analise_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('resultado_destino', models.CharField(blank=True, default='', max_length=128)),
                ('status_destino', models.CharField(blank=True, default='', max_length=64)),
                ('tipo_conclusao_destino', models.CharField(blank=True, default='', max_length=32)),
                ('matricula_destino', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('alertas_destino', models.TextField(blank=True, default='')),
                ('source_file', models.CharField(blank=True, default='', max_length=1024)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'produtividade_case_consolidado',
                'ordering': ['-conclusao_destino_at', 'protocolo_destino'],
                'indexes': [models.Index(fields=['periodo_mes', 'matricula_destino'], name='prod_case_cons_mes_mat')],
                'constraints': [models.UniqueConstraint(fields=('periodo_mes', 'protocolo_destino'), name='prod_case_cons_periodo_prot_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ProdutividadeCaseHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_mes', models.CharField(db_index=True, max_length=16)),
                ('matricula', models.CharField(db_index=True, max_length=64)),
                ('hora', models.PositiveSmallIntegerField()),
                ('qtd', models.PositiveIntegerField(default=0)),
                ('source_file', models.CharField(blank=True, default='', max_length=1024)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'produtividade_case_hora',
                'ordering': ['periodo_mes', 'matricula', 'hora'],
                'constraints': [models.UniqueConstraint(fields=('periodo_mes', 'matricula', 'hora'), name='prod_case_hora_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ProdutividadeCaseSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('consolidado', 'Consolidado'), ('prod_hora', 'Produtividade por hora'), ('tempo_logado', 'Tempo logado')], db_index=True, default='consolidado', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('trigger_source', models.CharField(choices=[('user', 'Usuário (portal/manual)'), ('system', 'Sistema (automático)')], db_index=True, default='user', max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('source_file', models.CharField(blank=True, default='', max_length=1024)),
                ('source_mtime', models.FloatField(blank=True, null=True)),
                ('source_size', models.BigIntegerField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('periodo_mes', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'produtividade_case_sync_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProdutividadeCaseTempoLogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_mes', models.CharField(db_index=True, max_length=16)),
                ('matricula', models.CharField(db_index=True, max_length=64)),
                ('dia', models.DateField(db_index=True)),
                ('diff_segundos', models.BigIntegerField(default=0)),
                ('source_file', models.CharField(blank=True, default='', max_length=1024)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'produtividade_case_tempo_logado',
                'ordering': ['periodo_mes', 'matricula', 'dia'],
                'constraints': [models.UniqueConstraint(fields=('periodo_mes', 'matricula', 'dia'), name='prod_case_tempo_uniq')],
            },
        ),
    ]
