# Generated by Django 5.2.15 on 2026-07-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade_case', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProdutividadeCaseConsolidado',
        ),
        migrations.DeleteModel(
            name='ProdutividadeCaseHora',
        ),
        migrations.DeleteModel(
            name='ProdutividadeCaseTempoLogado',
        ),
        migrations.AlterField(
            model_name='produtividadecasesynclog',
            name='report_type',
            field=models.CharField(choices=[('consolidado', 'Consolidado'), ('prod_hora', 'Produtividade por hora'), ('tempo_logado', 'Tempo logado (só Excel)')], db_index=True, default='consolidado', max_length=32),
        ),
    ]
