# Generated by Django 5.2.15 on 2026-07-30 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade_case', '0009_fila_aging_and_tempo_stats'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='caseconsolidadodailyagg',
            new_name='case_manage_periodo_677477_idx',
            old_name='case_manage_periodo_8g9h0i_idx',
        ),
        migrations.RenameIndex(
            model_name='caseconsolidadodailyagg',
            new_name='case_manage_dimensi_2e5280_idx',
            old_name='case_manage_dimensi_1j2k3l_idx',
        ),
        migrations.RenameIndex(
            model_name='caseconsolidadofact',
            new_name='case_manage_periodo_aa79d7_idx',
            old_name='case_manage_periodo_wf_idx',
        ),
        migrations.RenameIndex(
            model_name='caseconsolidadofact',
            new_name='case_manage_periodo_acd1db_idx',
            old_name='case_manage_periodo_md_idx',
        ),
        migrations.RenameIndex(
            model_name='caseconsolidadofact',
            new_name='case_manage_periodo_78a0e5_idx',
            old_name='case_manage_periodo_cd_idx',
        ),
        migrations.RenameIndex(
            model_name='caseconsolidadofact',
            new_name='case_manage_periodo_8b9763_idx',
            old_name='case_manage_periodo_cdest_idx',
        ),
        migrations.RenameIndex(
            model_name='caseconsolidadosnapshot',
            new_name='case_manage_periodo_447a31_idx',
            old_name='case_manage_periodo_7a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='caseconsolidadosnapshot',
            new_name='case_manage_success_382caf_idx',
            old_name='case_manage_success_3d4e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='casefilaagg',
            new_name='case_manage_snapsho_553e23_idx',
            old_name='case_manage_snapsho_8a1d2e_idx',
        ),
        migrations.RenameIndex(
            model_name='casefilasampleitem',
            new_name='case_manage_snapsho_f7042f_idx',
            old_name='case_manage_snap_idade_idx',
        ),
        migrations.RenameIndex(
            model_name='casefilasnapshot',
            new_name='case_manage_success_9c144f_idx',
            old_name='case_manage_success_2f0b1c_idx',
        ),
    ]
