from django.urls import path

from apps.auditoria.views_auditoria_dashboard import AuditoriaDashboardView
from apps.auditoria.views import (
    AuditoriaCatalogConfigDetailView,
    AuditoriaCatalogConfigBulkUpdateView,
    AuditoriaCatalogConfigImportView,
    AuditoriaCatalogConfigImportPreviewView,
    AuditoriaCatalogConfigListView,
    AuditoriaCatalogConfigMetaView,
    AuditoriaCatalogsView,
    AuditoriaFalhaCreateView,
    AuditoriaFalhaAlteracoesView,
    AuditoriaFalhaAgentOptionsView,
    AuditoriaFalhaRealizadasView,
    AuditoriaMotivoFalhaConfigDetailView,
    AuditoriaMotivoFalhaConfigBulkUpdateView,
    AuditoriaMotivoFalhaConfigImportView,
    AuditoriaMotivoFalhaConfigImportPreviewView,
    AuditoriaMotivoFalhaConfigListView,
    QualidadeConfiguracaoAlteracaoUndoView,
    QualidadeConfiguracaoAlteracoesView,
)
from apps.auditoria.views_atividades import (
    AuditoriaAtividadeDetailView,
    AuditoriaAtividadeFalhaDetailView,
    AuditoriaAtividadeFalhasBatchView,
    AuditoriaAtividadeFalhasView,
    AuditoriaAtividadeFinalizarView,
    AuditoriaAtividadeFromBrflowView,
    AuditoriaAtividadeImportConfirmView,
    AuditoriaAtividadeImportValidateView,
    AuditoriaAtividadeListView,
    AuditoriaAtividadeProtocoloAnaliseView,
    AuditoriaAtividadeProtocoloDetailView,
    AuditoriaAtividadeProtocoloListView,
    AuditoriaAtividadeResponsaveisView,
    AuditoriaAtividadeRetornoExportView,
    AuditoriaAtividadeTrilhaBrflowView,
    AuditoriaComplianceImportConfirmView,
    AuditoriaComplianceImportValidateView,
    AuditoriaReinspecaoImportConfirmView,
    AuditoriaReinspecaoImportValidateView,
)
from apps.auditoria.views_auditoria_compliance_fila import (
    AuditoriaComplianceAuditorFilaView,
    AuditoriaComplianceClaimView,
    AuditoriaComplianceConcluirAnaliseView,
    AuditoriaComplianceControleAuditoresView,
    AuditoriaComplianceDirecionarView,
    AuditoriaComplianceDistribuirView,
    AuditoriaComplianceFalhaDetailView,
    AuditoriaComplianceFalhasBulkDeleteView,
    AuditoriaComplianceFalhasView,
    AuditoriaComplianceHistoricoView,
    AuditoriaComplianceIniciarAnaliseView,
    AuditoriaComplianceMinhaFilaView,
    AuditoriaCompliancePresenceAdminView,
    AuditoriaCompliancePresenceMeView,
    AuditoriaComplianceRemoverDirecionadoView,
    AuditoriaComplianceRemoverFilaControleView,
    AuditoriaComplianceRedistribuirFilaView,
)
from apps.auditoria.views_reinspecao_fila import (
    AuditoriaReinspecaoFalhaDetailView,
    AuditoriaReinspecaoFalhasBulkDeleteView,
    AuditoriaReinspecaoFalhasView,
    ReinspecaoAuditorFilaView,
    ReinspecaoClaimView,
    ReinspecaoConcluirAnaliseView,
    ReinspecaoControleAuditoresView,
    ReinspecaoDirecionarView,
    ReinspecaoDistribuirView,
    ReinspecaoHistoricoView,
    ReinspecaoIniciarAnaliseView,
    ReinspecaoMinhaFilaView,
    ReinspecaoPresenceAdminView,
    ReinspecaoPresenceMeView,
    ReinspecaoRemoverDirecionadoView,
    ReinspecaoRemoverFilaControleView,
    ReinspecaoRedistribuirFilaView,
)
from apps.auditoria.views_reinspecao_ged_divergencias import (
    ReinspecaoGedDivergenciaListView,
    ReinspecaoGedDivergenciaReconhecerView,
    ReinspecaoGedDivergenciaResumoView,
)
from apps.auditoria.views_reinspecao_distribuicao import ReinspecaoGedPortalExportView
from apps.auditoria.views_falha_validacoes import (
    AuditoriaFalhaValidacaoAgentOptionsView,
    AuditoriaFalhaValidacaoConformeView,
    AuditoriaFalhaValidacaoDetailView,
    AuditoriaFalhaValidacaoListView,
    AuditoriaFalhaValidacaoNaoConformeView,
)
from apps.auditoria.views_controles import (
    AuditoriaControleDetailView,
    AuditoriaControleListView,
    AuditoriaControleMetaView,
)

urlpatterns = [
    path("dashboard/", AuditoriaDashboardView.as_view(), name="auditoria-dashboard"),
    path("catalogs/", AuditoriaCatalogsView.as_view(), name="auditoria-catalogs"),
    path("falhas/", AuditoriaFalhaCreateView.as_view(), name="auditoria-falhas-create"),
    path(
        "falhas/validacoes/",
        AuditoriaFalhaValidacaoListView.as_view(),
        name="auditoria-falhas-validacoes-list",
    ),
    path(
        "falhas/validacoes/agentes/",
        AuditoriaFalhaValidacaoAgentOptionsView.as_view(),
        name="auditoria-falhas-validacoes-agent-options",
    ),
    path(
        "falhas/validacoes/<int:pk>/",
        AuditoriaFalhaValidacaoDetailView.as_view(),
        name="auditoria-falhas-validacoes-detail",
    ),
    path(
        "falhas/validacoes/<int:pk>/conforme/",
        AuditoriaFalhaValidacaoConformeView.as_view(),
        name="auditoria-falhas-validacoes-conforme",
    ),
    path(
        "falhas/validacoes/<int:pk>/nao-conforme/",
        AuditoriaFalhaValidacaoNaoConformeView.as_view(),
        name="auditoria-falhas-validacoes-nao-conforme",
    ),
    path(
        "falhas/agentes/",
        AuditoriaFalhaAgentOptionsView.as_view(),
        name="auditoria-falhas-agent-options",
    ),
    path(
        "falhas/<int:pk>/alteracoes/",
        AuditoriaFalhaAlteracoesView.as_view(),
        name="auditoria-falhas-alteracoes",
    ),
    path(
        "falhas/realizadas/",
        AuditoriaFalhaRealizadasView.as_view(),
        name="auditoria-falhas-realizadas",
    ),
    path(
        "atividades/importacao/validar/",
        AuditoriaAtividadeImportValidateView.as_view(),
        name="auditoria-atividades-import-validate",
    ),
    path(
        "atividades/importacao/confirmar/",
        AuditoriaAtividadeImportConfirmView.as_view(),
        name="auditoria-atividades-import-confirm",
    ),
    path(
        "compliance/importacao/validar/",
        AuditoriaComplianceImportValidateView.as_view(),
        name="auditoria-compliance-import-validate",
    ),
    path(
        "compliance/importacao/confirmar/",
        AuditoriaComplianceImportConfirmView.as_view(),
        name="auditoria-compliance-import-confirm",
    ),
    path(
        "compliance/falhas/",
        AuditoriaComplianceFalhasView.as_view(),
        name="auditoria-compliance-falhas",
    ),
    path(
        "compliance/falhas/bulk-delete/",
        AuditoriaComplianceFalhasBulkDeleteView.as_view(),
        name="auditoria-compliance-falhas-bulk-delete",
    ),
    path(
        "compliance/falhas/<int:pk>/",
        AuditoriaComplianceFalhaDetailView.as_view(),
        name="auditoria-compliance-falha-detail",
    ),
    path(
        "compliance/presence/me/",
        AuditoriaCompliancePresenceMeView.as_view(),
        name="auditoria-compliance-presence-me",
    ),
    path(
        "compliance/presence/<uuid:user_id>/",
        AuditoriaCompliancePresenceAdminView.as_view(),
        name="auditoria-compliance-presence-admin",
    ),
    path(
        "compliance/distribuir/",
        AuditoriaComplianceDistribuirView.as_view(),
        name="auditoria-compliance-distribuir",
    ),
    path(
        "compliance/direcionar/",
        AuditoriaComplianceDirecionarView.as_view(),
        name="auditoria-compliance-direcionar",
    ),
    path(
        "compliance/fila/me/",
        AuditoriaComplianceMinhaFilaView.as_view(),
        name="auditoria-compliance-fila-me",
    ),
    path(
        "compliance/fila/me/claim/",
        AuditoriaComplianceClaimView.as_view(),
        name="auditoria-compliance-fila-claim",
    ),
    path(
        "compliance/fila/me/<int:pk>/remover/",
        AuditoriaComplianceRemoverDirecionadoView.as_view(),
        name="auditoria-compliance-fila-remover-direcionado",
    ),
    path(
        "compliance/fila/<uuid:user_id>/",
        AuditoriaComplianceAuditorFilaView.as_view(),
        name="auditoria-compliance-fila-auditor",
    ),
    path(
        "compliance/falhas/<int:pk>/iniciar/",
        AuditoriaComplianceIniciarAnaliseView.as_view(),
        name="auditoria-compliance-iniciar",
    ),
    path(
        "compliance/falhas/<int:pk>/concluir/",
        AuditoriaComplianceConcluirAnaliseView.as_view(),
        name="auditoria-compliance-concluir",
    ),
    path(
        "compliance/controle/auditores/",
        AuditoriaComplianceControleAuditoresView.as_view(),
        name="auditoria-compliance-controle",
    ),
    path(
        "compliance/fila/<uuid:user_id>/redistribuir/",
        AuditoriaComplianceRedistribuirFilaView.as_view(),
        name="auditoria-compliance-redistribuir",
    ),
    path(
        "compliance/fila/<uuid:user_id>/remover/",
        AuditoriaComplianceRemoverFilaControleView.as_view(),
        name="auditoria-compliance-fila-remover-controle",
    ),
    path(
        "compliance/historico/",
        AuditoriaComplianceHistoricoView.as_view(),
        name="auditoria-compliance-historico",
    ),
    path(
        "reinspecao/importacao/validar/",
        AuditoriaReinspecaoImportValidateView.as_view(),
        name="auditoria-reinspecao-import-validate",
    ),
    path(
        "reinspecao/importacao/confirmar/",
        AuditoriaReinspecaoImportConfirmView.as_view(),
        name="auditoria-reinspecao-import-confirm",
    ),
    path(
        "reinspecao/falhas/",
        AuditoriaReinspecaoFalhasView.as_view(),
        name="auditoria-reinspecao-falhas",
    ),
    path(
        "reinspecao/falhas/bulk-delete/",
        AuditoriaReinspecaoFalhasBulkDeleteView.as_view(),
        name="auditoria-reinspecao-falhas-bulk-delete",
    ),
    path(
        "reinspecao/falhas/<int:pk>/",
        AuditoriaReinspecaoFalhaDetailView.as_view(),
        name="auditoria-reinspecao-falha-detail",
    ),
    path(
        "reinspecao/presence/me/",
        ReinspecaoPresenceMeView.as_view(),
        name="auditoria-reinspecao-presence-me",
    ),
    path(
        "reinspecao/presence/<uuid:user_id>/",
        ReinspecaoPresenceAdminView.as_view(),
        name="auditoria-reinspecao-presence-admin",
    ),
    path(
        "reinspecao/distribuir/",
        ReinspecaoDistribuirView.as_view(),
        name="auditoria-reinspecao-distribuir",
    ),
    path(
        "reinspecao/direcionar/",
        ReinspecaoDirecionarView.as_view(),
        name="auditoria-reinspecao-direcionar",
    ),
    path(
        "reinspecao/fila/me/",
        ReinspecaoMinhaFilaView.as_view(),
        name="auditoria-reinspecao-fila-me",
    ),
    path(
        "reinspecao/fila/me/claim/",
        ReinspecaoClaimView.as_view(),
        name="auditoria-reinspecao-fila-claim",
    ),
    path(
        "reinspecao/fila/me/<int:pk>/remover/",
        ReinspecaoRemoverDirecionadoView.as_view(),
        name="auditoria-reinspecao-fila-remover-direcionado",
    ),
    path(
        "reinspecao/fila/<uuid:user_id>/",
        ReinspecaoAuditorFilaView.as_view(),
        name="auditoria-reinspecao-fila-auditor",
    ),
    path(
        "reinspecao/falhas/<int:pk>/iniciar/",
        ReinspecaoIniciarAnaliseView.as_view(),
        name="auditoria-reinspecao-iniciar",
    ),
    path(
        "reinspecao/falhas/<int:pk>/concluir/",
        ReinspecaoConcluirAnaliseView.as_view(),
        name="auditoria-reinspecao-concluir",
    ),
    path(
        "reinspecao/controle/auditores/",
        ReinspecaoControleAuditoresView.as_view(),
        name="auditoria-reinspecao-controle",
    ),
    path(
        "reinspecao/fila/<uuid:user_id>/redistribuir/",
        ReinspecaoRedistribuirFilaView.as_view(),
        name="auditoria-reinspecao-redistribuir",
    ),
    path(
        "reinspecao/fila/<uuid:user_id>/remover/",
        ReinspecaoRemoverFilaControleView.as_view(),
        name="auditoria-reinspecao-fila-remover-controle",
    ),
    path(
        "reinspecao/historico/",
        ReinspecaoHistoricoView.as_view(),
        name="auditoria-reinspecao-historico",
    ),
    path(
        "reinspecao/ged-divergencias/resumo/",
        ReinspecaoGedDivergenciaResumoView.as_view(),
        name="auditoria-reinspecao-ged-divergencias-resumo",
    ),
    path(
        "reinspecao/ged-divergencias/",
        ReinspecaoGedDivergenciaListView.as_view(),
        name="auditoria-reinspecao-ged-divergencias-list",
    ),
    path(
        "reinspecao/ged-divergencias/<int:pk>/reconhecer/",
        ReinspecaoGedDivergenciaReconhecerView.as_view(),
        name="auditoria-reinspecao-ged-divergencias-reconhecer",
    ),
    path(
        "reinspecao/ged-portal-export/",
        ReinspecaoGedPortalExportView.as_view(),
        name="auditoria-reinspecao-ged-portal-export",
    ),
    path(
        "compliance/ged-portal-export/",
        ReinspecaoGedPortalExportView.as_view(),
        name="auditoria-compliance-ged-portal-export",
    ),
    path(
        "atividades/responsaveis/",
        AuditoriaAtividadeResponsaveisView.as_view(),
        name="auditoria-atividades-responsaveis",
    ),
    path("atividades/", AuditoriaAtividadeListView.as_view(), name="auditoria-atividades-list"),
    path(
        "atividades/from-brflow/",
        AuditoriaAtividadeFromBrflowView.as_view(),
        name="auditoria-atividades-from-brflow",
    ),
    path("atividades/<int:pk>/", AuditoriaAtividadeDetailView.as_view(), name="auditoria-atividades-detail"),
    path(
        "atividades/<int:pk>/falhas/",
        AuditoriaAtividadeFalhasView.as_view(),
        name="auditoria-atividades-falhas",
    ),
    path(
        "atividades/<int:pk>/falhas/<int:falha_pk>/",
        AuditoriaAtividadeFalhaDetailView.as_view(),
        name="auditoria-atividades-falha-detail",
    ),
    path(
        "atividades/<int:pk>/falhas/lote/",
        AuditoriaAtividadeFalhasBatchView.as_view(),
        name="auditoria-atividades-falhas-batch",
    ),
    path(
        "atividades/<int:pk>/trilha-brflow/",
        AuditoriaAtividadeTrilhaBrflowView.as_view(),
        name="auditoria-atividades-trilha-brflow",
    ),
    path(
        "atividades/<int:pk>/finalizar/",
        AuditoriaAtividadeFinalizarView.as_view(),
        name="auditoria-atividades-finalizar",
    ),
    path(
        "atividades/<int:pk>/retorno.xlsx",
        AuditoriaAtividadeRetornoExportView.as_view(),
        name="auditoria-atividades-retorno-export",
    ),
    path(
        "atividades/<int:pk>/protocolos/",
        AuditoriaAtividadeProtocoloListView.as_view(),
        name="auditoria-atividades-protocolos",
    ),
    path(
        "atividades/<int:pk>/protocolos/<int:protocolo_pk>/",
        AuditoriaAtividadeProtocoloDetailView.as_view(),
        name="auditoria-atividades-protocolo-detail",
    ),
    path(
        "atividades/<int:pk>/protocolos/<int:protocolo_pk>/analise/",
        AuditoriaAtividadeProtocoloAnaliseView.as_view(),
        name="auditoria-atividades-protocolo-analise",
    ),
    path(
        "controles/<str:tipo>/meta/",
        AuditoriaControleMetaView.as_view(),
        name="auditoria-controles-meta",
    ),
    path(
        "controles/<str:tipo>/",
        AuditoriaControleListView.as_view(),
        name="auditoria-controles-list",
    ),
    path(
        "controles/<str:tipo>/<int:pk>/",
        AuditoriaControleDetailView.as_view(),
        name="auditoria-controles-detail",
    ),
    path("config/meta/", AuditoriaCatalogConfigMetaView.as_view(), name="auditoria-config-meta"),
    path(
        "config/alteracoes/",
        QualidadeConfiguracaoAlteracoesView.as_view(),
        name="auditoria-config-alteracoes",
    ),
    path(
        "config/alteracoes/<int:pk>/desfazer/",
        QualidadeConfiguracaoAlteracaoUndoView.as_view(),
        name="auditoria-config-alteracoes-desfazer",
    ),
    path(
        "config/cenarios/",
        AuditoriaMotivoFalhaConfigListView.as_view(),
        name="auditoria-config-cenarios-list",
    ),
    path(
        "config/cenarios/<int:pk>/",
        AuditoriaMotivoFalhaConfigDetailView.as_view(),
        name="auditoria-config-cenarios-detail",
    ),
    path(
        "config/cenarios/importar/",
        AuditoriaMotivoFalhaConfigImportView.as_view(),
        name="auditoria-config-cenarios-importar",
    ),
    path(
        "config/cenarios/importar/pre-visualizar/",
        AuditoriaMotivoFalhaConfigImportPreviewView.as_view(),
        name="auditoria-config-cenarios-importar-preview",
    ),
    path(
        "config/cenarios/alteracao-em-massa/",
        AuditoriaMotivoFalhaConfigBulkUpdateView.as_view(),
        name="auditoria-config-cenarios-bulk-update",
    ),
    # Compatibilidade com rota antiga
    path(
        "config/motivos-falha/",
        AuditoriaMotivoFalhaConfigListView.as_view(),
        name="auditoria-config-motivos-falha-list",
    ),
    path(
        "config/motivos-falha/<int:pk>/",
        AuditoriaMotivoFalhaConfigDetailView.as_view(),
        name="auditoria-config-motivos-falha-detail",
    ),
    path(
        "config/<str:catalog>/",
        AuditoriaCatalogConfigListView.as_view(),
        name="auditoria-config-list",
    ),
    path(
        "config/<str:catalog>/importar/",
        AuditoriaCatalogConfigImportView.as_view(),
        name="auditoria-config-importar",
    ),
    path(
        "config/<str:catalog>/importar/pre-visualizar/",
        AuditoriaCatalogConfigImportPreviewView.as_view(),
        name="auditoria-config-importar-preview",
    ),
    path(
        "config/<str:catalog>/alteracao-em-massa/",
        AuditoriaCatalogConfigBulkUpdateView.as_view(),
        name="auditoria-config-bulk-update",
    ),
    path(
        "config/<str:catalog>/<int:pk>/",
        AuditoriaCatalogConfigDetailView.as_view(),
        name="auditoria-config-detail",
    ),
]
