"""Stacks de permissão RBAC para endpoints Escala Flex."""

from __future__ import annotations

from rest_framework.permissions import IsAuthenticated

from apps.access import registry as R
from apps.access.permission_classes import portal_perm, portal_perm_any

IsAuth = IsAuthenticated

MONITORING_VIEW = [IsAuth, portal_perm(R.PLANEJAMENTO_MONITORAMENTO_VIEW)]
MONITORING_DASHBOARDS = [IsAuth, portal_perm(R.PLANEJAMENTO_MONITORAMENTO_DASHBOARDS_VIEW)]
ESCALAS_VIEW = [IsAuth, portal_perm(R.PLANEJAMENTO_ESCALAS_VIEW)]
ESCALAS_CONSULTA = [
    IsAuth,
    portal_perm_any(
        R.PLANEJAMENTO_ESCALAS_VIEW,
        R.PLANEJAMENTO_MONITORAMENTO_VIEW,
        R.OPERACAO_JORNADA_ESCALA_VIEW,
    ),
]
ESCALAS_IMPORT = [IsAuth, portal_perm(R.PLANEJAMENTO_ESCALAS_IMPORT)]
ESCALAS_GENERATE = [IsAuth, portal_perm(R.PLANEJAMENTO_ESCALAS_GENERATE)]
ESCALAS_PUBLISH = [IsAuth, portal_perm(R.PLANEJAMENTO_ESCALAS_PUBLISH)]
OCORRENCIAS_PLAN_VIEW = [IsAuth, portal_perm(R.PLANEJAMENTO_OCORRENCIAS_VIEW)]
OCORRENCIAS_PLAN_APPROVE = [IsAuth, portal_perm(R.PLANEJAMENTO_OCORRENCIAS_APPROVE)]
OCORRENCIAS_PLAN_EDIT = [IsAuth, portal_perm(R.PLANEJAMENTO_OCORRENCIAS_EDIT)]
TROCAS_PLAN = [IsAuth, portal_perm(R.PLANEJAMENTO_TROCAS_VIEW)]
TROCAS_PLAN_APPROVE = [IsAuth, portal_perm(R.PLANEJAMENTO_TROCAS_APPROVE)]
OPERACAO_PAINEL = [IsAuth, portal_perm(R.OPERACAO_JORNADA_PAINEL_VIEW)]
OPERACAO_ESCALA = [IsAuth, portal_perm(R.OPERACAO_JORNADA_ESCALA_VIEW)]
OPERACAO_HISTORICO = [IsAuth, portal_perm(R.OPERACAO_HISTORICO_VIEW)]
OPERACAO_HISTORICO_APPROVE = [IsAuth, portal_perm(R.OPERACAO_HISTORICO_APPROVE)]
OPERACAO_STATUS = [IsAuth, portal_perm(R.OPERACAO_STATUS_VIEW)]
OPERACAO_STATUS_CHANGE = [IsAuth, portal_perm(R.OPERACAO_STATUS_CHANGE)]
OCORRENCIAS_OP_VIEW = [IsAuth, portal_perm(R.OPERACAO_OCORRENCIAS_VIEW)]
OCORRENCIAS_OP_CREATE = [IsAuth, portal_perm(R.OPERACAO_OCORRENCIAS_CREATE)]
TROCAS_OP_VIEW = [IsAuth, portal_perm(R.OPERACAO_TROCAS_VIEW)]
TROCAS_OP_CREATE = [IsAuth, portal_perm(R.OPERACAO_TROCAS_CREATE)]
TROCAS_OP_APPROVE_LIDER = [IsAuth, portal_perm(R.OPERACAO_TROCAS_APPROVE_LIDER)]
IMPERSONATE = [IsAuth, portal_perm(R.ADM_ESCALA_IMPERSONATE)]
CONTROLE_JORNADA_ANY = [
    IsAuth,
    portal_perm_any(
        R.OPERACAO_JORNADA_PAINEL_VIEW,
        R.OPERACAO_JORNADA_ESCALA_VIEW,
        R.OPERACAO_HISTORICO_VIEW,
        R.OPERACAO_STATUS_VIEW,
    ),
]
ANY_ESCALA_FLEX_VIEW = [
    IsAuth,
    portal_perm_any(
        R.PLANEJAMENTO_MONITORAMENTO_VIEW,
        R.PLANEJAMENTO_MONITORAMENTO_DASHBOARDS_VIEW,
        R.PLANEJAMENTO_ESCALAS_VIEW,
        R.PLANEJAMENTO_OCORRENCIAS_VIEW,
        R.PLANEJAMENTO_TROCAS_VIEW,
        R.OPERACAO_JORNADA_PAINEL_VIEW,
        R.OPERACAO_JORNADA_ESCALA_VIEW,
        R.OPERACAO_HISTORICO_VIEW,
        R.OPERACAO_STATUS_VIEW,
        R.OPERACAO_OCORRENCIAS_VIEW,
        R.OPERACAO_TROCAS_VIEW,
    ),
]
