from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    ScheduleRequestViewSet,
    break_times_list,
    break_times_stats,
    break_times_update,
    context_view,
    dimensions_view,
    impersonate_clear_view,
    impersonate_view,
    nh_updates_export_view,
    nh_updates_view,
    schedule_today_blocked_batch,
    schedule_today_detail,
    schedule_today_escala_edit,
    schedule_today_kpis,
    schedule_today_list,
    schedule_today_rebuild,
    operational_dashboard_view,
    activity_panel_snapshot_view,
    operational_occurrence_approve,
    operational_occurrence_cancel,
    operational_occurrence_extension_approve,
    operational_occurrence_request_extension,
    operational_occurrence_update,
    operational_occurrences_batch_create,
    operational_occurrences_approve_batch,
    operational_occurrences_request_extension_batch,
    operational_occurrences_list,
    occurrence_type_config_detail,
    occurrence_types_config_view,
    absence_type_config_detail,
    absence_types_config_view,
    agent_schedule_escala_edit,
    status_events_view,
    status_event_history_list,
    status_event_history_filters,
    status_event_approve,
    status_event_approve_batch,
    status_event_related_occurrences,
    status_type_config_detail,
    status_types_config_view,
)
from .planning_views import (
    escala_import_detail_view,
    escala_import_view,
    escala_imports_list_view,
    escala_list_view,
    escala_planning_filter_options_view,
)
from .swap_request_views import (
    swap_request_leader_approve,
    swap_request_plan_approve,
    swap_requests_stats,
    swap_requests_validate,
    swap_requests_view,
)
from .escala_views import escala_consulta_view, escala_detail_view, escala_filter_options_view
from .generation_views import (
    generation_cancel_view,
    generation_config_options_view,
    generation_conflict_resolve_view,
    generation_entry_patch_view,
    generation_preview_view,
    generation_publish_view,
    generation_revalidate_view,
    generation_run_detail_view,
    generation_runs_list_view,
)
from .operational_alert_views import operational_alert_history_view

router = DefaultRouter()
router.register("requests", ScheduleRequestViewSet, basename="ef-request")

urlpatterns = [
    path("context/", context_view, name="ef-context"),
    path("impersonate/", impersonate_view, name="ef-impersonate"),
    path("impersonate/clear/", impersonate_clear_view, name="ef-impersonate-clear"),
    path("schedule/today/", schedule_today_list, name="ef-schedule-today"),
    path("schedule/today/kpis/", schedule_today_kpis, name="ef-schedule-kpis"),
    path("monitoring/dashboard/", operational_dashboard_view, name="ef-operational-dashboard"),
    path(
        "monitoring/alerts/history/",
        operational_alert_history_view,
        name="ef-operational-alert-history",
    ),
    path(
        "monitoring/activity-snapshot/",
        activity_panel_snapshot_view,
        name="ef-activity-panel-snapshot",
    ),
    path("operational-occurrences/", operational_occurrences_list, name="ef-operational-occurrences"),
    path(
        "operational-occurrences/batch/",
        operational_occurrences_batch_create,
        name="ef-operational-occurrences-batch",
    ),
    path(
        "operational-occurrences/approve-batch/",
        operational_occurrences_approve_batch,
        name="ef-operational-occurrences-approve-batch",
    ),
    path(
        "operational-occurrences/extensions/batch/",
        operational_occurrences_request_extension_batch,
        name="ef-operational-occurrences-extension-batch",
    ),
    path(
        "operational-occurrences/<uuid:pk>/approve/",
        operational_occurrence_approve,
        name="ef-operational-occurrence-approve",
    ),
    path(
        "operational-occurrences/<uuid:pk>/cancel/",
        operational_occurrence_cancel,
        name="ef-operational-occurrence-cancel",
    ),
    path(
        "operational-occurrences/<uuid:pk>/extensions/",
        operational_occurrence_request_extension,
        name="ef-operational-occurrence-extension-request",
    ),
    path(
        "operational-occurrences/<uuid:pk>/extensions/<uuid:extension_id>/approve/",
        operational_occurrence_extension_approve,
        name="ef-operational-occurrence-extension-approve",
    ),
    path(
        "operational-occurrences/<uuid:pk>/",
        operational_occurrence_update,
        name="ef-operational-occurrence-update",
    ),
    path("swap-requests/stats/", swap_requests_stats, name="ef-swap-requests-stats"),
    path("swap-requests/validate/", swap_requests_validate, name="ef-swap-requests-validate"),
    path("swap-requests/", swap_requests_view, name="ef-swap-requests"),
    path(
        "swap-requests/<uuid:pk>/approve-leader/",
        swap_request_leader_approve,
        name="ef-swap-request-approve-leader",
    ),
    path(
        "swap-requests/<uuid:pk>/approve-plan/",
        swap_request_plan_approve,
        name="ef-swap-request-approve-plan",
    ),
    path("schedule/today/rebuild/", schedule_today_rebuild, name="ef-schedule-rebuild"),
    path(
        "schedule/today/blocked/",
        schedule_today_blocked_batch,
        name="ef-schedule-blocked",
    ),
    path(
        "schedule/agent-escala/",
        agent_schedule_escala_edit,
        name="ef-schedule-agent-escala",
    ),
    path(
        "schedule/today/<uuid:pk>/escala/",
        schedule_today_escala_edit,
        name="ef-schedule-escala-edit",
    ),
    path(
        "schedule/today/<uuid:pk>/",
        schedule_today_detail,
        name="ef-schedule-detail",
    ),
    path("status-events/", status_events_view, name="ef-status-events"),
    path(
        "status-events/history/",
        status_event_history_list,
        name="ef-status-events-history",
    ),
    path(
        "status-events/history/filters/",
        status_event_history_filters,
        name="ef-status-events-history-filters",
    ),
    path(
        "status-events/approve-batch/",
        status_event_approve_batch,
        name="ef-status-event-approve-batch",
    ),
    path(
        "status-events/<uuid:pk>/related-occurrences/",
        status_event_related_occurrences,
        name="ef-status-event-related-occurrences",
    ),
    path(
        "status-events/<uuid:pk>/approve/",
        status_event_approve,
        name="ef-status-event-approve",
    ),
    path("nh-updates/", nh_updates_view, name="ef-nh-updates"),
    path("nh-updates/export/", nh_updates_export_view, name="ef-nh-export"),
    path("break-times/", break_times_list, name="ef-break-times"),
    path("break-times/stats/", break_times_stats, name="ef-break-times-stats"),
    path("break-times/update/", break_times_update, name="ef-break-times-update"),
    path("dimensions/<str:resource>/", dimensions_view, name="ef-dimensions"),
    path("config/status-types/", status_types_config_view, name="ef-config-status-types"),
    path(
        "config/status-types/<int:pk>/",
        status_type_config_detail,
        name="ef-config-status-type-detail",
    ),
    path(
        "config/occurrence-types/",
        occurrence_types_config_view,
        name="ef-config-occurrence-types",
    ),
    path(
        "config/occurrence-types/<int:pk>/",
        occurrence_type_config_detail,
        name="ef-config-occurrence-type-detail",
    ),
    path(
        "config/absence-types/",
        absence_types_config_view,
        name="ef-config-absence-types",
    ),
    path(
        "config/absence-types/<int:pk>/",
        absence_type_config_detail,
        name="ef-config-absence-type-detail",
    ),
    path("planejamento/import/", escala_import_view, name="ef-planning-import"),
    path("planejamento/imports/", escala_imports_list_view, name="ef-planning-imports"),
    path(
        "planejamento/imports/<uuid:batch_id>/",
        escala_import_detail_view,
        name="ef-planning-import-detail",
    ),
    path("planejamento/escala/", escala_list_view, name="ef-planning-escala"),
    path(
        "planejamento/escala/filters/",
        escala_planning_filter_options_view,
        name="ef-planning-escala-filters",
    ),
    path(
        "planejamento/generation/config-options/",
        generation_config_options_view,
        name="ef-generation-config-options",
    ),
    path(
        "planejamento/generation/preview/",
        generation_preview_view,
        name="ef-generation-preview",
    ),
    path(
        "planejamento/generation/runs/",
        generation_runs_list_view,
        name="ef-generation-runs",
    ),
    path(
        "planejamento/generation/runs/<uuid:run_id>/",
        generation_run_detail_view,
        name="ef-generation-run-detail",
    ),
    path(
        "planejamento/generation/runs/<uuid:run_id>/entries/<uuid:entry_id>/",
        generation_entry_patch_view,
        name="ef-generation-entry-patch",
    ),
    path(
        "planejamento/generation/runs/<uuid:run_id>/revalidate/",
        generation_revalidate_view,
        name="ef-generation-revalidate",
    ),
    path(
        "planejamento/generation/runs/<uuid:run_id>/publish/",
        generation_publish_view,
        name="ef-generation-publish",
    ),
    path(
        "planejamento/generation/runs/<uuid:run_id>/cancel/",
        generation_cancel_view,
        name="ef-generation-cancel",
    ),
    path(
        "planejamento/generation/runs/<uuid:run_id>/conflicts/<uuid:conflict_id>/resolve/",
        generation_conflict_resolve_view,
        name="ef-generation-conflict-resolve",
    ),
    path("escala/", escala_consulta_view, name="ef-escala-consulta"),
    path("escala/<uuid:pk>/", escala_detail_view, name="ef-escala-detail"),
    path("escala/filters/", escala_filter_options_view, name="ef-escala-filters"),
    path("", include(router.urls)),
]
