# Generated by Django 5.2.15 on 2026-07-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0020_atividade_recepcao_sla_finalizado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoriamotivofalha',
            options={'ordering': ['sort_order', 'motivo'], 'verbose_name': 'Cenário', 'verbose_name_plural': 'Cenários'},
        ),
    ]
