# Generated by Django 5.1.15 on 2026-07-30 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0034_auditoriaatividade_observacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriafalhacadastro',
            name='origem',
            field=models.CharField(blank=True, choices=[('auditoria', 'Auditoria'), ('contestacao', 'Contestação'), ('reinspecao', 'Reinspeção'), ('intranet', 'Intranet')], db_index=True, default='', help_text='De onde o registro tratado veio (auditoria, contestação, reinspeção, intranet).', max_length=16),
        ),
        migrations.CreateModel(
            name='QualidadePendenteAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('protocolo', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('nome', models.CharField(blank=True, default='', max_length=255)),
                ('cliente', models.CharField(blank=True, default='', max_length=255)),
                ('workflow', models.CharField(blank=True, default='', max_length=255)),
                ('nivel_hierarquico', models.CharField(blank=True, default='', max_length=255)),
                ('link_demanda', models.URLField(blank=True, default='', max_length=500)),
                ('brflow_raw', models.TextField(blank=True, default='')),
                ('brflow_parsed', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento')], db_index=True, default='pendente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendente_auditoria', to='auditoria.auditoriaatividade')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_pendentes_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qualidade_pendente_auditoria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualidadePendenteContestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('nome', models.CharField(blank=True, default='', max_length=255)),
                ('cliente', models.CharField(blank=True, default='', max_length=255)),
                ('nome_arquivo_original', models.CharField(blank=True, default='', max_length=255)),
                ('data_recepcao', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento')], db_index=True, default='pendente', max_length=20)),
                ('total_protocolos', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendente_contestacao', to='auditoria.auditoriaatividade')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestacao_pendentes_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qualidade_pendente_contestacao',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualidadePendenteReinspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, default='', help_text='ID do protocolo pendente: PDDMMHH-{id}.', max_length=32)),
                ('protocolo', models.CharField(db_index=True, max_length=100)),
                ('usuario', models.CharField(blank=True, default='', max_length=255)),
                ('descricao_irregularidades', models.TextField(blank=True, default='')),
                ('data_contestacao', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cliente', models.CharField(blank=True, default='', max_length=255)),
                ('modulo', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=128)),
                ('observacao', models.TextField(blank=True, default='')),
                ('auditor', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_falha', models.CharField(blank=True, default='reinspecao', max_length=32)),
                ('etapa_falha', models.CharField(blank=True, default='', max_length=255)),
                ('motivo_falha', models.CharField(blank=True, default='', max_length=255)),
                ('nivel_dificuldade', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_documento', models.CharField(blank=True, default='', max_length=255)),
                ('uf_documento', models.CharField(blank=True, default='', max_length=50)),
                ('novo_resultado', models.TextField(blank=True, default='')),
                ('brflow_parsed', models.JSONField(blank=True, default=dict)),
                ('data_resposta', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('analise_concluida_em', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('analise_status', models.CharField(blank=True, choices=[('nao_atribuido', 'Não atribuído'), ('aguardando_analise', 'Aguardando análise'), ('em_analise', 'Em análise')], db_index=True, default='nao_atribuido', max_length=32)),
                ('atribuido_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('analise_iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('fila_origem', models.CharField(blank=True, choices=[('auto', 'Atribuição automática'), ('direcionado', 'Direcionamento manual')], db_index=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinspecao_pendentes_criados', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinspecao_pendentes_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qualidade_pendente_reinspecao',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reinspecaofilahistorico',
            name='pendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reinspecao_historico', to='auditoria.qualidadependentereinspecao'),
        ),
    ]
