# Generated by Django 5.1.15 on 2026-08-03 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0040_dashboard_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriafalhacadastro',
            name='status_falha',
            field=models.CharField(blank=True, choices=[('ativa', 'Ativa'), ('retirada', 'Retirada'), ('mantida', 'Mantida')], db_index=True, default='ativa', help_text='Estado operacional da falha após contestação da liderança.', max_length=16),
        ),
        migrations.CreateModel(
            name='ContestacaoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(choices=[('fraud', 'Fraud'), ('compliance', 'Compliance')], db_index=True, max_length=16)),
                ('origem_tecnica', models.CharField(blank=True, db_index=True, default='', help_text='Espelho de falha.origem (auditoria|contestacao|reinspecao).', max_length=16)),
                ('categoria', models.CharField(choices=[('auditoria_fraud', 'Auditoria Fraud'), ('auditoria_compliance', 'Auditoria Compliance'), ('contestacao_fraud', 'Contestação Fraud'), ('reinspecao_compliance', 'Reinspeção Compliance')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em análise'), ('procedente', 'Procedente'), ('improcedente', 'Improcedente')], db_index=True, default='pendente', max_length=16)),
                ('justificativa_lider', models.TextField()),
                ('parecer_interno', models.TextField(blank=True, default='')),
                ('protocolo', models.CharField(db_index=True, max_length=100)),
                ('agente_usuario', models.CharField(db_index=True, max_length=255)),
                ('atribuida_em', models.DateTimeField(db_index=True, help_text='Data de atribuição da falha ao agente (não a criação desta contestação).')),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('decidida_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestacoes_operacionais_analisadas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestacoes_operacionais_criadas', to=settings.AUTH_USER_MODEL)),
                ('falha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contestacoes_operacionais', to='auditoria.auditoriafalhacadastro')),
            ],
            options={
                'db_table': 'qualidade_contestacao_operacional',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestacaoOperacionalHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('criada', 'Criada'), ('analise_iniciada', 'Análise iniciada'), ('decidida', 'Decidida')], db_index=True, max_length=32)),
                ('status_anterior', models.CharField(blank=True, default='', max_length=16)),
                ('status_novo', models.CharField(blank=True, default='', max_length=16)),
                ('falha_status_anterior', models.CharField(blank=True, default='', max_length=16)),
                ('falha_status_novo', models.CharField(blank=True, default='', max_length=16)),
                ('justificativa', models.TextField(blank=True, default='')),
                ('parecer', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestacao_operacional_historico', to=settings.AUTH_USER_MODEL)),
                ('contestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='auditoria.contestacaooperacional')),
            ],
            options={
                'db_table': 'qualidade_contestacao_operacional_hist',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='contestacaooperacional',
            index=models.Index(fields=['dominio', 'status'], name='qco_dominio_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contestacaooperacional',
            index=models.Index(fields=['categoria', 'status'], name='qco_categoria_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contestacaooperacional',
            index=models.Index(fields=['created_by', 'created_at'], name='qco_lider_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='contestacaooperacional',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pendente', 'em_analise'])), fields=('falha',), name='qco_uma_ativa_por_falha'),
        ),
    ]
