# Generated by Django 5.1.15 on 2026-08-04 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0041_contestacao_operacional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qualidadependentereinspecao',
            name='contexto',
            field=models.CharField(choices=[('reinspecao', 'Reinspeção'), ('auditoria_compliance', 'Auditoria Compliance')], db_index=True, default='reinspecao', max_length=32),
        ),
        migrations.AddField(
            model_name='reinspecaoauditorpresence',
            name='contexto',
            field=models.CharField(choices=[('reinspecao', 'Reinspeção'), ('auditoria_compliance', 'Auditoria Compliance')], db_index=True, default='reinspecao', max_length=32),
        ),
        migrations.AddField(
            model_name='reinspecaofilahistorico',
            name='contexto',
            field=models.CharField(choices=[('reinspecao', 'Reinspeção'), ('auditoria_compliance', 'Auditoria Compliance')], db_index=True, default='reinspecao', max_length=32),
        ),
        migrations.AlterField(
            model_name='reinspecaoauditorpresence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinspecao_presences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reinspecaoauditorpresence',
            constraint=models.UniqueConstraint(fields=('user', 'contexto'), name='reinspecao_presence_user_contexto_uniq'),
        ),
    ]
