# Generated by Django 5.1.15 on 2026-08-06 21:26

from django.db import migrations, models


CATALOG = "duvida_suporte_operacional"
QUESTIONS = [
    "DOCUMENTO ADULTERADO",
    "DOCUMENTO AUSENTE",
    "DOCUMENTO DE CELEBRIDADE/POLÍTICO",
    "DOCUMENTO FOTO DA FOTO",
    "DOCUMENTO FOTOCOPIADO",
    "DOCUMENTO ILEGÍVEL",
    "DOCUMENTO INCOMPLETO",
    "DOCUMENTO POSSUI RASURAS",
    "DOCUMENTO DETERIORADO",
    "FACE ENCONTRADA NA BASE",
    "FACES INCOMPATÍVEIS",
    "FORMATAÇÃO/FONTE E DESALINHAMENTO",
    "FOTO DO CLIENTE DIVERGENTE",
    "FOTO DO CLIENTE IGUAL",
    "FOTO DO CLIENTE NÃO PASSÍVEL",
    "FOTO DO DOCUMENTO ILEGÍVEL",
    "NÚMERO DO CPF AUSENTE",
    "NÚMERO DO CPF DIVERGENTE",
    "SELFIE APRESENTA PARTES ÍNTIMAS",
    "SELFIE COM MÁSCARA DE DISFARCE",
    "SELFIE COM MÁSCARA DE PROTEÇÃO",
    "SELFIE FOTO DA FOTO",
    "SELFIE ILEGÍVEL",
    "SELFIE INVÁLIDA",
    "SELFIE MANIPULADA",
    "SOBREPOSIÇÃO NA FOTO",
]


def seed_questions(apps, schema_editor):
    CatalogItem = apps.get_model("auditoria", "AuditoriaCatalogItem")
    for index, value in enumerate(QUESTIONS):
        CatalogItem.objects.get_or_create(
            catalog=CATALOG,
            value=value,
            defaults={
                "label": value,
                "sort_order": index,
                "active": True,
            },
        )


def remove_questions(apps, schema_editor):
    CatalogItem = apps.get_model("auditoria", "AuditoriaCatalogItem")
    CatalogItem.objects.filter(catalog=CATALOG).delete()


class Migration(migrations.Migration):

    replaces = [
        ('auditoria', '0043_alter_auditoriacatalogitem_catalog'),
    ]

    dependencies = [
        ('auditoria', '0042_fila_contexto_auditoria_compliance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriacatalogitem',
            name='catalog',
            field=models.CharField(choices=[('modulo', 'Módulo'), ('tipo_falha', 'Tipo de falha'), ('novo_resultado', 'Novo resultado'), ('sinalizacao', 'Sinalização'), ('etapa_falha', 'Etapa da falha'), ('nivel_dificuldade', 'Nível de dificuldade'), ('tipo_documento', 'Tipo de documento'), ('uf_documento', 'UF do documento'), ('cruzamento_bases', 'Cruzamento de bases'), ('qualidade_imagem', 'Qualidade da imagem'), ('tipo_acao_controle', 'Tipo de ação (controles)'), ('motivo_base_negativa', 'Motivo (base negativa)'), ('irregularidades_confer', 'Irregularidades Confer'), ('duvida_suporte_operacional', 'Dúvida do suporte operacional')], db_index=True, max_length=32),
        ),
        migrations.RunPython(seed_questions, remove_questions),
    ]
