# Generated by Django 5.2.17 on 2026-08-14 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0051_explicit_quality_dates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditoriafalhacadastro",
            name="auditor_responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="falhas_como_auditor_responsavel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
