# Generated by Django 5.1.15 on 2026-08-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0045_resultado_qualidade'),
        ('auditoria', '0051_explicit_quality_dates'),
    ]

    operations = [
    ]
