# Generated by Django 5.1.15 on 2026-08-18 20:15

import apps.auditoria.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0054_resultado_qualidade_override"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestacaooperacionalhistorico",
            name="evento",
            field=models.CharField(
                choices=[
                    ("criada", "Criada"),
                    ("analise_iniciada", "Análise iniciada"),
                    ("decidida", "Decidida"),
                    ("devolvida_fila", "Devolvida à fila"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="QualidadeComplianceImportArquivo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "contexto",
                    models.CharField(
                        choices=[
                            ("reinspecao", "Reinspeção"),
                            ("auditoria_compliance", "Auditoria Compliance"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(upload_to=apps.auditoria.models.compliance_import_arquivo_upload_to),
                ),
                ("nome_arquivo_original", models.CharField(max_length=255)),
                ("content_sha256", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("protocolos_importados", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qualidade_compliance_import_arquivos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "qualidade_compliance_import_arquivo",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["contexto", "created_at"],
                        name="qual_comp_imp_ctx_created_idx",
                    )
                ],
            },
        ),
    ]
