# Generated by Django 5.2.15 on 2026-08-20 14:16

import apps.auditoria.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.core.management.color import no_style
from django.db import migrations, models


AUDITORIA_COMPLIANCE = 'auditoria_compliance'


def copy_auditoria_compliance_data(apps, schema_editor):
    LegacyPending = apps.get_model('auditoria', 'QualidadePendenteReinspecao')
    NewPending = apps.get_model('auditoria', 'QualidadePendenteAuditoriaCompliance')
    LegacyPresence = apps.get_model('auditoria', 'ReinspecaoAuditorPresence')
    NewPresence = apps.get_model('auditoria', 'AuditoriaComplianceAuditorPresence')
    LegacyHistory = apps.get_model('auditoria', 'ReinspecaoFilaHistorico')
    NewHistory = apps.get_model('auditoria', 'AuditoriaComplianceFilaHistorico')
    LegacyArchive = apps.get_model('auditoria', 'QualidadeComplianceImportArquivo')
    NewArchive = apps.get_model('auditoria', 'AuditoriaComplianceImportArquivo')

    pending_fields = (
        'protocolo', 'usuario', 'descricao_irregularidades', 'data_contestacao',
        'data_analise', 'cliente', 'modulo', 'status', 'observacao', 'auditor',
        'tipo_falha', 'etapa_falha', 'motivo_falha', 'nivel_dificuldade',
        'tipo_documento', 'uf_documento', 'novo_resultado', 'brflow_parsed',
        'data_resposta', 'analise_concluida_em', 'payload', 'analise_status',
        'responsavel_id', 'atribuido_em', 'analise_iniciada_em', 'fila_origem',
        'created_by_id',
    )
    pending_rows = list(
        LegacyPending.objects.filter(contexto=AUDITORIA_COMPLIANCE)
        .values('id', 'created_at', 'updated_at', *pending_fields)
        .iterator(chunk_size=1000)
    )
    pending_objects = [
        NewPending(id=row['id'], **{field: row[field] for field in pending_fields})
        for row in pending_rows
    ]
    NewPending.objects.bulk_create(pending_objects, batch_size=1000, ignore_conflicts=True)
    for row in pending_rows:
        NewPending.objects.filter(pk=row['id']).update(
            created_at=row['created_at'],
            updated_at=row['updated_at'],
        )

    presence_rows = list(
        LegacyPresence.objects.filter(contexto=AUDITORIA_COMPLIANCE)
        .values(
            'id', 'user_id', 'status', 'status_changed_at',
            'last_assigned_at', 'updated_at',
        )
        .iterator(chunk_size=1000)
    )
    NewPresence.objects.bulk_create(
        [
            NewPresence(
                id=row['id'],
                user_id=row['user_id'],
                status=row['status'],
                last_assigned_at=row['last_assigned_at'],
            )
            for row in presence_rows
        ],
        batch_size=1000,
        ignore_conflicts=True,
    )
    for row in presence_rows:
        NewPresence.objects.filter(pk=row['id']).update(
            status_changed_at=row['status_changed_at'],
            updated_at=row['updated_at'],
        )

    new_pending_ids = set(NewPending.objects.values_list('id', flat=True))
    history_rows = list(
        LegacyHistory.objects.filter(contexto=AUDITORIA_COMPLIANCE)
        .values(
            'id', 'falha_id', 'pendente_id', 'auditor_id', 'actor_id',
            'tipo', 'justificativa', 'detalhe', 'created_at',
        )
        .iterator(chunk_size=1000)
    )
    NewHistory.objects.bulk_create(
        [
            NewHistory(
                id=row['id'],
                falha_id=row['falha_id'],
                pendente_id=(
                    row['pendente_id'] if row['pendente_id'] in new_pending_ids else None
                ),
                auditor_id=row['auditor_id'],
                actor_id=row['actor_id'],
                tipo=row['tipo'],
                justificativa=row['justificativa'],
                detalhe=row['detalhe'],
            )
            for row in history_rows
        ],
        batch_size=1000,
        ignore_conflicts=True,
    )
    for row in history_rows:
        NewHistory.objects.filter(pk=row['id']).update(created_at=row['created_at'])

    archive_rows = list(
        LegacyArchive.objects.filter(contexto=AUDITORIA_COMPLIANCE)
        .values(
            'id', 'arquivo', 'nome_arquivo_original', 'content_sha256',
            'protocolos_importados', 'created_by_id', 'created_at',
        )
        .iterator(chunk_size=1000)
    )
    NewArchive.objects.bulk_create(
        [
            NewArchive(
                id=row['id'],
                arquivo=row['arquivo'],
                nome_arquivo_original=row['nome_arquivo_original'],
                content_sha256=row['content_sha256'],
                protocolos_importados=row['protocolos_importados'],
                created_by_id=row['created_by_id'],
            )
            for row in archive_rows
        ],
        batch_size=1000,
        ignore_conflicts=True,
    )
    for row in archive_rows:
        NewArchive.objects.filter(pk=row['id']).update(created_at=row['created_at'])

    if schema_editor is not None:
        copied_models = (NewPending, NewPresence, NewHistory, NewArchive)
        sequence_sql = schema_editor.connection.ops.sequence_reset_sql(
            no_style(), copied_models
        )
        with schema_editor.connection.cursor() as cursor:
            for statement in sequence_sql:
                cursor.execute(statement)


def keep_legacy_data_on_reverse(apps, schema_editor):
    # A origem permanece intacta durante a expansão; o rollback apenas remove as tabelas novas.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0057_pendente_auditoria_falha_tempo_analise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaComplianceImportStaging',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='auditoria/compliance/import_staging/%Y/%m/')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('preview', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_compliance_import_stagings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_compliance_import_staging',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualidadePendenteAuditoriaCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(db_index=True, max_length=100)),
                ('usuario', models.CharField(blank=True, default='', max_length=255)),
                ('descricao_irregularidades', models.TextField(blank=True, default='')),
                ('data_contestacao', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('data_analise', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cliente', models.CharField(blank=True, default='', max_length=255)),
                ('modulo', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=128)),
                ('observacao', models.TextField(blank=True, default='')),
                ('auditor', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_falha', models.CharField(blank=True, default='auditoria', max_length=32)),
                ('etapa_falha', models.CharField(blank=True, default='', max_length=255)),
                ('motivo_falha', models.CharField(blank=True, default='', max_length=255)),
                ('nivel_dificuldade', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_documento', models.CharField(blank=True, default='', max_length=255)),
                ('uf_documento', models.CharField(blank=True, default='', max_length=50)),
                ('novo_resultado', models.TextField(blank=True, default='')),
                ('brflow_parsed', models.JSONField(blank=True, default=dict)),
                ('data_resposta', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('analise_concluida_em', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('analise_status', models.CharField(blank=True, choices=[('nao_atribuido', 'Não atribuído'), ('aguardando_analise', 'Aguardando análise'), ('em_analise', 'Em análise')], db_index=True, default='nao_atribuido', max_length=32)),
                ('atribuido_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('analise_iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('fila_origem', models.CharField(blank=True, choices=[('auto', 'Atribuição automática'), ('direcionado', 'Direcionamento manual')], db_index=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_compliance_pendentes_criados', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_compliance_pendentes_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qualidade_pendente_auditoria_compliance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaComplianceFilaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('atribuicao_auto', 'Atribuição automática'), ('direcionamento_manual', 'Direcionamento manual'), ('reatribuicao', 'Reatribuição'), ('liberacao_status', 'Liberação por status'), ('liberacao_timeout', 'Liberação por timeout'), ('inicio_analise', 'Início da análise'), ('conclusao', 'Conclusão'), ('status_auditor', 'Alteração de status do auditor')], db_index=True, max_length=32)),
                ('justificativa', models.TextField(blank=True, default='')),
                ('detalhe', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_compliance_historico_actor', to=settings.AUTH_USER_MODEL)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_compliance_historico_auditor', to=settings.AUTH_USER_MODEL)),
                ('falha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_compliance_historico', to='auditoria.auditoriafalhacadastro')),
                ('pendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_compliance_historico', to='auditoria.qualidadependenteauditoriacompliance')),
            ],
            options={
                'db_table': 'auditoria_compliance_fila_historico',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaComplianceAuditorPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('ausente', 'Ausente')], db_index=True, default='offline', max_length=16)),
                ('status_changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_assigned_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_compliance_presences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_compliance_auditor_presence',
                'ordering': ['user__username'],
                'constraints': [models.UniqueConstraint(fields=('user',), name='aud_comp_presence_user_uniq')],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaComplianceImportArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.auditoria.models.auditoria_compliance_import_arquivo_upload_to)),
                ('nome_arquivo_original', models.CharField(max_length=255)),
                ('content_sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('protocolos_importados', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_compliance_import_arquivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_compliance_import_arquivo',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['created_at'], name='aud_comp_imp_created_idx')],
            },
        ),
        migrations.RunPython(
            copy_auditoria_compliance_data,
            keep_legacy_data_on_reverse,
        ),
    ]
