# Generated by Django 5.2.15 on 2026-08-20 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0057_pendente_auditoria_falha_tempo_analise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriafalhacadastro',
            name='codigo_irregularidade',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auditoriafalhacadastro',
            name='mapping_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditoriafalhacadastro',
            name='mapping_scenario_status',
            field=models.CharField(blank=True, choices=[('matched', 'Mapeado'), ('unmatched', 'Não mapeado'), ('ambiguous', 'Ambíguo'), ('preexisting', 'Valor preexistente preservado'), ('conflict', 'Conflito com valor preexistente')], db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='auditoriafalhacadastro',
            name='mapping_source_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auditoriafalhacadastro',
            name='mapping_stage_status',
            field=models.CharField(blank=True, choices=[('matched', 'Mapeado'), ('unmatched', 'Não mapeado'), ('ambiguous', 'Ambíguo'), ('preexisting', 'Valor preexistente preservado'), ('conflict', 'Conflito com valor preexistente')], db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='auditoriafalhacadastro',
            name='mapping_version',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='qualidadependentereinspecao',
            name='codigo_irregularidade',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='qualidadependentereinspecao',
            name='mapping_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualidadependentereinspecao',
            name='mapping_scenario_status',
            field=models.CharField(blank=True, choices=[('matched', 'Mapeado'), ('unmatched', 'Não mapeado'), ('ambiguous', 'Ambíguo'), ('preexisting', 'Valor preexistente preservado'), ('conflict', 'Conflito com valor preexistente')], db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='qualidadependentereinspecao',
            name='mapping_source_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='qualidadependentereinspecao',
            name='mapping_stage_status',
            field=models.CharField(blank=True, choices=[('matched', 'Mapeado'), ('unmatched', 'Não mapeado'), ('ambiguous', 'Ambíguo'), ('preexisting', 'Valor preexistente preservado'), ('conflict', 'Conflito com valor preexistente')], db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='qualidadependentereinspecao',
            name='mapping_version',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='ReinspecaoMappingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('import', 'Importação'), ('backfill', 'Backfill'), ('rollback', 'Rollback')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('running', 'Em execução'), ('applied', 'Aplicado'), ('failed', 'Falhou'), ('rolled_back', 'Revertido')], db_index=True, default='running', max_length=16)),
                ('mapping_version', models.CharField(db_index=True, max_length=64)),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('preview_token', models.CharField(blank=True, default='', max_length=64)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reinspecao_mapping_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reinspecao_mapping_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReinspecaoIrregularidadeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_original', models.CharField(max_length=64)),
                ('codigo_normalizado', models.CharField(db_index=True, max_length=64)),
                ('classificacao', models.CharField(blank=True, default='', max_length=2)),
                ('descricao_original', models.TextField()),
                ('descricao_normalizada', models.TextField()),
                ('ilha', models.CharField(blank=True, default='', max_length=255)),
                ('etapa', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_documento', models.CharField(blank=True, default='', max_length=255)),
                ('categoria', models.CharField(blank=True, default='', max_length=128)),
                ('cenario', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('mapping_version', models.CharField(db_index=True, max_length=64)),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('source_row', models.PositiveIntegerField()),
                ('review_status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], db_index=True, default='pending', max_length=16)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reinspecao_mappings_importados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reinspecao_irregularidade_mapping',
                'ordering': ['mapping_version', 'source_row'],
                'indexes': [models.Index(fields=['active', 'review_status', 'codigo_normalizado'], name='reins_map_active_code_idx'), models.Index(fields=['mapping_version', 'active'], name='reins_map_version_act_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_hash', 'source_row'), name='reinspecao_map_hash_row_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ReinspecaoMappingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('pending', 'Pendente'), ('treated', 'Tratado')], max_length=16)),
                ('target_id', models.BigIntegerField()),
                ('before_values', models.JSONField(default=dict)),
                ('after_values', models.JSONField(default=dict)),
                ('filled_fields', models.JSONField(default=list)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='auditoria.reinspecaomappingrun')),
            ],
            options={
                'db_table': 'reinspecao_mapping_change',
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='reins_map_change_target_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'target_type', 'target_id'), name='reins_map_change_target_uniq')],
            },
        ),
    ]
