# Generated by Django 5.2.15 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0058_auditoriacomplianceimportstaging_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestacaooperacionalhistorico",
            name="evento",
            field=models.CharField(
                choices=[
                    ("criada", "Criada"),
                    ("analise_iniciada", "Análise iniciada"),
                    ("decidida", "Decidida"),
                    ("devolvida_fila", "Devolvida à fila"),
                    ("reclassificada", "Reclassificada"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
