# Generated by Django 5.2.15 on 2026-08-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0058_auditoriafalhacadastro_codigo_irregularidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinspecaoirregularidademapping',
            name='classificacao',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
