# Generated by Django 5.1.15 on 2026-08-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0059_alter_contestacaooperacionalhistorico_evento'),
        ('auditoria', '0059_alter_reinspecaoirregularidademapping_classificacao'),
    ]

    operations = [
    ]
