# Generated by Django 5.2.15 on 2026-08-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0061_seed_reinspecao_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestacaooperacional',
            name='cenario_decisao',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contestacaooperacional',
            name='destino_falha',
            field=models.CharField(blank=True, choices=[('retirada', 'Retirar falha'), ('mantida', 'Manter falha')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='contestacaooperacional',
            name='etapa_decisao',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contestacaooperacional',
            name='nivel_decisao',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
