# Generated by Django 5.2.15 on 2026-08-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0062_contestacaooperacional_cenario_decisao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestacaooperacional',
            name='cenario_original',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contestacaooperacional',
            name='etapa_original',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contestacaooperacional',
            name='nivel_original',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
