# Generated by Django 5.2.15 on 2026-08-28 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0065_qualidadeconfiguracaoalteracao_reverte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReinspecaoGedDivergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto', models.CharField(choices=[('reinspecao', 'Reinspeção'), ('auditoria_compliance', 'Auditoria Compliance')], db_index=True, default='reinspecao', max_length=32)),
                ('occurrence_key', models.CharField(max_length=64, unique=True)),
                ('protocolo', models.CharField(db_index=True, max_length=100)),
                ('descricao_irregularidades', models.TextField()),
                ('irregularidade_normalizada', models.TextField()),
                ('data_contestacao', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('reconhecida', 'Reconhecida'), ('resolvida', 'Resolvida')], db_index=True, default='aberta', max_length=16)),
                ('first_seen_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('seen_count', models.PositiveIntegerField(default=1)),
                ('reopened_count', models.PositiveIntegerField(default=0)),
                ('last_source_file', models.CharField(blank=True, default='', max_length=255)),
                ('last_source_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('reconhecida_em', models.DateTimeField(blank=True, null=True)),
                ('reconhecimento_observacao', models.TextField(blank=True, default='')),
                ('resolvida_em', models.DateTimeField(blank=True, null=True)),
                ('resolucao_motivo', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reconhecida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinspecao_ged_divergencias_reconhecidas', to=settings.AUTH_USER_MODEL)),
                ('resolvida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinspecao_ged_divergencias_resolvidas', to=settings.AUTH_USER_MODEL)),
                ('tratado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divergencias_ged', to='auditoria.auditoriafalhacadastro')),
            ],
            options={
                'db_table': 'reinspecao_ged_divergencia',
                'ordering': ['-last_seen_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReinspecaoGedDivergenciaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('detectada', 'Detectada'), ('reconhecida', 'Reconhecida'), ('resolvida', 'Resolvida'), ('reaberta', 'Reaberta')], db_index=True, max_length=16)),
                ('source_file', models.CharField(blank=True, default='', max_length=255)),
                ('source_hash', models.CharField(blank=True, default='', max_length=64)),
                ('detalhe', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinspecao_ged_divergencia_eventos', to=settings.AUTH_USER_MODEL)),
                ('divergencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='auditoria.reinspecaogeddivergencia')),
            ],
            options={
                'db_table': 'reinspecao_ged_divergencia_evento',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReinspecaoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto', models.CharField(choices=[('reinspecao', 'Reinspeção'), ('auditoria_compliance', 'Auditoria Compliance')], db_index=True, default='reinspecao', max_length=32)),
                ('occurrence_key', models.CharField(max_length=64, unique=True)),
                ('protocolo', models.CharField(db_index=True, max_length=100)),
                ('descricao_irregularidades', models.TextField()),
                ('irregularidade_normalizada', models.TextField()),
                ('data_contestacao', models.DateTimeField(db_index=True)),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('last_source_file', models.CharField(blank=True, default='', max_length=255)),
                ('last_source_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('reservada', 'Reservada'), ('pendente', 'Pendente'), ('tratada', 'Tratada')], db_index=True, default='reservada', max_length=16)),
                ('first_seen_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('seen_count', models.PositiveIntegerField(default=1)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pendente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencia_ledger', to='auditoria.qualidadependentereinspecao')),
                ('tratado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias_reinspecao', to='auditoria.auditoriafalhacadastro')),
            ],
            options={
                'db_table': 'reinspecao_ocorrencia',
                'ordering': ['-last_seen_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='reinspecaogeddivergencia',
            name='ocorrencia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='divergencia_ged', to='auditoria.reinspecaoocorrencia'),
        ),
        migrations.AddIndex(
            model_name='reinspecaoocorrencia',
            index=models.Index(fields=['contexto', 'status', 'last_seen_at'], name='reins_ocorr_ctx_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reinspecaoocorrencia',
            index=models.Index(fields=['protocolo', 'data_contestacao'], name='reins_ocorr_proto_data_idx'),
        ),
        migrations.AddIndex(
            model_name='reinspecaogeddivergencia',
            index=models.Index(fields=['contexto', 'status', 'last_seen_at'], name='reins_ged_div_ctx_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reinspecaogeddivergencia',
            index=models.Index(fields=['protocolo', 'data_contestacao'], name='reins_ged_div_proto_data_idx'),
        ),
    ]
