# Generated by Django 5.2.15 on 2026-08-28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0066_reinspecaogeddivergencia_and_more"),
        ("workforce", "0012_agenthistory_sharepoint_item_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditoriafalhacadastro",
            name="status_falha",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ativa", "Ativa"),
                    ("retirada", "Retirada"),
                    ("mantida", "Mantida"),
                    ("em_validacao", "Em validação"),
                    ("nao_conforme", "Não conforme"),
                ],
                db_index=True,
                default="ativa",
                help_text="Estado operacional da falha após contestação da liderança.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="qualidadependenteauditoriafalha",
            name="observacao",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="AuditoriaFalhaValidacaoHistorico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status_de",
                    models.CharField(
                        choices=[
                            ("ativa", "Ativa"),
                            ("retirada", "Retirada"),
                            ("mantida", "Mantida"),
                            ("em_validacao", "Em validação"),
                            ("nao_conforme", "Não conforme"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status_para",
                    models.CharField(
                        choices=[
                            ("ativa", "Ativa"),
                            ("retirada", "Retirada"),
                            ("mantida", "Mantida"),
                            ("em_validacao", "Em validação"),
                            ("nao_conforme", "Não conforme"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("conforme", "Conforme"),
                            ("nao_conforme", "Não conforme"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("observacao", models.TextField()),
                ("snapshot_inicial", models.JSONField(default=dict)),
                ("snapshot_final", models.JSONField(default=dict)),
                ("idempotency_key", models.UUIDField(editable=False, unique=True)),
                (
                    "idempotency_payload_hash",
                    models.CharField(editable=False, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alteracao",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validacao_capacitacao",
                        to="auditoria.auditoriafalhaalteracao",
                    ),
                ),
                (
                    "ator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validacoes_de_falha",
                        to="workforce.agent",
                    ),
                ),
                (
                    "falha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validacoes_capacitacao",
                        to="auditoria.auditoriafalhacadastro",
                    ),
                ),
            ],
            options={
                "db_table": "auditoria_falha_validacao_historico",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status_para", "created_at"],
                        name="aud_fal_val_status_dt_idx",
                    ),
                    models.Index(
                        fields=["ator", "created_at"],
                        name="aud_fal_val_actor_dt_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status_de", "em_validacao")),
                        name="aud_fal_val_status_de_check",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("alteracao__isnull", True),
                                ("resultado", "conforme"),
                                ("status_para", "ativa"),
                            )
                            | models.Q(
                                ("alteracao__isnull", False),
                                ("resultado", "nao_conforme"),
                                ("status_para__in", ("ativa", "nao_conforme")),
                            )
                        ),
                        name="aud_fal_val_resultado_check",
                    ),
                ],
            },
        ),
    ]
