# Generated by Django 5.2.15 on 2026-08-31 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0066_merge_20260828_0001'),
        ('auditoria', '0067_falha_validacao_capacitacao'),
    ]

    operations = [
    ]
