# Generated by Django 5.1.15 on 2026-07-24 15:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NhPrioridadeFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prk_cliente', models.PositiveIntegerField()),
                ('nom_cliente', models.CharField(max_length=512)),
                ('prk_workflow', models.PositiveIntegerField()),
                ('nom_workflow', models.CharField(blank=True, default='', max_length=512)),
                ('prk_nivel_hierarquico', models.PositiveIntegerField(db_index=True)),
                ('nom_nivel_hierarquico', models.CharField(max_length=512)),
                ('prk_fluxo', models.PositiveIntegerField()),
                ('nom_fluxo', models.CharField(max_length=512)),
                ('prk_modulo', models.PositiveIntegerField(blank=True, null=True)),
                ('nom_modulo', models.CharField(blank=True, default='', max_length=255)),
                ('num_prioridade_fluxo', models.IntegerField()),
                ('cod_analise', models.CharField(blank=True, default='', max_length=64)),
                ('hierarchical_level_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('synced_at', models.DateTimeField(help_text='Última alteração efetiva desta linha (não atualiza se o conteúdo for igual).')),
            ],
            options={
                'db_table': 'prioridades_nh_fluxo',
                'ordering': ['nom_nivel_hierarquico', 'num_prioridade_fluxo', 'nom_workflow'],
                'indexes': [models.Index(fields=['prk_nivel_hierarquico', 'num_prioridade_fluxo'], name='prioridades_prk_niv_96bc77_idx'), models.Index(fields=['prk_workflow'], name='prioridades_prk_wor_9df871_idx'), models.Index(fields=['synced_at'], name='prioridades_synced__1703e6_idx')],
                'constraints': [models.UniqueConstraint(fields=('prk_nivel_hierarquico', 'prk_fluxo'), name='uq_prioridades_nh_nivel_fluxo')],
            },
        ),
        migrations.CreateModel(
            name='PrioridadesNhSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, default='', max_length=1024)),
                ('trigger_source', models.CharField(choices=[('system', 'Sistema'), ('user', 'Usuário')], default='system', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('inserted', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('unchanged', models.PositiveIntegerField(default=0)),
                ('deleted', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prioridades_nh_sync_log',
                'ordering': ['-started_at'],
            },
        ),
    ]
