"""Path constants and SharePoint directories for all bots."""

import os
from pathlib import Path

from app.config.env import _ensure_directory, _env_bool, _env_int, _env_str

USER_NAME = os.getenv("USER") or os.getenv("USERNAME") or "default_user"

_USER_HOME = Path.home()
_DOCUMENTS = _USER_HOME / "Documents"
_DOWNLOADS = _USER_HOME / "Downloads"
_APPDATA = Path(os.getenv("APPDATA", _USER_HOME / "AppData" / "Roaming"))
PLAN_IDF_SERASA_BOTS = _APPDATA / "PLAN_IDF_SERASA_BOTS"
_ensure_directory(PLAN_IDF_SERASA_BOTS, "Config")
TRAY_UI_IMAGENS_DIR = Path(_env_str("TRAY_UI_IMAGENS_DIR", str(PLAN_IDF_SERASA_BOTS / "imagens")))
_ensure_directory(TRAY_UI_IMAGENS_DIR, "Tray UI imagens")

DEFAULT_SHAREPOINT_USUARIOS = _USER_HOME / "OneDrive - EXPERIAN SERVICES CORP" / "Planejamento ID&F - Extração de usuários"
_ONEDRIVE_EXP_CORP = _USER_HOME / "OneDrive - EXPERIAN SERVICES CORP"
DEFAULT_SHAREPOINT_BASES = _ONEDRIVE_EXP_CORP / "Planejamento - IDF - Bases"
DEFAULT_SHAREPOINT_BOTS = DEFAULT_SHAREPOINT_BASES / "Bots"
DEFAULT_SHAREPOINT_IDF_BOTS = _ONEDRIVE_EXP_CORP / "Planejamento - IDF - Bots"
DEFAULT_FALHAS_CRITICAS_DIR = DEFAULT_SHAREPOINT_IDF_BOTS / "report-falhas-criticas"
DEFAULT_FALHAS_CRITICAS_EXCEL = DEFAULT_FALHAS_CRITICAS_DIR / "FALHAS_CRITICAS_MANUAL.xlsx"
DEFAULT_FALHAS_CRITICAS_BACKUPS = DEFAULT_FALHAS_CRITICAS_DIR / "backups"
_ensure_directory(DEFAULT_FALHAS_CRITICAS_DIR, "Falhas Críticas")
_ensure_directory(DEFAULT_FALHAS_CRITICAS_BACKUPS, "Falhas Críticas backups")
DEFAULT_SHAREPOINT_PRODUCAO = DEFAULT_SHAREPOINT_BOTS / "prod-unif-hxh"
DEFAULT_SHAREPOINT_ROTINA = (
    DEFAULT_SHAREPOINT_BASES
    / "Relatório gerencial"
    / "Detalhado de Registros"
    / "Detalhado de Registro FY25 Consolidar"
)
DEFAULT_SHAREPOINT_ROTINA_PARQUET = (
    DEFAULT_SHAREPOINT_BASES
    / "Relatório gerencial"
    / "Detalhado de Registros"
    / "Detalhado de Registro Parquet"
)
DEFAULT_SHAREPOINT_MONITOR = (
    DEFAULT_SHAREPOINT_BASES
    / "Detalhado de produtividade"
    / "MONITOR_EVENTOS_FY_27"
)
DEFAULT_SHAREPOINT_DETALHADO = (
    DEFAULT_SHAREPOINT_BASES
    / "Detalhado de produtividade"
    / "DETALHADO_FY_27"
)
DEFAULT_SHAREPOINT_GED_PARQUET = (
    DEFAULT_SHAREPOINT_BASES
    / "Claro indicador"
    / "GED Digitalização"
    / "GED parquet"
)
DEFAULT_SHAREPOINT_GED_CSV = (
    DEFAULT_SHAREPOINT_BASES
    / "Claro indicador"
    / "GED Digitalização"
    / "GED 2.0"
)
PASTA_GED_CSV_GED20 = DEFAULT_SHAREPOINT_GED_CSV

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
BASE_DIR = PROJECT_ROOT
DEFAULT_MODEL = BASE_DIR / "modelo_nivel.xlsx"
DEFAULT_MODELM = BASE_DIR / "modelo_monitor.xlsx"
DEFAULT_SHAREPOINT = DEFAULT_SHAREPOINT_USUARIOS
DEFAULT_DOWNLOAD = Path(_env_str("DOWNLOAD_PATH", str(_DOWNLOADS)))
_ensure_directory(DEFAULT_DOWNLOAD, "Downloads")

_ensure_directory(DEFAULT_SHAREPOINT_USUARIOS, "SharePoint")
XLSX_PATH = Path(_env_str("EXCEL_XLSX_PATH", str(DEFAULT_SHAREPOINT_USUARIOS / "Alterações.xlsx")))
PASTA_CONFIG = Path(_env_str("ROBOT_CONFIG_DIR", str(DEFAULT_SHAREPOINT_BOTS / "config")))
_ensure_directory(PASTA_CONFIG, "Config")
dim_path = PASTA_CONFIG / "dimNivelHierarquico.csv"
STATE_FILE_BRFLOW = PASTA_CONFIG / "processed_rows.json"
STATE_FILE_CONFER = PASTA_CONFIG / "processed_rows_confer.json"

POLL_INTERVAL = _env_int("EXCEL_POLL_INTERVAL", 10)
MAX_RETRIES = _env_int("EXCEL_MAX_RETRIES", 1)
RETRY_DELAY = _env_int("EXCEL_RETRY_DELAY", 10)
DEBOUNCE_SECONDS = float(_env_str("EXCEL_DEBOUNCE_SECONDS", "2"))
HEADLESS = _env_bool("HEADLESS", False)
HEADLESS_DEFAULT = HEADLESS
WORKER_COUNT = _env_int("EXCEL_WORKER_COUNT", 4)
ENABLE_DEBUG_SNAPSHOTS = _env_bool("EXCEL_ENABLE_DEBUG_SNAPSHOTS", False)
IDLE_CLOSE_SECONDS = _env_int("EXCEL_IDLE_CLOSE_SECONDS", 30)
FALLBACK_SCAN_INTERVAL = _env_int("EXCEL_FALLBACK_SCAN_INTERVAL", 300)
FILE_STABILITY_WAIT = float(_env_str("EXCEL_FILE_STABILITY_WAIT", "1.0"))
FILE_STABILITY_RETRIES = _env_int("EXCEL_FILE_STABILITY_RETRIES", 3)
LOG_LEVEL = _env_str("EXCEL_LOG_LEVEL", "INFO")
DEFAULT_INTERVAL = 600
DEFAULT_TIMEOUT = 60
DRIVER_FAILURE_THRESHOLD = _env_int("EXCEL_DRIVER_FAILURE_THRESHOLD", 5)
DRIVER_FAILURE_PAUSE = _env_int("EXCEL_DRIVER_FAILURE_PAUSE", 300)

import logging

LOG_LEVEL_NUM = getattr(logging, LOG_LEVEL.upper(), logging.INFO)

# BOT ROTINA
TIMEOUT_DRIVER_ROTINA = 8
TIMEOUT_DOWNLOAD_ROTINA = 180
TIMEOUT_SHORT_ROTINA = 6
MAX_RETRY_DOWNLOAD_CONFER_ROTINA = max(1, int(os.getenv("CONFER_DOWNLOAD_RETRY", "4") or "4"))

INTERVALO_ATUALIZACAO_COUNTDOWN_ROTINA = 30
INTERVALO_ATUALIZACAO_FINAL_ROTINA = 10
TEMPO_LIMITE_COUNTDOWN_ROTINA = 300

PASTA_MONITOR_TRATADO = DEFAULT_SHAREPOINT_BOTS / "brflow-monitor-tratado"
PASTA_MONITOR_BRUTA = DEFAULT_SHAREPOINT_BOTS / "brflow-monitor-bruto"
PASTA_MONITOR_EVENTOS_BRUTO = DEFAULT_SHAREPOINT_BOTS / "monitor-eventos-bruto"
PASTA_MONITOR_EVENTOS_TRATADO = DEFAULT_SHAREPOINT_BOTS / "monitor-eventos-tratado"
PASTA_PROD_TRATADO = DEFAULT_SHAREPOINT_BOTS / "brflow-prod-tratado"
PASTA_AUDITORIA_TRATADO = DEFAULT_SHAREPOINT_BOTS / "brflow-gauditoria_tratado"
PASTA_AUDITORIA_REPLICADOS_D1 = DEFAULT_SHAREPOINT_BOTS / "brflow-replicadosd1-tratado"
PASTA_GAUDITORIA_ROTINAS = (
    _ONEDRIVE_EXP_CORP
    / "Planejamento ID&F - Rotinas"
)
PASTA_PRODUTIVIDADE_D1_BRUTA = DEFAULT_SHAREPOINT_BOTS / "brflow-prod-bruto"
PASTA_PROD_HXH_BRUTA = DEFAULT_SHAREPOINT_BOTS / "brflow-prod-hxh-bruto"
PASTA_PRODUCAO_CONFER = DEFAULT_SHAREPOINT_BOTS / "confer-prod-bruto"
PASTA_PRODUCAO_CONFER_TRATADO = DEFAULT_SHAREPOINT_BOTS / "confer-prod-tratado"
PASTA_MONITOR_CONFER_TRATADO = DEFAULT_SHAREPOINT_BOTS / "confer-monitor-tratado"
PASTA_DETALHADO_D1 = DEFAULT_SHAREPOINT_BOTS / "brflow-detalhado-tratado"
PASTA_DETALHADO_BRUTO = DEFAULT_SHAREPOINT_BOTS / "brflow-detalhado-bruto"
PASTA_PROD_UNIFICADO_BOTS = DEFAULT_SHAREPOINT_BOTS / "prod-unificado"
PASTA_MONITOR_UNIFICADO_BOTS = DEFAULT_SHAREPOINT_BOTS / "monitor-unificado"

# Produtividade Case Manager (DocumentDB → IDF Docs Relatórios)
_prod_case_root_env = _env_str("PRODUTIVIDADE_CASE_REPORTS_ROOT", "")
DEFAULT_PRODUTIVIDADE_CASE_REPORTS_ROOT = (
    Path(_prod_case_root_env)
    if _prod_case_root_env
    else (_USER_HOME / "EXPERIAN SERVICES CORP" / "IDF Docs - Relatórios")
)
DEFAULT_PRODUTIVIDADE_CASE_TEMP = Path(
    _env_str("PRODUTIVIDADE_CASE_TEMP_DIR", r"C:\relatorios_temp")
)
PASTA_PRODUTIVIDADE_CASE_HORA = DEFAULT_PRODUTIVIDADE_CASE_REPORTS_ROOT / "Relatório de Produtividade por Hora"
PASTA_PRODUTIVIDADE_CASE_TEMPO = DEFAULT_PRODUTIVIDADE_CASE_REPORTS_ROOT / "Relatório de Tempo Logado"
PASTA_PRODUTIVIDADE_CASE_CONS = (
    DEFAULT_PRODUTIVIDADE_CASE_REPORTS_ROOT / "Relatório de Produtividade Consolidado"
)

PASTA_MONITOR_CONFER_TMP = PLAN_IDF_SERASA_BOTS / "downloads_temp" / "rotina"
PASTA_CONFER_PROD_UNIFICADO = DEFAULT_SHAREPOINT_DETALHADO
PASTA_MONITOR_CONFER_UNIFICADO = DEFAULT_SHAREPOINT_MONITOR

PREFIXO_MONITOR_BRFLOW_BRUTO = "brflow-monitor-bruto_"
PREFIXO_MONITOR_EVENTOS_BRUTO = "monitor-eventos-bruto_"
PREFIXO_MONITOR_EVENTOS_TRATADO = "monitor-eventos-tratado_"
PREFIXO_MONITOR_TRATADO = "brflow-monitor-tratado_"
PREFIXO_PROD_TRATADA = "brflow-prod-tratado_"
PREFIXO_PROD_D1 = "brflow-prod-bruto_"
PREFIXO_AUDITORIA = "brflow-gauditoria_tratado_"
PREFIXO_AUDITORIA_REPLICADOS_D1 = "brflow-replicadosd1-tratado_"
PREFIXO_DETALHADO_FINAL = "brflow-detalhado-tratado_"
PREFIXO_DETALHADO_BRUTO = "brflow-detalhado-bruto_"

PREFIXO_CONF_BRUTO = "confer-prod-bruto_"
PREFIXO_CONF_TRATADO = "confer-prod-tratado_"
PREFIXO_MONITOR_CONFER_TRATADO = "confer-monitor-tratado_"

PREFIXO_CONF_PROD_UNIFICADO = "prod-unificado_"
PREFIXO_MONITOR_CONFER_UNIFICADO = "monitor-unificado_"

PREFIXO_GED_TRATADO = "ged-detalhado-tratado_"

PASTA_INDICADOR_QUALIDADE = (
    DEFAULT_SHAREPOINT_BASES
    / "Claro indicador"
    / "GED Contestação"
    / "FY26"
    / "Indicador qualidade"
)
PASTA_GED_IRREGULARIDADE_TRATADO = DEFAULT_SHAREPOINT_BOTS / "ged-irregularidade-tratado"
PASTA_GED_IRREGULARIDADE_HXH_BRUTO = DEFAULT_SHAREPOINT_BOTS / "ged-irregularidade-hxh-bruto"
PASTA_GED_IRREGULARIDADE_COPIA_GERENCIAL = PASTA_INDICADOR_QUALIDADE
PREFIXO_GED_IRREGULARIDADE_TRATADO = "ged-irregularidade-tratado_"
PREFIXO_GED_IRREGULARIDADE_HXH_BRUTO = "ged-irregularidade-bruto_"
_ensure_directory(PASTA_INDICADOR_QUALIDADE, "Indicador qualidade")

PASTA_CONFER_BUSCAR_PROTOCOLO_TRATADO = (
    DEFAULT_SHAREPOINT_BOTS / "confer-buscarpIrregularidade-tratado"
)
PASTA_BUSCA_PROTOCOLOS_GERENCIAL = (
    DEFAULT_SHAREPOINT_BASES
    / "Claro indicador"
    / "GED Contestação"
    / "FY26"
    / "busca_protocolos"
)
PREFIXO_CONFER_BUSCAR_PROTOCOLO_TRATADO = "confer-buscarpIrregularidade-tratado_"
_ensure_directory(PASTA_BUSCA_PROTOCOLOS_GERENCIAL, "Busca protocolos")

# BOT REPLICAÇÃO AUDITORIA
PASTA_REPLICACAO_AUD_BASE = DEFAULT_SHAREPOINT_BOTS / "brflow-auditoria-replic"
PASTA_REPLICACAO_AUD_CONFIG = PASTA_REPLICACAO_AUD_BASE / "config"
PASTA_REPLICACAO_AUD_PROTOCOLOS = PASTA_REPLICACAO_AUD_BASE / "protocolos"
PASTA_REPLICACAO_AUD_RESUMO = PASTA_REPLICACAO_AUD_BASE / "resumo"
PASTA_REPLICACAO_AUD_RELATORIOS = PASTA_REPLICACAO_AUD_RESUMO / "relatorios"
PASTA_REPLICACAO_AUD_CONFIRMED = PASTA_REPLICACAO_AUD_RESUMO / "confirmed"
PASTA_REPLICACAO_AUD_ESCALA = PASTA_REPLICACAO_AUD_CONFIG / "escala"
PASTA_REPLICACAO_AUD_VOLUMETRIA = PASTA_REPLICACAO_AUD_CONFIG / "volumetria"
CONFIG_DEFAULT_XLSX = PASTA_REPLICACAO_AUD_CONFIG / "Default.xlsx"
CONFIG_CATEGORIA_XLSX = PASTA_REPLICACAO_AUD_CONFIG / "Categoria.xlsx"
CONFIG_AUDITORIA_XLSX = CONFIG_DEFAULT_XLSX
PASTA_REPLICACAO_AUD_ESCALA_LEGADO = PASTA_REPLICACAO_AUD_BASE / "escala"
_ensure_directory(PASTA_REPLICACAO_AUD_BASE, "brflow-auditoria-replic")
_ensure_directory(PASTA_REPLICACAO_AUD_CONFIG, "brflow-auditoria-replic/config")
_ensure_directory(PASTA_REPLICACAO_AUD_PROTOCOLOS, "brflow-auditoria-replic/protocolos")
_ensure_directory(PASTA_REPLICACAO_AUD_RESUMO, "brflow-auditoria-replic/resumo")
_ensure_directory(PASTA_REPLICACAO_AUD_RELATORIOS, "brflow-auditoria-replic/resumo/relatorios")
_ensure_directory(PASTA_REPLICACAO_AUD_CONFIRMED, "brflow-auditoria-replic/resumo/confirmed")
_ensure_directory(PASTA_REPLICACAO_AUD_ESCALA, "brflow-auditoria-replic/config/escala")
_ensure_directory(PASTA_REPLICACAO_AUD_VOLUMETRIA, "brflow-auditoria-replic/config/volumetria")
REPLICACAO_AUD_PLANO_PREFIXO = "replicacao_aud_plano_"
REPLICACAO_AUD_RESUMO_PREFIXO = "replicacao_aud_resumo_"
REPLICACAO_AUD_DASHBOARD_PREFIXO = "replicacao_aud_dashboard_"
REPLICACAO_AUD_RELATORIO_PREFIXO = "replicacao_aud_relatorio_"
REPLICACAO_AUD_CONFERENCIA_PREFIXO = "replicacao_aud_conferencia_"
REPLICACAO_AUD_EXECUCAO_PREFIXO = "execucao_"
REPLICACAO_AUD_SEED_DEFAULT = 42
REPLICACAO_AUD_SOBRESCREVER_DEFAULT = False
REPLICACAO_AUD_EXCLUIR_HISTORICO_DEFAULT = True
REPLICACAO_AUD_DIAS_HISTORICO_DEFAULT = 30
REPLICACAO_UPLOAD_CSV_VAZIO_DEFAULT = False
REPLICACAO_CSV_PLACEHOLDER_LIMPEZA = "1"
COLUNA_CONFIG_WORKFLOW = "Workflow"
COLUNA_CONFIG_WORKFLOW_SELENIUM = "Workflow - selenium"
COLUNA_CONFIG_WORKFLOW_D1 = "Workflow d-1"
COLUNA_CONFIG_CLIENTE = "Cliente"
COLUNA_CONFIG_SEGMENTO = "Segmento"
COLUNA_CONFIG_CATEGORIA = "Categoria"
COLUNA_CONFIG_AUTOMATICOS = "Automáticos"
COLUNA_CONFIG_MANUAIS = "Manuais"
COLUNA_CONFIG_TOTAL = "Total"
COLUNA_CONFIG_AMOSTRA = "Amostra Conf. Prod"
COLUNA_CONFIG_AMOSTRA_TOTAL = "Amostra total"
COLUNA_CONFIG_AMOSTRA_DIARIA = "Amostra diária"
COLUNA_CONFIG_META_PRODU = "Meta Produ (diária)"
COLUNA_CONFIG_META_CLIENTE = "Meta Cliente"
META_CLIENTE_LEDGER_ARQUIVO = "meta_cliente_ledger.csv"
META_CLIENTE_MENSAL_ARQUIVO = "meta_cliente_mensal.csv"
REPLICACAO_META_CLIENTE_TOLERANCIA_SUM = 50
META_CLIENTE_ANO_MES_REF_DEFAULT = "execucao"
META_CLIENTE_FALLBACK_SEM_CAP_DEFAULT = True
REPLICACAO_AUD_D1_LIMPAR_PLANOS_AUTOMATICO_DEFAULT = False
REPLICACAO_AUD_D1_MANTER_PLANOS_ULTIMOS_N_DEFAULT = 5
REPLICACAO_AUD_D1_DIAS_RETENCAO_PLANOS_DEFAULT = 0
REPLICACAO_AUD_D1_LIMPAR_PLANOS_AO_GERAR_DEFAULT = False
REPLICACAO_AUD_D1_LIMPAR_PLANOS_APOS_CONCLUSAO_DEFAULT = False
ABA_DEFAULT_WORKFLOW_D1 = "Workflow d1"
COLUNA_CONFIG_STATUS = "Status"
COLUNA_CONFIG_FILA = "Fila"
COLUNA_CONFIG_USAR_ARQUIVO_CSV = "Usar arquivo CSV"
COLUNA_CONFIG_NOME_REGRA_BRFLOW = "nome_regra_brflow"
REPLICACAO_AUD_MARCA_PENDENTE = "PENDENTE ATUALIZAR"
REPLICACAO_AUD_SINCRONIZAR_WORKFLOW_D1_DEFAULT = True
REPLICACAO_LISTAGEM_ESPERA_SEG = 1
PENDENTES_WORKFLOW_D1_CSV = PASTA_REPLICACAO_AUD_CONFIG / "pendentes_workflow_d1.csv"
COLUNA_ESCALA_DATA = "data"
COLUNA_ESCALA_AUDITORES = "auditores_ativos"
COLUNA_ESCALA_AUDITORES_CASE = "auditores_ativos_case"
COLUNA_ESCALA_AUDITORES_BIO = "auditores_ativos_bio"
COLUNA_ESCALA_AUDITORES_REDOC = "auditores_ativos_redoc"
REPLICACAO_FILA_G_AUDITORIA = "G auditoria"
REPLICACAO_FILA_DOCUMENTOSCOPIA_31 = "3.1"
REPLICACAO_FILA_BIO = "Bio"
REPLICACAO_FILA_REDOC = "Redoc"
REPLICACAO_WORKFLOW_COD_G_AUDITORIA = "17047"
REPLICACAO_WORKFLOW_COD_DOCUMENTOSCOPIA_31 = "17426"
REPLICACAO_WORKFLOW_DESTINO_G_AUDITORIA = "G Auditoria - G Auditoria"
REPLICACAO_WORKFLOW_DESTINO_DOCUMENTOSCOPIA_31 = "Documentoscopia 3.1 - Documentoscopia 3.1"
REPLICACAO_WORKFLOW_DESTINO_BIO = "Auditoria Biometria - Auditoria Biometria"
REPLICACAO_WORKFLOW_DESTINO_REDOC = "Auditoria Redoc - Auditoria Redoc"
REPLICACAO_MODO_PROTOCOLOS = "protocolos"
REPLICACAO_MODO_QTD = "qtd"
REPLICACAO_D1_SUBPASTA_BRFLOW = "brflow"
REPLICACAO_D1_SUBPASTA_CASE = "case"
ESCALA_AUDITORES_ARQUIVO = "escala_auditores.csv"
ESCALA_AUDITORES_CSV = PASTA_REPLICACAO_AUD_ESCALA / ESCALA_AUDITORES_ARQUIVO
REPLICACAO_AUD_USAR_ESCALA_DEFAULT = True
REPLICACAO_AUD_META_PRODU_DEFAULT = 300

# BOT REPLICAÇÃO AUDITORIA D-1 (volumetria diária do parquet)
PASTA_REPLICACAO_AUD_D1_BASE = DEFAULT_SHAREPOINT_BOTS / "brflow-auditoria-replic-d1"
PASTA_REPLICACAO_AUD_D1_CONFIG = PASTA_REPLICACAO_AUD_D1_BASE / "config"
PASTA_REPLICACAO_AUD_D1_PROTOCOLOS = PASTA_REPLICACAO_AUD_D1_BASE / "protocolos"
PASTA_REPLICACAO_AUD_D1_RESUMO = PASTA_REPLICACAO_AUD_D1_BASE / "resumo"
PASTA_REPLICACAO_AUD_D1_RELATORIOS = PASTA_REPLICACAO_AUD_D1_RESUMO / "relatorios"
PASTA_REPLICACAO_AUD_D1_CONFIRMED = PASTA_REPLICACAO_AUD_D1_RESUMO / "confirmed"
PASTA_REPLICACAO_AUD_D1_BI = PASTA_REPLICACAO_AUD_D1_BASE / "bi"
ARQUIVO_PARQUET_CONSOLIDADO_D1 = "replicacao_aud_d1_consolidado.parquet"
PASTA_REPLICACAO_AUD_D1_ESCALA = PASTA_REPLICACAO_AUD_D1_CONFIG / "escala"
CONFIG_DEFAULT_D1_XLSX = PASTA_REPLICACAO_AUD_D1_CONFIG / "Default.xlsx"
CONFIG_CATEGORIA_D1_XLSX = PASTA_REPLICACAO_AUD_D1_CONFIG / "Categoria.xlsx"
PASTA_REPLICACAO_AUD_D1_ESCALA_LEGADO = PASTA_REPLICACAO_AUD_D1_BASE / "escala"
_ensure_directory(PASTA_REPLICACAO_AUD_D1_BASE, "brflow-auditoria-replic-d1")
_ensure_directory(PASTA_REPLICACAO_AUD_D1_CONFIG, "brflow-auditoria-replic-d1/config")
_ensure_directory(PASTA_REPLICACAO_AUD_D1_PROTOCOLOS, "brflow-auditoria-replic-d1/protocolos")
_ensure_directory(PASTA_REPLICACAO_AUD_D1_RESUMO, "brflow-auditoria-replic-d1/resumo")
_ensure_directory(PASTA_REPLICACAO_AUD_D1_RELATORIOS, "brflow-auditoria-replic-d1/resumo/relatorios")
_ensure_directory(PASTA_REPLICACAO_AUD_D1_CONFIRMED, "brflow-auditoria-replic-d1/resumo/confirmed")
_ensure_directory(PASTA_REPLICACAO_AUD_D1_BI, "brflow-auditoria-replic-d1/bi")
_ensure_directory(PASTA_REPLICACAO_AUD_D1_ESCALA, "brflow-auditoria-replic-d1/config/escala")
_ensure_directory(
    PASTA_REPLICACAO_AUD_D1_RELATORIOS / REPLICACAO_D1_SUBPASTA_BRFLOW,
    "brflow-auditoria-replic-d1/resumo/relatorios/brflow",
)
_ensure_directory(
    PASTA_REPLICACAO_AUD_D1_RELATORIOS / REPLICACAO_D1_SUBPASTA_CASE,
    "brflow-auditoria-replic-d1/resumo/relatorios/case",
)
REPLICACAO_AUD_D1_PLANO_PREFIXO = "replicacao_aud_d1_plano_"
REPLICACAO_AUD_D1_RESUMO_PREFIXO = "replicacao_aud_d1_resumo_"
REPLICACAO_AUD_D1_DASHBOARD_PREFIXO = "replicacao_aud_d1_dashboard_"
REPLICACAO_AUD_D1_RELATORIO_PREFIXO = "replicacao_aud_d1_relatorio_"
REPLICACAO_AUD_D1_CONFERENCIA_PREFIXO = "replicacao_aud_d1_conferencia_"
REPLICACAO_AUD_D1_EXECUCAO_PREFIXO = "execucao_d1_"
REPLICACAO_AUD_D1_SEED_DEFAULT = 42
REPLICACAO_AUD_D1_SOBRESCREVER_DEFAULT = False
REPLICACAO_AUD_D1_EXCLUIR_HISTORICO_DEFAULT = True
REPLICACAO_AUD_D1_DIAS_HISTORICO_DEFAULT = 30
REPLICACAO_AUD_D1_USAR_ESCALA_DEFAULT = True
REPLICACAO_AUD_D1_META_PRODU_DEFAULT = 300
REPLICACAO_AUD_D1_FALLBACK_PARQUET_DEFAULT = True
ESCALA_AUDITORES_D1_CSV = PASTA_REPLICACAO_AUD_D1_ESCALA / ESCALA_AUDITORES_ARQUIVO
PENDENTES_WORKFLOW_D1_CSV_D1 = PASTA_REPLICACAO_AUD_D1_CONFIG / "pendentes_workflow_d1.csv"
